pom.xml
ramls/order.raml
src/main/java/org/folio/orders/rest/exceptions/HttpException.java
src/main/java/org/folio/rest/impl/OrdersResourceImpl.java
src/main/java/org/folio/rest/impl/PostOrdersHelper.java
src/test/java/org/folio/rest/impl/OrdersResourceImplTest.java
src/test/resources/po_creation_failure.json
src/test/resources/po_line_creation_failure.json
src/test/resources/po_listed_print_monograph.json

See [MODORDERS-21](https://issues.folio.org/projects/MODORDERS/issues/MODORDERS-21) for details.

initial check-in of basic skeleton/BL

---

src/main/java/org/folio/rest/impl/PostOrdersHelper.java
src/test/java/org/folio/rest/impl/OrdersResourceImplTest.java

Better Unit Tests
* Failure to create one or more POLine sub-objects (e.g. Cost/Details/etc.)
* More assertions... check po_line_number, po_number, etc.

MODORDERS-34

---

src/main/java/org/folio/rest/impl/GetOrdersByIdHelper.java
src/main/java/org/folio/rest/impl/PostOrdersHelper.java
src/test/java/org/folio/rest/impl/OrdersResourceImplTest.java

Follow-on to [MODORDERS-56](https://issues.folio.org/browse/MODORDERS-56)...
mod-inventory-storage provides /locations (plural)
mod-orders-storage provides /location (singular)
Here we're interested in the latter.  Fixing the endpoints accordingly.

orders-storage provides /location, inventory-storage provides /locations

---

src/main/java/org/folio/orders/utils/HelperUtils.java
src/main/java/org/folio/rest/impl/DeleteOrdersByIdHelper.java
src/main/java/org/folio/rest/impl/OrdersResourceImpl.java
src/test/java/org/folio/rest/impl/OrdersResourceImplTest.java

Implementation for the /delete end point and corresponding unit test cases

Delete End point initial code

---

src/main/java/org/folio/rest/impl/PostOrdersHelper.java
src/main/java/org/folio/rest/impl/PutOrdersByIdHelper.java
src/test/java/org/folio/rest/impl/OrdersImplTest.java

- ignoring created date at post and put requests
- added additional get call in putOrders to retrieve createdDate before deleting

MODORDERS-82-Purchase-Order-set-createdOn-by-system

---

src/main/java/org/folio/orders/utils/HelperUtils.java
src/main/java/org/folio/rest/impl/OrdersImpl.java
src/test/java/org/folio/rest/impl/OrdersImplTest.java
src/test/resources/mockdata/configurations.entries/test_diku.json

[MODORDERS-102](https://issues.folio.org/browse/MODORDERS-102) fixing PO Line Limit error when creating a PO

MODORDERS-102 PO Line Limit error when creating a PO

---

NEWS.md
pom.xml
src/test/java/org/folio/rest/impl/OrdersImplTest.java

Enable path parameters pattern validation
Upgrade to RMB v23.3.0

MODORDERS-95 Path param pattern validation

---

src/main/java/org/folio/orders/rest/exceptions/ValidationException.java
src/main/java/org/folio/orders/utils/HelperUtils.java
src/main/java/org/folio/rest/impl/AbstractHelper.java
src/main/java/org/folio/rest/impl/GetOrdersByIdHelper.java
src/main/java/org/folio/rest/impl/OrdersImpl.java
src/main/java/org/folio/rest/impl/PostOrderLineHelper.java
src/main/java/org/folio/rest/impl/PostOrdersHelper.java
src/main/java/org/folio/rest/impl/PutOrderLineByIdHelper.java
src/main/java/org/folio/rest/impl/PutOrdersByIdHelper.java
src/main/java/org/folio/rest/impl/ValidationHelper.java
src/test/java/org/folio/rest/impl/OrdersImplTest.java

[MODORDERS-96](https://issues.folio.org/browse/MODORDERS-96) Update Put  /orders/<id>
- Validate if the resulting PO number is unique on PUT order operation
- Update PO lines numbers once user edits PO number of the pending order.

Modorders 109 update put /orders/id

---

ramls/order.raml

MODORDERS-87 - Create GET /orders/po_number endpoint for generating a po_number

---

ramls/order.raml

MODORDERS-87 - Create GET /orders/po_number endpoint (RAML update) (JIRA: [MODORDERS-87](https://issues.folio.org/browse/MODORDERS-87)) - Resolving branch name conflict from https://github.com/folio-org/mod-orders/pull/83.

MODORDERS-87 - Create GET /orders/po_number endpoint (RAML update)

---

src/main/java/org/folio/rest/impl/GetOrdersHelper.java
src/main/java/org/folio/rest/impl/GetPOLinesHelper.java
src/main/java/org/folio/rest/impl/InventoryHelper.java
src/test/java/org/folio/rest/impl/OrdersImplTest.java

Update unit tests to check error responses
Follow up change to https://github.com/folio-org/mod-orders/pull/91 to cover error responses from storage by unit tests
Update unit tests to check error responses

MODORDERS-142 Get PO Lines

---

ramls/order.raml
src/main/java/org/folio/orders/utils/HelperUtils.java
src/main/java/org/folio/orders/utils/ResourcePathResolver.java
src/main/java/org/folio/rest/impl/AbstractHelper.java
src/main/java/org/folio/rest/impl/GetOrdersHelper.java
src/main/java/org/folio/rest/impl/GetReceivingHistoryHelper.java
src/main/java/org/folio/rest/impl/OrdersImpl.java
src/test/java/org/folio/rest/impl/OrdersImplTest.java
src/test/resources/mockdata/receivingHistory/receivingHistory.json

https://issues.folio.org/browse/MODORDERS-105
To view the receiving history.
Call the existing /orders-storage/receiving-history end point from mod orders storage and pass along the query where needed.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is …

MODORDERS 105- Receiving History flow

---

src/main/java/org/folio/rest/impl/PostOrderLineHelper.java

https://issues.folio.org/browse/MODORDERS-153
* adding poLineId mapping for sub objects …

MODORDERS-153 added poLineId mapping for sub objects

---

src/main/java/org/folio/orders/utils/HelperUtils.java
src/main/java/org/folio/rest/impl/InventoryHelper.java
src/main/java/org/folio/rest/impl/PostOrderLineHelper.java
src/main/java/org/folio/rest/impl/PutOrderLineByIdHelper.java
src/test/java/org/folio/rest/impl/OrdersImplTest.java
src/test/resources/mockdata/lines/po_line_collection.json
src/test/resources/mockdata/receivingHistory/receivingHistory.json

[MODORDERS-165](https://issues.folio.org/browse/MODORDERS-165) Add location to receiving_history
[MODORDERS-166](https://issues.folio.org/browse/MODORDERS-166) Add locationId to the piece schema
MODORDERS-165/MODORDERS-166:
- updated ramls/acq-models
MODORDERS-166:
- locationId is set when creating piece records
- unit tests updated
Ideally all of the …

MODORDERS-166/MODORDERS-165 Add locationId to piece and receiving_history schemas

---

pom.xml
ramls/order.raml

[MODINVOSTO-2](https://issues.folio.org/browse/MODINVOSTO-2)  update module due to path changes in [folio-org/acq-models#99](https://github.com/folio-org/acq-models/pull/99)
- updated acq-models
- updated schema reference in raml file
- updated sourceDirectory in pom.xml
Ideally all of the PRs involved in breaking changes would be merged in the same day …

Modinvosto 2 acq-models schema path change

---

NEWS.md
README.md
descriptors/ModuleDescriptor-template.json
pom.xml
ramls/order.raml
src/main/java/org/folio/orders/utils/ErrorCodes.java

[MODORDERS-190](https://issues.folio.org/browse/MODORDERS-190) Create MODORDERS release 4.0.0
- updating interface and raml versions
`orders 4.0`
- required interface version changed:
* `orders-storage.po-lines 4.0`
* `orders-storage.purchase-orders 4.0`
* `orders-storage.receiving-history 2.1`
- News file updated with release details
- Readme file updated
- Do PRs exist for these …

MODORDERS-190 - Release 4.0.0

---

descriptors/ModuleDescriptor-template.json

https://issues.folio.org/browse/MODORDERS-206 - Add missing permission to successfully POST an order
After testing a little, there are few permissions missing from the list, added all the required permissions
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication …

MODORDERS- 206- Adding list of missing permissions

---

src/main/java/org/folio/orders/utils/ErrorCodes.java
src/main/java/org/folio/orders/utils/HelperUtils.java
src/main/java/org/folio/orders/utils/ResourcePathResolver.java
src/test/java/org/folio/rest/impl/OrdersImplTest.java
src/test/resources/mockdata/compositeOrders/getOrders.json
src/test/resources/order_without_vendor_id.json
src/test/resources/po_creation_failure.json
src/test/resources/po_line_creation_failure.json

https://issues.folio.org/browse/MODORDERS-208
- Point to a branch which has new schema changes for required `vendor` UUID field
- Fix the existing failing test for new schema change
- Validate that order fails with a proper error message if required field `vendor` UUID is missing
- Add a new unit test to verify the required field `vendor` 
- Make sure all tests pass
There will be conflicting files(`raml/acq-model`) until this [PR-115]( https://github.com/folio-org/acq-models/pull/115) is merged to master
- What other modules …

Modorders 208 required vendor

---

src/main/java/org/folio/orders/utils/HelperUtils.java
src/main/java/org/folio/rest/impl/InventoryHelper.java
src/main/java/org/folio/rest/impl/PurchaseOrderLineHelper.java
src/test/java/org/folio/rest/impl/OrdersImplTest.java
src/test/resources/minimal_order.json
src/test/resources/mockdata/compositeLines/minimalContent.json
src/test/resources/po_creation_failure.json
src/test/resources/put_order_with_mismatch_id_in_po_lines.json
src/test/resources/put_order_with_po_lines.json

[MODORDERS-136](https://issues.folio.org/browse/MODORDERS-136) Define required fields in the schemas
- removed checks for required fields
- updated unit tests …

MODORDERS-136 Define required fields in the schemas

---

descriptors/ModuleDescriptor-template.json
pom.xml
src/main/java/org/folio/orders/utils/HelperUtils.java

https://issues.folio.org/browse/MODORDERS-223
- Enabling /_/jsonSchemas API which provides schemas for acq-models/mod-orders and mod-orders-storage schemas
- This change will be tested with API test once this PR is merged …

MODORDERS-223: Use Json API for loading module schemas

---

src/main/java/org/folio/orders/utils/HelperUtils.java
src/main/java/org/folio/orders/utils/ResourcePathResolver.java
src/main/java/org/folio/rest/impl/PurchaseOrderHelper.java
src/main/java/org/folio/rest/impl/ReceivingHelper.java
src/test/java/org/folio/rest/impl/MockServer.java
src/test/java/org/folio/rest/impl/PurchaseOrdersApiTest.java

[MODORDERS-227](https://issues.folio.org/browse/MODORDERS-227) use GET /orders-storage/orders  to query a view combining several tables
- sending request to /orders-storage/orders if query not empty
- sending request to /orders-storage/purchase-orders if query is empty
- updating unit tests  to check new logic
Ideally all of the PRs involved in breaking …

MODORDERS-227 Search & Filter: Call GET /orders-storage/orders

---

descriptors/ModuleDescriptor-template.json
pom.xml
src/main/java/org/folio/orders/utils/ErrorCodes.java
src/main/java/org/folio/rest/impl/VendorHelper.java
src/test/java/org/folio/rest/impl/MockServer.java
src/test/java/org/folio/rest/impl/PurchaseOrdersApiTest.java
src/test/resources/mockdata/organizations/active_inactive_access_providers.json
src/test/resources/mockdata/organizations/active_vendor.json
src/test/resources/mockdata/organizations/all_access_providers_active.json
src/test/resources/mockdata/organizations/all_access_providers_not_found.json
src/test/resources/mockdata/organizations/all_inactive_access_providers.json
src/test/resources/mockdata/organizations/inactive_vendor.json
src/test/resources/mockdata/organizations/not_vendor.json
src/test/resources/mockdata/organizations/one_access_provider_not_found.json
src/test/resources/mockdata/organizations/one_access_providers_active.json
src/test/resources/mockdata/organizations/pending_vendor.json
src/test/resources/mockdata/organizations/vendor_bad_content.json
src/test/resources/mockdata/vendors/all_access_providers_not_found.json

https://issues.folio.org/browse/MODORDERS-225
https://issues.folio.org/browse/MODORDERS-225 : To switch to use mod-organizations-storage instead of mod-vendors
1) Add a check to see if the organization is a vendor
2) change all the APIs to mod-organizations-storage
Ideally all of the PRs involved in breaking changes would be merged in the same day to …

MODORDERS-225- Switch to mod-organizations-storage

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml
ramls/order.raml

[MODORDERS-213](https://issues.folio.org/browse/MODORDERS-213) Release 5.0.0
Increase provided interface versions due to non-backward compatible changes and updated required ones …

MODORDERS-213 - Release 5.0.0

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/orders/utils/ResourcePathResolver.java
src/main/java/org/folio/rest/impl/OrdersImpl.java
src/main/java/org/folio/rest/impl/PurchaseOrderLineHelper.java
src/test/java/org/folio/rest/impl/MockServer.java
src/test/java/org/folio/rest/impl/PurchaseOrderLinesApiTest.java

https://issues.folio.org/browse/MODORDERS-228 - use /orders-storage/order-lines endpoint that queries a view
change logic to query /orders-storage/po-lines for all internal calls that query just the po lines or in case there is no query. And use /orders-storage/order-lines for any external queries
Ideally all of the PRs involved in breaking changes would …

MODORDERS-228- changing to use storage order-lines

---

src/main/java/org/folio/rest/impl/InventoryHelper.java
src/test/java/org/folio/rest/impl/ApiTestBase.java
src/test/java/org/folio/rest/impl/MockServer.java
src/test/java/org/folio/rest/impl/PurchaseOrdersApiTest.java
src/test/resources/mockdata/contributorNameTypes/emptyContributorPersonalNameType.json
src/test/resources/mockdata/instanceStatuses/empty_instance_statuses.json
src/test/resources/mockdata/instanceTypes/temp.json

[MODORDERS-233](https://issues.folio.org/browse/MODORDERS-233)  Make the cache keys tenant-specific.
- updated the caching mechanism in inventoryHelper by incorporating the tenantId and name of object to the key.
- added unit test to verify that caching mechanism is tenant-specific.
Ideally all of the PRs involved in breaking changes would be merged in …

MODORDERS-233 add tenant id to cache keys

---

src/main/java/org/folio/rest/impl/CheckinReceivePiecesHelper.java
src/test/java/org/folio/rest/impl/CheckinReceivingApiTest.java
src/test/java/org/folio/rest/impl/MockServer.java
src/test/resources/mockdata/lines/po_line_collection.json

According to [comment](https://issues.folio.org/browse/MODORDERS-221?focusedCommentId=51538&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-51538) holdings not created in case of poLine `createInventory=Instance, Holding`
* Fixed conditions of holdings creation
* Reordered steps of inventory processing
* Updated unit test to verify a proper quantity of holdings created
* [API tests](https://github.com/folio-org/folio-api-tests/pull/195) updated to cover this case  …

MODORDERS-221 - Holdings not created

---

src/test/resources/mockdata/configurations.entries/test_diku_limit_10.json

https://issues.folio.org/browse/MODORDERS-253
* Pointed acq-models submodule to the latest commit
* Added mock configuration data …

MODORDERS-253 Purchase order: bill to and ship to addresses

---

descriptors/ModuleDescriptor-template.json
ramls/examples/errors_400.sample
ramls/examples/errors_500.sample
ramls/order.raml
src/main/java/org/folio/orders/utils/HelperUtils.java
src/main/java/org/folio/rest/impl/OrdersImpl.java
src/main/java/org/folio/rest/impl/PiecesHelper.java
src/test/java/org/folio/rest/impl/MockServer.java
src/test/java/org/folio/rest/impl/PieceApiTest.java

[MODORDERS-257](https://issues.folio.org/browse/MODORDERS-257) Implement PUT and DELETE /orders/pieces/id
- Make straight proxy to storage `/orders-storage/pieces` for PUT and DELETE by id
- Add unit tests
- Add permissions in the module-descriptor
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …

MODORDERS-257 Implement PUT and DELETE /orders/pieces/id

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml
ramls/order.raml

[MODORDERS-258](https://issues.folio.org/browse/MODORDERS-258) - Create MODORDERS release
- Updating NEWS.md 
- Increasing major version of orders interface due to non-backward compatible changes in fund_distribution.json, composite_po_line.json and product_id_type.json (in scope of stories [MODORDERS-237](https://issues.folio.org/browse/MODORDERS-237), [MODORDERS-242](https://issues.folio.org/browse/MODORDERS-242), [MODORDERS-252](https://issues.folio.org/browse/MODORDERS-252) )
- What other modules will these changes …

MODORDERS-258 - Release 6.0.0

---

descriptors/ModuleDescriptor-template.json
ramls/order.raml
src/main/java/org/folio/orders/utils/ResourcePathResolver.java
src/main/java/org/folio/rest/impl/AbstractHelper.java
src/main/java/org/folio/rest/impl/AcquisitionsUnitAssignmentsHelper.java
src/main/java/org/folio/rest/impl/AcquisitionsUnitsImpl.java
src/main/java/org/folio/rest/impl/OrdersImpl.java
src/test/java/org/folio/rest/impl/AcquisitionsUnitAssignmentsTests.java
src/test/java/org/folio/rest/impl/ApiTestSuite.java
src/test/java/org/folio/rest/impl/MockServer.java
src/test/resources/mockdata/acquisitionsUnitAssignments/assignments/assignments.json

[MODORDERS-266](https://issues.folio.org/browse/MODORDERS-266)
Implement CRUD for acquisitions unit assignments …

MODORDERS-266 CRUD for acquisitions unit assignments

---

src/test/resources/mockdata/organizations/active_vendor.json

[MODORGS-32](https://issues.folio.org/browse/MODORGS-32) Include metadata property in JSON schemas …

MODORGS-32 Include metadata property in JSON schemas

---

src/test/resources/mockdata/compositeLines/0009662b-8b80-4001-b704-ca10971f175d.json
src/test/resources/mockdata/compositeLines/c0d08448-347b-418a-8c2f-5fb50248d67e.json
src/test/resources/mockdata/compositeLines/c2755a78-2f8d-47d0-a218-059a9b7391b4.json
src/test/resources/mockdata/compositeLines/fca5fa9e-15cb-4a3d-ab09-eeea99b97a47.json
src/test/resources/mockdata/compositeOrders/07f65192-44a4-483d-97aa-b137bbd96390.json
src/test/resources/mockdata/compositeOrders/1ab7ef6a-d1d4-4a4f-90a2-882aed18af14.json
src/test/resources/mockdata/compositeOrders/bad500aa-aaaa-500a-aaaa-aaaaaaaaaaaa.json
src/test/resources/mockdata/compositeOrders/e5ae4afd-3fa9-494e-a972-f541df9b877e.json
src/test/resources/mockdata/lines/0009662b-8b80-4001-b704-ca10971f175d.json
src/test/resources/mockdata/lines/0dd8f1d2-ac2e-4155-a407-72071f6d5f4a.json
src/test/resources/mockdata/lines/2f443dbe-b3f6-417a-a4ec-db2623920b4a.json
src/test/resources/mockdata/lines/c0d08448-347b-418a-8c2f-5fb50248d67e.json
src/test/resources/mockdata/lines/c2755a78-2f8d-47d0-a218-059a9b7391b4.json
src/test/resources/mockdata/lines/d471d766-8dbb-4609-999a-02681dea6c22.json
src/test/resources/mockdata/lines/fca5fa9e-15cb-4a3d-ab09-eeea99b97a47.json
src/test/resources/mockdata/lines/fe47e95d-24e9-4a9a-9dc0-bcba64b51f56.json
src/test/resources/mockdata/lines/po_line_collection.json
src/test/resources/po_listed_electronic_monograph.json
src/test/resources/po_listed_print_monograph.json
src/test/resources/po_listed_print_monograph_pe_mix.json
src/test/resources/po_listed_print_serial.json
src/test/resources/print_monograph_for_create_inventory_test.json
src/test/resources/put_order_with_mismatch_id_in_po_lines.json
src/test/resources/put_order_with_po_lines.json

Update schemas from acq-models and update test data
Update acq-models submodule to the latest version from master,
Update test data according to changes done in MODORDERS-280
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …

MODORDERS-280 Update test data according to schema changes

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml
ramls/order.raml

[MODORDERS-279](https://issues.folio.org/browse/MODORDERS-279) - mod-orders Release 7.0.0

MODORDERS-279 - Release 7.0.0

---

pom.xml

MODORDERS-279 - Release 7.0.1

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/orders/utils/AcqDesiredPermissions.java
src/main/java/org/folio/rest/impl/PurchaseOrderHelper.java

Unblock  [UIAC-4](https://issues.folio.org/browse/UIAC-4) 
- renamed: 
* orders.acquisitions-units-assignments.item.post->orders.acquisitions-units-assignments.assign
* orders.acquisitions-units-assignments.item.delete->orders.acquisitions-units-assignments.manage
- acquisitions-units-assignments.assign required only in POST /orders/composite-orders if acqUnitIds not empty
- orders.acquisitions-units-assignments.manage required only in PUT /orders/composite-orders/id if acqUnitIds is changed …

MODORDERS-254/MODORDERS-255 Rename assignments permissions

---

descriptors/ModuleDescriptor-template.json

https://issues.folio.org/browse/MODORDERS-283
Added the missing identifier type permission

MODORDERS-283- Missing identifier type permissions

---

pom.xml
ramls/acquisitions-units.raml

Point acquisitions-unit schemas/examples to acquisitions-unit folder with respect to acq-model changes [PR#173](https://github.com/folio-org/acq-models/pull/173)
- Update schemas/examples in raml to point to the common folder
Needs to be merged along:
acq-model - [PR#173](https://github.com/folio-org/acq-models/pull/173)
mod-orders-storage - [PR#147](https://github.com/folio-org/mod-orders-storage/pull/147)
Point acq-model to latest master after merging PR#173
- Do JIRAs exist …

Update raml - Point acq-units schemas/examples to common folder

---

README.md
descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/orders/utils/ErrorCodes.java
src/main/java/org/folio/rest/impl/PurchaseOrderHelper.java
src/test/java/org/folio/rest/impl/PurchaseOrdersApiTest.java
src/test/resources/mockdata/compositeOrders/9d56b621-202d-414b-9e7f-5fefe4422ab3.json
src/test/resources/mockdata/compositeOrders/c1465131-ed35-4308-872c-d7cdf0afc5f7.json
src/test/resources/mockdata/compositeOrders/e5ae4afd-3fa9-494e-a972-f541df9b877e.json
src/test/resources/mockdata/configurations.entries/test_diku_limit_1.json
src/test/resources/mockdata/configurations.entries/test_diku_limit_10.json
src/test/resources/po_listed_print_monograph_pe_mix.json

https://issues.folio.org/browse/MODORDERS-290-
1. Permission required to approve order
2. Config is checked for order approval
1. New permission is added to check if User has permission to approve order 
2. Configuration entry is checked for is "isApprovalRequired" is set to true/false
-  If approval required, order is checked to see if it is approved , if yes user permissions are checked to see if approval permitted, if all of the above is true -> Approval details are set 
-   If approval required and order is not approved, an error is thrown
-   If approval is not needed, then approval details are set only when the order is transitioned to open
i.e approval details are set only if order is approved, else they are always left blank
Before merging this PR, please go through the following …

MODORDERS-290 - Approval required to open Order

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml
ramls/acquisitions-units.raml
ramls/order.raml
src/main/resources/log4j.properties
src/main/resources/log4j2.properties

MODORDERS-300 - Release 8.0.0

---

src/test/java/org/folio/rest/impl/ApiTestBase.java

The unit tests were failing sporadically on slower systems since the awaitability timeouts were too strict...
Relax the timeouts from 1s to 5s.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number …

increase awaitability timeouts

---

NEWS.md
src/test/java/org/folio/rest/impl/ApiTestBase.java

Merging changes from bug fix release-8.0.2 [PR#223](https://github.com/folio-org/mod-orders/pull/223) to master.
Includes commites: [571979...](https://github.com/folio-org/mod-orders/commit/57197916fca5524353acb2331a6264a38d05cfc8
), [e202b9...](https://github.com/folio-org/mod-orders/commit/e202b906e0f4864d7df61b63fb4ed981e6beffad)

Changes from bugfix-8.0.2

---

descriptors/ModuleDescriptor-template.json
pom.xml
ramls/order.raml
src/test/resources/mockdata/compositeLines/0009662b-8b80-4001-b704-ca10971f175d.json
src/test/resources/mockdata/compositeLines/c0d08448-347b-418a-8c2f-5fb50248d67e.json
src/test/resources/mockdata/compositeLines/c2755a78-2f8d-47d0-a218-059a9b7391b4.json
src/test/resources/mockdata/compositeLines/fca5fa9e-15cb-4a3d-ab09-eeea99b97a47.json
src/test/resources/mockdata/compositeOrders/07f65192-44a4-483d-97aa-b137bbd96390.json
src/test/resources/mockdata/compositeOrders/1ab7ef6a-d1d4-4a4f-90a2-882aed18af14.json
src/test/resources/mockdata/compositeOrders/bad500aa-aaaa-500a-aaaa-aaaaaaaaaaaa.json
src/test/resources/mockdata/compositeOrders/e5ae4afd-3fa9-494e-a972-f541df9b877e.json
src/test/resources/mockdata/lines/0009662b-8b80-4001-b704-ca10971f175d.json
src/test/resources/mockdata/lines/0dd8f1d2-ac2e-4155-a407-72071f6d5f4a.json
src/test/resources/mockdata/lines/2f443dbe-b3f6-417a-a4ec-db2623920b4a.json
src/test/resources/mockdata/lines/c0d08448-347b-418a-8c2f-5fb50248d67e.json
src/test/resources/mockdata/lines/d471d766-8dbb-4609-999a-02681dea6c22.json
src/test/resources/mockdata/lines/fca5fa9e-15cb-4a3d-ab09-eeea99b97a47.json
src/test/resources/mockdata/lines/fe47e95d-24e9-4a9a-9dc0-bcba64b51f56.json
src/test/resources/mockdata/lines/po_line_collection.json
src/test/resources/po_listed_electronic_monograph.json
src/test/resources/po_listed_print_monograph.json
src/test/resources/po_listed_print_monograph_pe_mix.json
src/test/resources/po_listed_print_serial.json
src/test/resources/print_monograph_for_create_inventory_test.json
src/test/resources/put_order_with_mismatch_id_in_po_lines.json
src/test/resources/put_order_with_po_lines.json

[MODORDERS-307](https://issues.folio.org/browse/MODORDERS-307) Fund Distribution schema changes
- Updating acq-models and mock files
- Increasing major interface and module's version

MODORDERS-307 Fund Distribution schema changes

---

src/main/java/org/folio/rest/impl/PurchaseOrderLineHelper.java
src/test/java/org/folio/rest/impl/PoNumberApiTest.java
src/test/java/org/folio/rest/impl/PurchaseOrdersApiTest.java
src/test/resources/po_creation_failure.json

https://issues.folio.org/browse/MODORDERS-334
* making code and mock data adjustments
* merge after https://github.com/folio-org/mod-orders-storage/pull/158
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially …

MODORDERS-334 adjustments after the updating poNumber pattern

---

pom.xml

https://issues.folio.org/browse/MODINVOICE-116
* Need to apply the latest schemas (especially receiving_history.json) and adjust sample data 
* pointed acq-models submodule to the latest commit
* updated RMB to v29.0.1 …

MODINVOICE-116 Update purchase order number pattern

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

MODORDERS-330 - Release 9.0.0
orders interface major version changed previously

MODORDERS-330 - Release 9.0.0

---

src/main/java/org/folio/rest/impl/InventoryHelper.java
src/test/java/org/folio/rest/impl/CheckinReceivingApiTest.java
src/test/resources/mockdata/checkIn/checkin-pe-mix-2-electronic-resources.json
src/test/resources/mockdata/checkIn/checkin-pe-mix-2-physical-resources.json
src/test/resources/mockdata/receiving/receive-physical-all-resources.json

https://issues.folio.org/browse/MODORDERS-340
- Update POST checkin, receive with call number
- Update mock data
- Update unit tests
Schema and example changes - https://github.com/folio-org/acq-models/pull/205 …

MODORDERS-340 Add call number while receiving and checkin

---

descriptors/ModuleDescriptor-template.json
pom.xml
ramls/titles.raml
src/main/java/org/folio/orders/utils/HelperUtils.java
src/main/java/org/folio/orders/utils/ResourcePathResolver.java
src/main/java/org/folio/rest/impl/OrdersImpl.java
src/main/java/org/folio/rest/impl/TitlesHelper.java
src/main/java/org/folio/rest/impl/TitlesImpl.java
src/test/java/org/folio/rest/impl/ApiTestBase.java
src/test/java/org/folio/rest/impl/ApiTestSuite.java
src/test/java/org/folio/rest/impl/MockServer.java
src/test/java/org/folio/rest/impl/TestEntities.java
src/test/java/org/folio/rest/impl/TitlesApiTest.java
src/test/resources/mockdata/titles/9a665b22-9fe5-4c95-b4ee-837a5433c95d.json
src/test/resources/mockdata/titles/title.json
src/test/resources/mockdata/titles/title_without_poLine.json
src/test/resources/mockdata/titles/titles.json

https://issues.folio.org/browse/MODORDERS-348
* Implemented titles crud
While it's …

MODORDERS-348 Implemented titles crud

---

descriptors/ModuleDescriptor-template.json
pom.xml
ramls/order.raml
src/test/java/org/folio/rest/impl/ApiTestBase.java
src/test/resources/mockdata/pieces/pieceRecord-af372ac8-5ffb-4560-8b96-3945a12e121b.json
src/test/resources/mockdata/pieces/pieceRecord-fccaca78-ee0b-4579-930d-670bf5102ab0.json
src/test/resources/mockdata/pieces/pieceRecord-fullyreceived-5dbe5481-e5c1-4119-95bc-58e52ffd8374.json
src/test/resources/mockdata/pieces/pieceRecord-poLineId-fe47e95d-24e9-4a9a-9dc0-bcba64b51f56.json
src/test/resources/mockdata/pieces/pieceRecord-poline-not-exists-5b454292-6aaa-474f-9510-b59a564e0c8d.json
src/test/resources/mockdata/pieces/pieceRecord-received-consistent-receipt-status-5b454292-6aaa-474f-9510-b59a564e0c8d2.json
src/test/resources/mockdata/pieces/pieceRecord.json
src/test/resources/mockdata/pieces/pieceRecords-2f443dbe-b3f6-417a-a4ec-db2623920b4a.json
src/test/resources/mockdata/pieces/pieceRecords-9b68e7c2-8818-4387-a405-6567232c1c6f.json
src/test/resources/mockdata/pieces/pieceRecords-cf447221-29b9-481e-947c-9ad545f22888.json
src/test/resources/mockdata/pieces/pieceRecords-d471d766-8dbb-4609-999a-02681dea6c22.json
src/test/resources/mockdata/pieces/pieceRecords-daa9cfd1-b330-4b65-8c2a-3663aaae5130.json
src/test/resources/mockdata/pieces/pieceRecords-f217a5c2-2c56-4d05-9412-a96cfc8e52de.json
src/test/resources/mockdata/pieces/pieceRecords-fe47e95d-24e9-4a9a-9dc0-bcba64b51f56.json
src/test/resources/mockdata/pieces/pieceRecordsCollection.json
src/test/resources/mockdata/receivingHistory/receivingHistory.json

[MODORDERS-350](https://issues.folio.org/browse/MODORDERS-350) - Update piece schema (receipt date)
- updated schemas
- updated mocks and unitTests …

MODORDERS-350 Update piece schema (receipt date)

---

src/main/java/org/folio/rest/impl/InventoryHelper.java
src/test/java/org/folio/rest/impl/ApiTestBase.java
src/test/java/org/folio/rest/impl/CheckinReceivingApiTest.java
src/test/java/org/folio/rest/impl/InventoryInteractionTestHelper.java
src/test/resources/mockdata/checkIn/checkin-pe-mix-2-electronic-resources.json
src/test/resources/mockdata/itemsRecords/inventoryItemsCollection.json
src/test/resources/mockdata/receiving/receive-500-error-for-items-lookup.json
src/test/resources/mockdata/receiving/receive-500-error-for-pieces-lookup.json
src/test/resources/mockdata/receiving/receive-electronic-5-of-10-resources-no-items.json
src/test/resources/mockdata/receiving/receive-physical-all-resources.json

Apply [scheme changes](https://github.com/folio-org/acq-models/pull/217)
- updated item status schema
- fixed mock data, unit tests …

MODORDERS-353 Migrate to new major version of item-storage, inventory, circulation

---

descriptors/ModuleDescriptor-template.json

Organization interface version updating. …

FOLIO-2436 - folio-testing build failure w/interface mismatch (organiztions-storage/orders)

---

src/main/java/org/folio/rest/impl/OrdersImpl.java
src/main/java/org/folio/rest/impl/PurchaseOrderLineHelper.java
src/test/java/org/folio/rest/impl/PurchaseOrderLinesApiTest.java

[MODORDERS-361](https://issues.folio.org/browse/MODORDERS-361) - Cannot edit any receving note fields for POLs created in Daisy
Cannot edit any receving note fields for POLs created in Daisy.
Changing order of ISBN normalization and protected fields changing validation.
Ideally all of the PRs involved in breaking changes would be merged in the same day …

MODORDERS-361 - Cannot edit any receving note fields for POLs created in Daisy

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/orders/utils/ErrorCodes.java
src/main/java/org/folio/orders/utils/POProtectedFields.java
src/main/java/org/folio/rest/impl/PurchaseOrderHelper.java
src/test/java/org/folio/rest/impl/PurchaseOrdersApiTest.java
src/test/resources/minimal_order.json
src/test/resources/mockdata/compositeOrders/07f65192-44a4-483d-97aa-b137bbd96390.json
src/test/resources/mockdata/compositeOrders/11111111-dddd-4444-9999-ffffffffffff.json
src/test/resources/po_listed_print_serial.json

[MODORDERS-351]( https://issues.folio.org/browse/MODORDERS-351) Apply schema changes and add validation of renewal/subscription information
- update acq-models
- increased orders major version
- updated required orders-storage.purchase-order version
- applied validation logic for ongoing field
Ideally all of the PRs involved in breaking changes would be …

MODORDERS-351 Validate renewal/subscription information

---

descriptors/ModuleDescriptor-template.json
pom.xml

[MODFIN-113 ](https://issues.folio.org/browse/MODFIN-113) acq-models submodule in mod-invoice has to be updated
- adding support of finance.transactions 2.0 interface …

MODFIN-113 Add invoiceId and invoiceLineId to the awaitingPayment schema

---

descriptors/ModuleDescriptor-template.json

https://issues.folio.org/browse/MODORDERS-342
* added permissions for ledgers and budgets calls …

MODORDERS-342 missed permissions

---

src/main/java/org/folio/orders/utils/HelperUtils.java
src/main/java/org/folio/orders/utils/validators/CompositePoLineValidationUtil.java
src/main/java/org/folio/rest/impl/OrdersImpl.java
src/main/java/org/folio/rest/impl/PurchaseOrderHelper.java
src/main/java/org/folio/rest/impl/PurchaseOrderLineHelper.java
src/test/java/org/folio/rest/impl/PurchaseOrderLinesApiTest.java
src/test/java/org/folio/rest/impl/PurchaseOrdersApiTest.java
src/test/resources/order_po_line_without_material_type.json

[MODORDERS-176](https://issues.folio.org/browse/MODORDERS-176)
Order creation failure, if material type is absent and order status is PENDING
- Set of validation PO_Line methods were moved into separate util class
- Logic for material type availability check was moved from PO_Line validation to a separate method
Ideally all of the PRs involved in …

[MODORDERS-176] - Failure in inventory interaction, fails the order

---

src/main/java/org/folio/orders/utils/HelperUtils.java
src/main/java/org/folio/rest/impl/InventoryHelper.java
src/main/java/org/folio/rest/impl/PurchaseOrderLineHelper.java
src/test/java/org/folio/rest/impl/InventoryInteractionTestHelper.java
src/test/java/org/folio/rest/impl/PurchaseOrdersApiTest.java

[MODORDERS-371](https://issues.folio.org/browse/MODORDERS-371)
- fixed the counting of the pieces with and without itemId …

MODORDERS-371 Extra pieces are created for "PO Line" with type for "P/E Mix"

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/orders/utils/ErrorCodes.java
src/main/java/org/folio/orders/utils/validators/CompositePoLineValidationUtil.java
src/main/java/org/folio/rest/impl/PurchaseOrderHelper.java
src/main/java/org/folio/rest/impl/PurchaseOrderLineHelper.java
src/test/java/org/folio/rest/impl/ApiTestBase.java
src/test/java/org/folio/rest/impl/MockServer.java
src/test/java/org/folio/rest/impl/PurchaseOrderLinesApiTest.java
src/test/java/org/folio/rest/impl/PurchaseOrdersApiTest.java

https://issues.folio.org/browse/MODORDERS-368
* added required logic
* unit tests updated …

MODORDERS-368 fixed update POL with a specified instanceId

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

https://issues.folio.org/browse/MODORDERS-370
Bugfix release …

MODORDERS-370 10.0.1 bugfix release

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

mod-orders 10.0.2 bugfix release

Tmp bugfix 10.0.2

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

Tmp bugfix 10.0.3

---

src/main/java/org/folio/rest/impl/InventoryHelper.java
src/main/java/org/folio/rest/impl/PiecesHelper.java

[MODORDERS-384](https://issues.folio.org/browse/MODORDERS-384)
- update item on piece update …

[MODORDERS-384] Item status not set to order closed

---

NEWS.md
pom.xml

Hotfix release 10.0.4
The main focus of this bugfix release was to fix bugs related to receiving and instances 
[Full Changelog](https://github.com/folio-org/mod-orders/compare/v10.0.3...v10.0.4)

[MODORDERS-381] - Create MODORDERS Hotfix release 10.0.4

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/rest/impl/FinanceHelper.java

[MODFISTO-85](https://issues.folio.org/browse/MODFISTO-85) - Update the transaction 'source' enum
Update `acq-models` submodule after schema changes
`acq-models` submodule updated
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to …

MODFISTO-85 - Update the transaction 'source' enum

---

descriptors/ModuleDescriptor-template.json

[MODORDSTOR-136](https://issues.folio.org/browse/MODORDSTOR-136) …

MODORDSTOR-136 Title, PoLine schema updates

---

descriptors/ModuleDescriptor-template.json

https://issues.folio.org/browse/MODORDERS-336
* added missed permission
While it's …

MODORDERS-336 Allow to edit Vendor and Bill to on OPEN order

---

src/main/java/org/folio/dao/AbstractHttpDAO.java
src/main/java/org/folio/dao/GenericDAO.java
src/main/java/org/folio/rest/impl/ConfigurationApi.java
src/main/java/org/folio/service/PrefixService.java
src/main/java/org/folio/service/ReasonForClosureService.java
src/main/java/org/folio/service/SuffixService.java

[MODORDERS-389](https://issues.folio.org/browse/MODORDERS-389) 
- fix get API limit, offset params
- set default headers for delete requests …

MODORDERS-389 Unable to remove prefixes/suffixes that are currently used by an existing orders

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/orders/utils/ErrorCodes.java
src/main/java/org/folio/rest/impl/PurchaseOrderHelper.java
src/test/java/org/folio/rest/impl/PurchaseOrdersApiTest.java

https://issues.folio.org/browse/MODORDERS-337
* added permission handler
While it's …

MODORDERS-337 added permission if order is un-opened

---

descriptors/ModuleDescriptor-template.json

See https://issues.folio.org/browse/MODORDERS-388 Securing APIs by default

Modorders 388

---

descriptors/ModuleDescriptor-template.json

Circulation interface updatet from 9.3 -> 9.2 …

[MODORDERS-393] - MODORDERS (mod-orders) release

---

src/main/java/org/folio/rest/impl/FinanceHelper.java
src/main/java/org/folio/rest/impl/PurchaseOrderHelper.java
src/test/java/org/folio/rest/impl/FinanceHelperTest.java
src/test/java/org/folio/rest/impl/PurchaseOrderHelperTest.java
src/test/resources/mockdata/compositeOrders/1ab7ef6a-d1d4-4a4f-90a2-882aed18af20.json
src/test/resources/mockdata/encumbrances/two_pending_encumbrances.json

Fix problem, when add new fund in Pending order and then transfer order to Open
Fix logic …

[MODORDERS-338] - Adjust encumbrances when Order is re-opened

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

Release 11.0.0
Interfaces updated
RMB updated to 30.0.0
NEWS  updated …

[MODORDERS-393] - Release 11.0.0

---

pom.xml
src/main/java/org/folio/orders/utils/HelperUtils.java
src/main/java/org/folio/rest/impl/AbstractHelper.java
src/main/java/org/folio/rest/impl/InitEventBus.java

* obsolete version of mod-configuration-client potentially can cause compilation issues
* updated mod-configuration-client.version and other dependency versions …

MODORDERS-402 updated mod-configuration-client.version 

---

descriptors/ModuleDescriptor-template.json
pom.xml
src/main/java/org/folio/orders/utils/ErrorCodes.java
src/main/java/org/folio/orders/utils/HelperUtils.java
src/main/java/org/folio/rest/impl/PurchaseOrderLineHelper.java
src/test/java/org/folio/rest/impl/PurchaseOrderLinesApiTest.java

[MODORDERS-400](https://issues.folio.org/browse/MODORDERS-400)
Adding pieces, when the quantity is increased
- Call pieces creation if location quantity has been increased.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …

MODORDERS-400 Adding pieces, when the quantity is increased

---

pom.xml
src/main/java/org/folio/rest/impl/FinanceHelper.java
src/main/java/org/folio/rest/impl/PurchaseOrderHelper.java
src/main/java/org/folio/rest/impl/PurchaseOrderLineHelper.java
src/test/java/org/folio/rest/impl/FinanceHelperTest.java

* https://issues.folio.org/browse/MODORDERS-402
* fixed encumbrances for release processing …

MODORDERS-402 fixed encumbrances for release processing

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/rest/impl/FinanceHelper.java
src/main/java/org/folio/rest/impl/PurchaseOrderHelper.java
src/test/java/org/folio/rest/impl/PurchaseOrderHelperTest.java
src/test/java/org/folio/rest/impl/PurchaseOrdersApiTest.java

https://issues.folio.org/browse/MODORDERS-402
* added missed permissions
* added isEmpty checks …

Modorders 402 release encumbrances fix

---

NEWS.md
pom.xml

https://issues.folio.org/browse/MODORDERS-403 …

MODORDERS-403 release 11.0.1

---

src/main/java/org/folio/orders/utils/POLineProtectedFields.java
src/test/java/org/folio/rest/impl/PurchaseOrderLinesApiTest.java
src/test/java/org/folio/rest/impl/PurchaseOrdersApiTest.java

```
{
"errors" : [ {
"message" : "Protected fields can't be modified",
"code" : "protectedFieldChanging",
"parameters" : [ ],
"protectedAndModifiedFields" : [ "fundDistribution" ]
} ],
"total_records" : 1
}
```
* remove fields from protected list
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …

MODORDERS-402 remove fundDistribution from protected fields

---

src/main/java/org/folio/rest/impl/PurchaseOrderHelper.java
src/main/java/org/folio/rest/impl/PurchaseOrderLineHelper.java

https://issues.folio.org/browse/MODORDERS-408
* moved recalculation of estimated price to a proper place …

MODORDERS-408 fix recalculation estimated price

---

NEWS.md
pom.xml

move updates from b11 to master
While it's helpful for reviewers to help identify …

Merge 11.0.3 to master

---

NEWS.md
pom.xml

https://issues.folio.org/browse/MODORDERS-412
* release 11.0.5 …

Tmp release 11.0.5

---

NEWS.md
pom.xml

[MODORDERS-412] Sync master with bugfix

---

pom.xml
src/main/java/org/folio/helper/FinanceHelper.java
src/main/java/org/folio/helper/PurchaseOrderLineHelper.java
src/test/java/org/folio/rest/impl/MockServer.java
src/test/java/org/folio/rest/impl/PurchaseOrderLinesApiTest.java
src/test/resources/mockdata/encumbrances/valid_encumbrances.json

https://issues.folio.org/browse/MODORDERS-416
* added fundDistribution update check …

MODORDERS-416 added fundDistribution check 

---

src/main/java/org/folio/rest/impl/FinanceHelper.java
src/main/java/org/folio/rest/impl/PurchaseOrderLineHelper.java

https://issues.folio.org/browse/MODORDERS-416
* added commits to long live b11
While …

MODORDERS-416 add to long live branch

---

src/main/java/org/folio/helper/FinanceHelper.java
src/test/java/org/folio/rest/impl/MockServer.java
src/test/java/org/folio/rest/impl/PurchaseOrderLinesApiTest.java
src/test/java/org/folio/rest/impl/PurchaseOrdersApiTest.java
src/test/resources/mockdata/compositeLines/bb66b269-76ed-4616-8da9-730d9b817247.json
src/test/resources/mockdata/encumbrances/encumbrance_for_tags_inheritance.json
src/test/resources/po_tags_inheritance.json

[MODORDERS-364](https://issues.folio.org/browse/MODORDERS-364) - Encumbrances - tag inheritance
Encumbrances should inherit tags from their source record (order line in this case)
* Updated open order logic
* Updated order line change logic
* Updated unit tests
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid …

MODORDERS-364 - Encumbrances - tag inheritance

---

NEWS.md
pom.xml

https://issues.folio.org/browse/MODORDERS-417 …

Hotfix Release 11.0.6

---

NEWS.md

* added 11.0.6 release notes
While it's helpful for reviewers to help identify potential …

added 11.0.6 release notes

---

src/main/java/org/folio/helper/PurchaseOrderLineHelper.java
src/test/java/org/folio/rest/impl/PurchaseOrderLinesApiTest.java
src/test/resources/mockdata/compositeLines/c2755a78-2f8d-47d0-a218-059a9b7391b4.json

https://issues.folio.org/browse/MODORDERS-424
* fixed isEncumbranceUpdateNeeded check …

MODORDERS-424 fixed isEncumbranceUpdateNeeded check

---

src/main/java/org/folio/helper/FinanceHelper.java
src/main/java/org/folio/helper/PurchaseOrderLineHelper.java
src/test/java/org/folio/rest/impl/MockServer.java
src/test/java/org/folio/rest/impl/PurchaseOrderLinesApiTest.java

https://issues.folio.org/browse/MODORDERS-420
* fixed validate ExpenseClasses flow
While …

MODORDERS-420 fixed validate ExpenseClasses flow

---

Dockerfile
Jenkinsfile
pom.xml
src/main/java/org/folio/rest/impl/InitAPIs.java

https://issues.folio.org/browse/MODORDERS-419
* RMB updated up to v31.1.1
While it's …

MODORDERS-419 RMB 31.1.1

---

src/main/java/org/folio/helper/PiecesHelper.java
src/main/java/org/folio/helper/PurchaseOrderHelper.java
src/main/java/org/folio/helper/PurchaseOrderLineHelper.java
src/main/java/org/folio/orders/utils/HelperUtils.java
src/test/java/org/folio/helper/PiecesHelperTest.java

https://issues.folio.org/browse/MODORDERS-431 …

[MODORDERS-431] - Piece quantity is not changed, when location is changed in Open order

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

https://issues.folio.org/browse/MODORDERS-418 …

MODORDERS-418 release 11.1.0

---

src/main/java/org/folio/helper/InventoryHelper.java
src/main/java/org/folio/helper/PurchaseOrderLineHelper.java
src/main/java/org/folio/models/PoLineUpdateHolder.java
src/main/java/org/folio/orders/utils/ErrorCodes.java
src/main/java/org/folio/orders/utils/HelperUtils.java
src/main/java/org/folio/orders/utils/LocationUtil.java
src/test/java/org/folio/rest/impl/MockServer.java
src/test/java/org/folio/rest/impl/PurchaseOrderLinesApiTest.java
src/test/resources/mockdata/holdingsRecords/holdingRecords-old-new.json

https://issues.folio.org/browse/MODORDERS-434 …

[MODORDERS-434] - Extra items and holdings are created, when location is changed in Open order

---

descriptors/ModuleDescriptor-template.json
pom.xml
src/main/java/org/folio/config/ApplicationConfig.java
src/main/java/org/folio/config/RestClientsConfiguration.java
src/main/java/org/folio/config/ServicesConfiguration.java
src/main/java/org/folio/helper/FinanceHelper.java
src/main/java/org/folio/orders/utils/ResourcePathResolver.java
src/main/java/org/folio/rest/RestConstants.java
src/main/java/org/folio/rest/core/RestClient.java
src/main/java/org/folio/rest/core/models/RequestContext.java
src/main/java/org/folio/service/exchange/ExchangeRateProviderResolver.java
src/main/java/org/folio/service/exchange/FinanceApiExchangeRateProvider.java
src/main/java/org/folio/service/exchange/FinanceExchangeRateService.java
src/main/java/org/folio/service/exchange/ManualCurrencyConversion.java
src/main/java/org/folio/service/exchange/ManualExchangeRateProvider.java
src/test/java/org/folio/ApiTestSuite.java
src/test/java/org/folio/helper/FinanceHelperTest.java
src/test/java/org/folio/orders/events/handlers/CheckInOrderStatusChangeChangeHandlerTest.java
src/test/java/org/folio/orders/events/handlers/ReceiveOrderStatusChangeHandlerTest.java
src/test/java/org/folio/rest/core/RestClientTest.java
src/test/java/org/folio/rest/impl/ApiTestBase.java
src/test/java/org/folio/rest/impl/MockServer.java
src/test/java/org/folio/rest/impl/PurchaseOrdersApiTest.java
src/test/java/org/folio/service/exchange/ManualExchangeRateProviderTest.java

* [MODORDERS-436] exchange rate not applied to encumbrance when POL in foreign currency.
(cherry picked from commit 15c2db63dfb88c6c23b77308e14fc2dae3f54a82)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially …

Modorders 436 (#371)

---

pom.xml
src/main/java/org/folio/helper/FinanceHelper.java
src/test/java/org/folio/helper/FinanceHelperTest.java

* Fixed with creating of transactions form empty encumbrances pending.
* Code was updated code to conform Sonar requirements.
* Added test cases of skipping of transaction creation when there are no encumbrances presents for order lines.
(cherry picked from commit 1f97e64cfea796c1e96ca116cad3411ec3c38b09)
Ideally all of the PRs involved in breaking …

MODORDERS-430: Can't Unopen order - error response 2 (#373)

---

src/main/java/org/folio/helper/FinanceHelper.java
src/main/java/org/folio/helper/InventoryHelper.java
src/main/java/org/folio/orders/utils/HelperUtils.java

https://issues.folio.org/browse/MODORDERS-446
Calculate encumbrances in FY currency after **_Open->unOpen->Open_** flow …

[Modorders - 446] -exchange rate not applied to encumbrance after Reopen order

---

pom.xml
src/main/java/org/folio/helper/FinanceHelper.java
src/test/java/org/folio/helper/FinanceHelperTest.java

Reverts folio-org/mod-orders#376

Revert "MODORDERS-430: Can't Unopen order - error response 2 (#373)"

---

src/main/java/org/folio/helper/InventoryHelper.java
src/main/java/org/folio/helper/PurchaseOrderLineHelper.java
src/main/java/org/folio/orders/utils/LocationUtil.java
src/test/java/org/folio/helper/InventoryHelperTest.java
src/test/java/org/folio/rest/impl/PurchaseOrderLinesApiTest.java

Fix regression issues 
Creation and update logic has been changed …

[MODORDERS-434] - Fix regression in piece update/create

---

NEWS.md
pom.xml

https://issues.folio.org/browse/MODORDERS-444

MODORDERS-444 release 11.1.1

---

src/main/java/org/folio/helper/AbstractHelper.java
src/main/java/org/folio/helper/InventoryHelper.java
src/main/java/org/folio/helper/PurchaseOrderHelper.java
src/main/java/org/folio/helper/PurchaseOrderLineHelper.java
src/main/java/org/folio/orders/utils/HelperUtils.java
src/main/java/org/folio/service/configuration/ConfigurationEntriesService.java

https://issues.folio.org/browse/MODORDERS-447
* fixed load configuration
While it's …

MODORDERS-447 fix system currency conversion

---

src/main/java/org/folio/helper/PurchaseOrderLineHelper.java
src/test/java/org/folio/rest/impl/ApiTestBase.java
src/test/java/org/folio/rest/impl/PurchaseOrdersApiTest.java

[MODORDSTOR-197] - mod-orders update acq-models

---

NEWS.md
pom.xml

Signed-off-by: Yauheni Kuzmianok <yauheni_kuzmianok@epam.com> …

MODORDERS-458 Bugfix release NEWS.md update

---

descriptors/ModuleDescriptor-template.json
pom.xml
ramls/check-in.raml
ramls/order-lines.raml
ramls/order-templates.raml
ramls/order.raml
ramls/pieces.raml
ramls/po-number.raml
ramls/receive.raml
ramls/receiving-history.raml
ramls/rollover.raml
src/main/java/org/folio/rest/impl/CompositePoLineAPI.java
src/main/java/org/folio/rest/impl/OrderTemplatesAPI.java
src/main/java/org/folio/rest/impl/OrdersApi.java
src/main/java/org/folio/rest/impl/PiecesAPI.java
src/main/java/org/folio/rest/impl/PoNumberAPI.java
src/main/java/org/folio/rest/impl/ReceivingAPI.java

[MODORDERS-438](https://issues.folio.org/browse/MODORDERS-438)
- split orders ramls
- defined and stubbed APIs: POST /orders/rollover and POST /orders/composite-orders/{id}/re-encumber
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is …

MODORDERS-438 Define re-encumber and rollover orders business API

---

descriptors/ModuleDescriptor-template.json
pom.xml
ramls/rollover.raml
src/main/java/org/folio/helper/FinanceHelper.java
src/main/java/org/folio/helper/PurchaseOrderHelper.java
src/main/java/org/folio/orders/utils/ResourcePathResolver.java
src/main/resources/log4j2.properties
src/test/java/org/folio/helper/PurchaseOrderHelperTest.java
src/test/java/org/folio/rest/impl/MockServer.java
src/test/java/org/folio/service/finance/FundServiceTest.java
src/test/resources/log4j2-test.properties
src/test/resources/mockdata/compositeOrders/07f65192-44a4-483d-97aa-b137bbd96390.json
src/test/resources/mockdata/compositeOrders/1ab7ef6a-d1d4-4a4f-90a2-882aed18af20.json
src/test/resources/mockdata/ledgerFyRolloverErrors/ledger_fiscal_year_rollover_error_collection.json
src/test/resources/mockdata/ledgerFyRollovers/ledger_fiscal_year_rollover_collection.json

https://issues.folio.org/browse/MODORDERS-465
* populated needReencumber field
While …

MODORDERS-465 populate needReencumber field

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/config/RestClientsConfiguration.java
src/main/java/org/folio/config/ServicesConfiguration.java
src/main/java/org/folio/helper/AbstractHelper.java
src/main/java/org/folio/helper/PurchaseOrderHelper.java
src/main/java/org/folio/helper/PurchaseOrderLineHelper.java
src/main/java/org/folio/orders/utils/ErrorCodes.java
src/main/java/org/folio/orders/utils/ResourcePathResolver.java
src/main/java/org/folio/service/orders/OrderInvoiceRelationService.java
src/main/resources/log4j2.properties
src/test/java/org/folio/helper/PurchaseOrderHelperTest.java
src/test/java/org/folio/rest/impl/ApiTestBase.java
src/test/java/org/folio/rest/impl/MockServer.java
src/test/resources/log4j2-test.properties

https://issues.folio.org/browse/MODORDERS-454
* restrict deleting the order/line linked to invoice …

MODORDERS-454 User should NOT be able to delete an order or order line that is related to an invoice

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/helper/InventoryHelper.java
src/main/java/org/folio/helper/OrderTemplatesHelper.java
src/main/java/org/folio/orders/events/handlers/AbstractOrderStatusHandler.java
src/main/java/org/folio/orders/events/handlers/ReceiptStatusConsistency.java
src/main/java/org/folio/orders/utils/AsyncUtil.java

Fix issue with permissions and module stuck
Permissions added
Use worker thread pool for map JsonObject to java object …

[MODORDERS-463] - Fix issue with permissions and module stuck

---

descriptors/ModuleDescriptor-template.json

[MODORDERS-476](https://issues.folio.org/browse/MODORDERS-476) 
- added "finance.funds.budget.item.get" module permission to PUT /orders/order-lines/id API
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially …

MODORDERS-476 Investigate invoice approval error

---

src/main/java/org/folio/helper/PurchaseOrderHelper.java
src/main/java/org/folio/orders/utils/HelperUtils.java
src/test/java/org/folio/helper/PurchaseOrderHelperTest.java

https://issues.folio.org/browse/MODORDERS-472 …

[MODORDERS-472] - Potentially incorrect number of units/price display in order cost details

---

src/main/java/org/folio/helper/PurchaseOrderHelper.java
src/main/java/org/folio/orders/utils/HelperUtils.java
src/main/java/org/folio/service/finance/EncumbranceService.java
src/test/java/org/folio/orders/utils/HelperUtilsTest.java

[MODORDERS-443](https://issues.folio.org/browse/MODORDERS-443)
Update logic for supporting manually exchange rate for purchase order line
- Add manual exchange rate for totalEstimatedPrice
- Add manual exchange rate for Encumbrances calculations
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …

[MODORDERS-443] - Update logic for supporting manually exchange rate for purchase order line

---

pom.xml
src/main/java/org/folio/helper/CheckinHelper.java
src/main/java/org/folio/helper/CheckinReceivePiecesHelper.java
src/main/java/org/folio/helper/PurchaseOrderHelper.java
src/main/java/org/folio/helper/ReceivingHelper.java
src/main/java/org/folio/orders/events/handlers/ReceiptStatusConsistency.java
src/main/java/org/folio/service/orders/PurchaseOrderService.java
src/test/java/org/folio/TestConfig.java
src/test/java/org/folio/rest/impl/CheckinReceivingApiTest.java
src/test/java/org/folio/rest/impl/PurchaseOrdersApiTest.java
src/test/java/org/folio/service/orders/PurchaseOrderLineServiceTest.java
src/test/java/org/folio/service/orders/PurchaseOrderServiceTest.java
src/test/resources/mockdata/lines/6e2b169a-ebeb-4c3c-a2f2-6233ff9c59ae.json
src/test/resources/mockdata/lines/po_line_collection.json
src/test/resources/mockdata/pieces/pieceRecords-05a95f03-eb00-4248-9f2e-2bd05957ff04.json
src/test/resources/mockdata/pieces/pieceRecordsCollection.json
src/test/resources/mockdata/receiving/receive-physical-ongoing.json
src/test/resources/po_listed_print_serial.json

https://issues.folio.org/browse/MODORDERS-459
* Update POL status of "Ongoing" order to Ongoing when order is Open …

 MODORDERS-459 Update POL status of "Ongoing" order to Ongoing when order is Open

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/config/ApplicationConfig.java
src/main/java/org/folio/models/ReEncumbranceHolder.java
src/main/java/org/folio/orders/utils/AsyncUtil.java
src/main/java/org/folio/orders/utils/ErrorCodes.java
src/main/java/org/folio/rest/impl/OrdersApi.java
src/main/java/org/folio/service/finance/BudgetRestrictionService.java
src/main/java/org/folio/service/finance/BudgetService.java
src/main/java/org/folio/service/finance/EncumbranceService.java
src/main/java/org/folio/service/finance/FundService.java
src/main/java/org/folio/service/finance/RolloverErrorService.java
src/main/java/org/folio/service/finance/RolloverRetrieveService.java
src/main/java/org/folio/service/finance/TransactionService.java
src/main/java/org/folio/service/orders/CompositePurchaseOrderService.java
src/main/java/org/folio/service/orders/OrderReEncumberService.java
src/main/java/org/folio/service/orders/OrderRolloverService.java
src/main/java/org/folio/service/orders/ReEncumbranceHoldersBuilder.java
src/test/java/org/folio/ApiTestSuite.java
src/test/java/org/folio/rest/impl/MockServer.java
src/test/java/org/folio/service/finance/EncumbranceServiceTest.java
src/test/java/org/folio/service/orders/OrderReEncumberServiceTest.java
src/test/java/org/folio/service/orders/OrderRolloverServiceTest.java
src/test/java/org/folio/service/orders/PurchaseOrderServiceTest.java
src/test/java/org/folio/service/orders/ReEncumbranceHoldersBuilderTest.java
src/test/resources/mockdata/ledgerFyRolloverProgress/ledger_fiscal_year_rollover_progress_collection.json
src/test/resources/mockdata/ledgerFyRollovers/ledger_fiscal_year_rollover_collection.json

[MODORDERS-439](https://issues.folio.org/browse/MODORDERS-439)
* collect all data in ReEncumbranceHolder using  ReEncumbranceHoldersBuilder
* check funds exist => check rollover completed => check budgets exist => check budgets have enough money to create encumbrances (for encumbrances to be created) => create encumbrances for  current fiscal year (if absent) =>  update fyroAdjustmentAmount =>  update po lines =>  delete rollover errors
- Do JIRAs exist to update the impacted …

MODORDERS-439 Implement re-encumber orders logic

---

descriptors/ModuleDescriptor-template.json
src/test/resources/mockdata/compositeLines/c0d08448-347b-418a-8c2f-5fb50248d67e.json
src/test/resources/mockdata/compositeOrders/0cb6741d-4a00-47e5-a902-5678eb24478d.json
src/test/resources/mockdata/compositeOrders/bad500aa-aaaa-500a-aaaa-aaaaaaaaaaaa.json
src/test/resources/mockdata/compositeOrders/e5ae4afd-3fa9-494e-a972-f541df9b877e.json
src/test/resources/mockdata/lines/0dd8f1d2-ac2e-4155-a407-72071f6d5f4a.json
src/test/resources/mockdata/lines/2f443dbe-b3f6-417a-a4ec-db2623920b4a.json
src/test/resources/mockdata/lines/6e2b169a-ebeb-4c3c-a2f2-6233ff9c59ae.json
src/test/resources/mockdata/lines/c0d08448-347b-418a-8c2f-5fb50248d67e.json
src/test/resources/mockdata/lines/c2755a78-2f8d-47d0-a218-059a9b7391b4.json
src/test/resources/mockdata/lines/d471d766-8dbb-4609-999a-02681dea6c22.json
src/test/resources/mockdata/lines/fca5fa9e-15cb-4a3d-ab09-eeea99b97a47.json
src/test/resources/mockdata/lines/fe47e95d-24e9-4a9a-9dc0-bcba64b51f56.json
src/test/resources/mockdata/lines/po_line_collection.json
src/test/resources/order_po_line_without_material_type.json
src/test/resources/po_listed_electronic_monograph.json
src/test/resources/po_listed_print_monograph.json
src/test/resources/po_listed_print_monograph_pe_mix.json
src/test/resources/po_listed_print_serial.json
src/test/resources/po_tags_inheritance.json
src/test/resources/print_monograph_for_create_inventory_test.json
src/test/resources/put_order_with_mismatch_id_in_po_lines.json
src/test/resources/put_order_with_po_lines.json

[MODORDSTOR-146](https://issues.folio.org/browse/MODORDSTOR-146) …

MODORDSTOR-146 Pair of "refNumber" and "refNumberType" in PO line should be an array

---

descriptors/ModuleDescriptor-template.json
pom.xml
src/main/java/org/folio/config/ApplicationConfig.java
src/main/java/org/folio/helper/AcquisitionsUnitsHelper.java
src/main/java/org/folio/helper/ProtectionHelper.java
src/main/java/org/folio/helper/PurchaseOrderHelper.java
src/main/java/org/folio/helper/TitlesHelper.java
src/main/java/org/folio/orders/utils/HelperUtils.java
src/main/java/org/folio/orders/utils/ResourcePathResolver.java
src/main/java/org/folio/service/TagService.java
src/test/java/org/folio/helper/PurchaseOrderHelperTest.java
src/test/java/org/folio/rest/impl/MockServer.java
src/test/java/org/folio/service/TagServiceTest.java
src/test/resources/mockdata/tags/tag.json
src/test/resources/mockdata/tags/tags_collection.json

https://issues.folio.org/browse/MODORDERS-470
* create tags if missing
While it's …

Modorders 470 Create new tags centrally

---

src/main/java/org/folio/helper/PurchaseOrderHelper.java
src/main/java/org/folio/service/TagService.java
src/test/resources/po_listed_print_serial.json

* https://issues.folio.org/browse/MODORDERS-470
* modify poLine tags (lowercase, no spaces) …

MODORDERS-470 modify poLine tags

---

src/main/java/org/folio/helper/PurchaseOrderHelper.java
src/test/resources/po_listed_print_serial.json

https://issues.folio.org/browse/MODORDERS-470
* exclude empty tags …

MODORDERS-470 exclude empty tags

---

src/main/java/org/folio/service/orders/OrderRolloverService.java
src/test/java/org/folio/service/orders/OrderRolloverServiceTest.java

[MODORDERS-479](https://issues.folio.org/browse/MODORDERS-479)
Update fundDistributions during order rollover
- Update logic to calculate amount fund distributions in count of estimatedTotal
- Update test
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is …

[MODORDERS-479] Update fundDistributions during order rollover

---

src/main/java/org/folio/models/ReEncumbranceHolder.java
src/main/java/org/folio/service/orders/OrderReEncumberService.java
src/main/java/org/folio/service/orders/ReEncumbranceHoldersBuilder.java
src/test/java/org/folio/service/orders/OrderReEncumberServiceTest.java
src/test/java/org/folio/service/orders/ReEncumbranceHoldersBuilderTest.java

https://issues.folio.org/browse/MODORDERS-480
Logic for calculating new encumbrances is changed and based on fund distributions  …

[MODORDERS-480] - Create encumbrances based on fundDistribution percentage value during re-encumber

---

descriptors/ModuleDescriptor-template.json
pom.xml
src/main/java/org/folio/completablefuture/FolioVertxCompletableFuture.java
src/main/java/org/folio/helper/AbstractHelper.java
src/main/java/org/folio/helper/InventoryHelper.java
src/main/java/org/folio/helper/PurchaseOrderHelper.java
src/main/java/org/folio/helper/PurchaseOrderLineHelper.java
src/main/java/org/folio/rest/core/RestClient.java
src/main/java/org/folio/rest/impl/OrdersApi.java
src/main/java/org/folio/service/configuration/ConfigurationEntriesService.java

https://issues.folio.org/browse/MODORDERS-484
* saved response from mod-configuration and mod-invenory to reduce amount of requests
* increased docker container memory …

Modorders 484 iris fix

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/helper/AbstractHelper.java
src/main/java/org/folio/helper/InventoryHelper.java
src/main/java/org/folio/helper/PurchaseOrderLineHelper.java

https://issues.folio.org/browse/MODORDERS-484
* decreased amount of similar requests to the mod-configuration and mod-inventory …

MODORDERS-484 decreased amount of similar requests to the mod-configuration and mod-inventory

---

PERSONAL_DATA_DISCLOSURE.md

[MODORDERS-468] - Add personal data disclosure form

---

NEWS.md
pom.xml

[MODORDERS-462] - Release 12.0.0

---

descriptors/ModuleDescriptor-template.json

Update version of the required "circulation" dependency
Version in the descriptor updated …

Update version of the required "circulation" dependency

---

NEWS.md
pom.xml

Bugfix release 12.0.1
While it's helpful for reviewers to help identify potential …

[MODORDERS-491] - Bugfix release 12.0.1

---

src/main/java/org/folio/helper/PurchaseOrderHelper.java
src/main/java/org/folio/orders/utils/ErrorCodes.java
src/main/java/org/folio/orders/utils/validators/OngoingOrderValidator.java
src/main/java/org/folio/orders/utils/validators/OrderValidator.java
src/test/java/org/folio/ApiTestSuite.java
src/test/java/org/folio/orders/utils/validators/OngoingOrderValidatorTest.java

Validate that renewals is present in ongoing orders > https://issues.folio.org/browse/MODORDERS-224 …

[MODORDERS-224] Add renewalInterval and renewalDate existing validation.

---

src/main/java/org/folio/service/finance/expenceclass/ExpenseClassValidationService.java
src/test/java/org/folio/ApiTestSuite.java
src/test/java/org/folio/service/expenceclass/ExpenseClassValidationServiceTest.java

Unable to open an order with 2 POLs that have different currencies > https://issues.folio.org/browse/MODORDERS-496 …

[MODORDERS-496] Fix DuplicateKeyException.

---

src/main/java/org/folio/orders/utils/validators/OngoingOrderValidator.java
src/test/java/org/folio/orders/utils/validators/OngoingOrderValidatorTest.java

Renewals validation prevents opening of ongoing orders > https://issues.folio.org/browse/MODORDERS-499 …

[MODORDERS-499] Fix validation of the renewal date and interval.

---

src/main/java/org/folio/helper/PurchaseOrderHelper.java
src/main/java/org/folio/service/inventory/InventoryManager.java
src/test/java/org/folio/helper/InventoryInteractionTestHelper.java
src/test/java/org/folio/helper/PurchaseOrderHelperTest.java
src/test/java/org/folio/rest/impl/MockServer.java
src/test/java/org/folio/rest/impl/PieceApiTest.java
src/test/java/org/folio/rest/impl/PurchaseOrdersApiTest.java
src/test/resources/mockdata/compositeOrders/11111111-dddd-4444-9999-ffffffffffff.json
src/test/resources/mockdata/lines/2bafc9e1-9dd3-4ede-9f23-c4a03f8bb2d5.json

Support reference on holding in the Location for the Open order operation
Logic of the open order updated …

MODORDERS-493 Update open order logic with holding ids storing

---

src/main/java/org/folio/service/finance/transaction/OpenToCloseEncumbranceStrategy.java

[MODORDERS-513](https://issues.folio.org/browse/MODORDERS-513)
Closing an order fails when all encumbrances are already released
- Add fix to prevent update encumbrance if all released.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that …

[MODORDERS-513]

---

pom.xml
ramls/titles.raml
src/main/java/org/folio/helper/PurchaseOrderHelper.java
src/main/java/org/folio/helper/PurchaseOrderLineHelper.java
src/main/java/org/folio/rest/impl/TitlesApi.java
src/test/java/org/folio/rest/impl/CheckinReceivingApiTest.java
src/test/java/org/folio/rest/impl/PurchaseOrdersApiTest.java

* https://issues.folio.org/browse/MODORDERS-486
*  updated rmb 33.0.0 …

Modorders-486 update rmb 33.0.0

---

src/main/java/org/folio/helper/PurchaseOrderHelper.java

* https://issues.folio.org/browse/MODORDERS-486
* removed readonly fields due to conversion issues …

MODORDERS-486 fix readonly fields

---

src/main/java/org/folio/helper/CheckinReceivePiecesHelper.java
src/main/java/org/folio/service/pieces/PiecesService.java

[MODORDERS-519](https://issues.folio.org/browse/MODORDERS-519)
This is a followup to the previous PR to fix issues with receiving pieces for package orders.
It fixes an additional issue when a piece is created with an itemId.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing …

[MODORDERS-519] Fixed itemId being removed when creating a piece, and fixed a variable name

---

NEWS.md
pom.xml
src/main/java/org/folio/helper/CheckinReceivePiecesHelper.java
src/main/java/org/folio/helper/PiecesHelper.java
src/main/java/org/folio/orders/utils/ErrorCodes.java
src/main/java/org/folio/orders/utils/HelperUtils.java
src/test/java/org/folio/rest/impl/CheckinReceivingApiTest.java
src/test/java/org/folio/rest/impl/MockServer.java

Hotfix for MODORDERS-519
Fixed receiving with package POL (which can have more than 1 instance)
Fixed creating a piece with an itemId …

[MODORDERS-519] Hotfix - Receiving pieces for package POL

---

NEWS.md
pom.xml
src/main/java/org/folio/service/finance/transaction/OpenToCloseEncumbranceStrategy.java

[MODORDERS-513](https://issues.folio.org/browse/MODORDERS-513)
Included [fix](https://github.com/folio-org/mod-orders/pull/449) for MODORDERS-513. …

[MODORDERS-513] Hotfix 12.0.3

---

NEWS.md
pom.xml

* https://issues.folio.org/browse/MODORDERS-485
While it's …

MODORDERS-485 release 12.1.0

---

src/main/java/org/folio/helper/PurchaseOrderLineHelper.java

* https://issues.folio.org/browse/MODORDERS-521
* adjusted open order check
While it's …

MODORDERS-521 Allow updating quantity and location for Open order if it is initiated by EBSCONET

---

src/main/java/org/folio/helper/PurchaseOrderLineHelper.java
src/main/java/org/folio/orders/utils/POLineProtectedFields.java

* https://issues.folio.org/browse/MODORDERS-521
*  removed source from protected fields …

Modorders 521 removed source from protected fields

---

src/main/java/org/folio/service/inventory/InventoryManager.java
src/test/java/org/folio/helper/InventoryManagerTest.java

Remove unused code.
Deleting the method and the tests for it.

MODORDERS-533: Remove unused InventoryManager.updateItemRecords

---

src/main/java/org/folio/helper/PurchaseOrderHelper.java

https://issues.folio.org/browse/MODORDERS-547
Fixed the logic of receiving pieces for line …

[MODORDERS-547] - Delete piece modal no longer appears for NON manualy add piece for receiving POLs

---

src/main/java/org/folio/config/ApplicationConfig.java
src/main/java/org/folio/helper/PurchaseOrderHelper.java
src/main/java/org/folio/orders/events/handlers/AbstractOrderStatusHandler.java
src/main/java/org/folio/service/finance/transaction/EncumbranceService.java
src/main/java/org/folio/service/finance/transaction/OpenToPendingEncumbranceStrategy.java
src/test/java/org/folio/service/finance/transaction/OpenToPendingEncumbranceStrategyTest.java

* https://issues.folio.org/browse/MODORDERS-544
* updated unopen logic
While it's …

MODORDERS-544 Unopen fails after a rollover for an order created in the previous year

---

src/main/java/org/folio/helper/PurchaseOrderHelper.java

https://issues.folio.org/browse/MODORDERS-547
1. Fixed the logic of receiving pieces for line …

[MODORDERS-547] - Master : Delete piece modal no longer appears for ON manually add piece for receiving POLs

---

src/main/java/org/folio/service/finance/transaction/EncumbranceRelationsHoldersBuilder.java
src/main/java/org/folio/service/finance/transaction/TransactionSummariesService.java

https://issues.folio.org/browse/MODORDERS-545
* update transaction summary if it exists …

MODORDERS-545 Transaction log not updated when deleting a POL

---

NEWS.md
pom.xml

[MODORDERS-543] - R1 hotfix 4. Version 12.0.5 …

[MODORDERS-543] - R1 hotfix 4. Version 12.0.5

---

ramls/pieces.raml
src/main/java/org/folio/rest/impl/PiecesAPI.java

Move business logic, which manages Item creation for Piece, from UI to Back-End
1. Query parameter added. As we don't split DB model and UI DTO, then it is time consuming rework approach
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that …

[MODORDERS-538] - Create item query param added to POST and PUT

---

ramls/pieces.raml
src/main/java/org/folio/rest/impl/PiecesAPI.java
src/main/java/org/folio/service/pieces/PieceDeleteFlowManager.java

Support for confirming the deletion of a holding when deleting a piece
While it's …

[MODORDERS-538] - support for confirming the deletion of a holding when deleting a piece

---

src/main/java/org/folio/service/inventory/InventoryManager.java

[MODORDERS-573](https://issues.folio.org/browse/MODORDERS-573) - Update instance matching logic
Used a CQL array search to look for instances by product more precisely. …

[MODORDERS-573] Fixed instance matching

---

src/main/java/org/folio/config/ApplicationConfig.java
src/main/java/org/folio/service/pieces/flows/create/PieceCreateFlowInventoryManager.java
src/main/java/org/folio/service/pieces/flows/create/PieceCreateFlowValidator.java
src/main/java/org/folio/service/pieces/flows/delete/PieceDeleteFlowManager.java
src/test/java/org/folio/rest/impl/MockServer.java
src/test/java/org/folio/rest/impl/PieceApiTest.java
src/test/java/org/folio/service/pieces/flows/create/PieceCreateFlowInventoryManagerTest.java

https://issues.folio.org/browse/MODORDERS-538
Fix issue with validation of the item creation when "Manual piece create" is true …

[MODORDERS-538] - Manual piece create fix

---

src/main/java/org/folio/service/pieces/flows/create/PieceCreateFlowValidator.java
src/test/java/org/folio/service/pieces/flows/create/PieceCreateFlowValidatorTest.java

Remove validation of the pending order
While it's helpful for reviewers to help identify …

[MODORDERS-575] - No way to create piece for pending order with create piece = True

---

src/main/java/org/folio/service/finance/transaction/EncumbranceService.java

Fix the wirk of the ClosedToOpenEncumbranceStrategy
Fixed query …

MODORDERS-588 Fixed a bug in the payment scenario

---

src/main/java/org/folio/orders/utils/HelperUtils.java
src/main/java/org/folio/rest/impl/BaseApi.java

…dy exist
https://issues.folio.org/browse/MODORDERS-605
Must be transmitted to UI appropriate message about duplicate acquisition unit name
{
"errors" : [ {
"message" : "Field Name must be unique",
"code" : "uniqueFieldAcquisitionsUnitNameError",
"parameters" : [ {
"key" : "field",
"value" : "Name"
}, {
"key" : "entity",
"value" : "AcquisitionsUnit"
} ]
} ],
"total_records" : 1
}
https://github.com/folio-org/mod-finance/pull/59
- …

[MODORDERS-605] Return helpful and clear error code, when Acquisition unit name already exist

---

src/main/java/org/folio/helper/PurchaseOrderHelper.java
src/main/java/org/folio/service/inventory/InventoryManager.java
src/main/java/org/folio/service/orders/PurchaseOrderStorageService.java
src/main/java/org/folio/service/orders/flows/update/open/OpenCompositeOrderInventoryService.java
src/main/java/org/folio/service/orders/flows/update/open/OpenCompositeOrderManager.java
src/main/java/org/folio/service/orders/flows/update/open/OpenCompositeOrderPieceService.java
src/test/java/org/folio/service/inventory/InventoryManagerTest.java
src/test/java/org/folio/service/orders/flows/open/OpenCompositeOrderPieceServiceTest.java
src/test/java/org/folio/service/pieces/flows/create/PieceCreateFlowInventoryManagerTest.java
src/test/resources/mockdata/configurations.entries/test_diku_limit_1.json

https://issues.folio.org/browse/MODORDERS-557
Check config before performing instance matching. …

MODORDERS-557 - support disable instance matching config

---

src/main/java/org/folio/service/pieces/flows/BasePieceFlowUpdatePoLineService.java

https://issues.folio.org/browse/MODORDERS-608 …

[MODORDERS-608] - Update Piece flow : Location quantity is not updated if create inventory is None and location provided

---

src/main/java/org/folio/service/pieces/flows/update/PieceUpdateFlowInventoryManager.java
src/test/java/org/folio/service/pieces/flows/update/PieceUpdateFlowInventoryManagerTest.java

https://issues.folio.org/browse/MODORDERS-607
Added check to skip item update if item is absent. …

MODORDERS-607 - piece without item can now be updated

---

src/main/java/org/folio/service/pieces/flows/delete/PieceDeleteFlowPoLineService.java
src/main/java/org/folio/service/pieces/validators/PieceValidatorUtil.java
src/test/java/org/folio/service/orders/flows/open/OpenCompositeOrderPieceServiceTest.java
src/test/java/org/folio/service/pieces/flows/delete/PieceDeleteFlowPoLineServiceTest.java

https://issues.folio.org/browse/MODORDERS-606 …

[MODORDERS-606] - Pieces with no location can be delete and do not update order quantity

---

src/main/java/org/folio/service/pieces/flows/BasePieceFlowUpdatePoLineService.java
src/main/java/org/folio/service/pieces/flows/update/PieceUpdateFlowPoLineService.java
src/test/java/org/folio/service/pieces/flows/create/PieceCreateFlowInventoryManagerTest.java
src/test/java/org/folio/service/pieces/flows/create/PieceCreateFlowPoLineServiceTest.java
src/test/java/org/folio/service/pieces/flows/delete/PieceDeleteFlowManagerTest.java
src/test/java/org/folio/service/pieces/flows/delete/PieceDeleteFlowPoLineServiceTest.java
src/test/java/org/folio/service/pieces/flows/update/PieceUpdateFlowPoLineServiceTest.java

https://issues.folio.org/browse/MODORDERS-614 …

[MODORDERS-614] - Add a piece the quantity and location are updated but the estimated price does not change

---

src/main/java/org/folio/service/orders/OrderReEncumberService.java
src/test/java/org/folio/service/orders/OrderRolloverServiceTest.java

https://issues.folio.org/browse/MODORDERS-599
Updated method org.folio.service.orders.OrderReEncumberService#adjustPoLineCost  …

MODORDERS-599. Update re-emcumbered logic to support "initialEncumbered"

---

descriptors/ModuleDescriptor-template.json
ramls/acquisition_method.raml
src/main/java/org/folio/config/ApplicationConfig.java
src/main/java/org/folio/orders/utils/ResourcePathResolver.java
src/main/java/org/folio/rest/core/exceptions/ErrorCodes.java
src/main/java/org/folio/rest/impl/AcquisitionMethodAPI.java
src/main/java/org/folio/service/AcquisitionMethodsService.java
src/test/java/org/folio/ApiTestSuite.java
src/test/java/org/folio/rest/impl/AcquisitionMethodAPITest.java
src/test/java/org/folio/rest/impl/MockServer.java
src/test/resources/mockdata/acquisitionMethods/acquisitionMethods.json

Add acquisition method API
https://issues.folio.org/browse/MODORDERS-624
While it's …

[MODORDERS-620] - Added acquisition method API

---

src/test/resources/mockdata/acquisitionMethods/acquisitionMethods.json

https://issues.folio.org/browse/MODORDSTOR-267 …

MODORDSTOR-267. Rename collection field name for Acquisition method collection

---

src/main/java/org/folio/rest/core/exceptions/ErrorCodes.java
src/main/java/org/folio/service/AcquisitionMethodsService.java
src/test/java/org/folio/rest/impl/AcquisitionMethodAPITest.java

Fix deletion
While it's helpful for reviewers to help identify potential problems, …

[MODORDSTOR-256] - fixed deletion

---

src/main/java/org/folio/service/orders/OrderInvoiceRelationService.java
src/test/java/org/folio/service/orders/OrderInvoiceRelationServiceTest.java

https://issues.folio.org/browse/MODORDERS-609
Allow to delete order lines without mod-invoice installed, if order is not related to invoice
Added check that the order is linked to some invoice. Return null if there is no relationship
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing …

MODORDERS-609. Deleting an order line fails without mod-invoice

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/rest/core/exceptions/ExceptionUtil.java

Add permissions
While it's helpful for reviewers to help identify potential problems, …

[MODORDERS-609] - Added permissions

---

pom.xml

https://issues.folio.org/browse/MODORDERS-630 …

MODORDERS-630. Kiwi R3 2021 - Log4j vulnerability verification and correction

---

NEWS.md
pom.xml

KIWI Bugfix 12.2.5
While it's helpful for reviewers to help identify potential problems, …

[MODORDERS-633] - KIWI Bugfix 12.2.5

---

pom.xml

https://issues.folio.org/browse/MODORDERS-631 …

MODORDERS-631. Juniper R2 2021 - Log4j vulnerability verification and correction

---

NEWS.md
pom.xml

https://issues.folio.org/browse/MODORDERS-632 …

MODORDERS-632. Juniper R2 2021 HF #5 module release

---

descriptors/ModuleDescriptor-template.json

Adapt mod-orders to the changes in circulation module.
Resolves:https://issues.folio.org/browse/MODORDERS-628

MODORDERS-628 Update circulation interface version

---

src/main/java/org/folio/orders/utils/POLineProtectedFields.java

[MODORDSTOR-277] - Update acq-models

---

src/main/java/org/folio/service/finance/transaction/EncumbranceRelationsHoldersBuilder.java

[MODORDERS-638](https://issues.folio.org/browse/MODORDERS-638) - Invoice can be approved but not paid when expense class added at point of invoice
The issue with invoices cames from the fact that encumbrances were recreated when an expense class was modified in an order line fund distribution. Invoice lines have a link to encumbrances that was not getting updated.
The issue is resolved by updating an existing encumbrance instead of recreating it when a fund distribution is modified (it could be a fund or expense class change). Behavior stays the same as before when the new fund distribution does not have an encumbrance id yet or when the fund and expense class are not modified.
- Does this PR meet …

[MODORDERS-638] Update encumbrances instead of recreating them when the fund distribution is modified

---

descriptors/ModuleDescriptor-template.json

[MODORDERS-655] - Add description of the permissions

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

https://issues.folio.org/browse/MODORDERS-650 …

MODORDERS-650 Tmp release 12.3.0

---

src/main/java/org/folio/service/finance/budget/BudgetRestrictionService.java
src/test/java/org/folio/service/finance/budget/BudgetRestrictionServiceTest.java

[MODORDERS-652](https://issues.folio.org/browse/MODORDERS-652) - Open order : Error message does not indicate what Fund does not have money
Similar to MODINVOICE-357 - in the exception, return fund codes instead of budget ids as parameters.
Also updated the unit tests.
We still need a UI story to display the fund codes.
Ideally all of the PRs involved in …

[MODORDERS-652] Return fund codes in checkEncumbranceRestrictions

---

src/main/java/org/folio/orders/utils/FundDistributionUtils.java

[MODORDERS-646](https://issues.folio.org/browse/MODORDERS-646) - Fund distribution total not correct when 3 Fund distributions are used
Compare the remaining amount to 0 taking precision into account.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is …

[MODORDERS-646] Fixed validateFundDistributionTotal

---

.gitignore
src/main/java/org/folio/helper/CheckinReceivePiecesHelper.java
src/main/java/org/folio/helper/OrderTemplatesHelper.java
src/main/java/org/folio/helper/PurchaseOrderHelper.java
src/main/java/org/folio/helper/PurchaseOrderLineHelper.java
src/main/java/org/folio/helper/ReceivingHelper.java
src/main/java/org/folio/helper/VendorHelper.java
src/main/java/org/folio/orders/utils/HelperUtils.java
src/main/java/org/folio/rest/core/models/RequestEntry.java
src/main/java/org/folio/service/finance/transaction/EncumbranceService.java
src/main/java/org/folio/service/inventory/InventoryManager.java
src/main/java/org/folio/service/orders/PurchaseOrderLineService.java
src/main/java/org/folio/service/orders/PurchaseOrderStorageService.java
src/main/java/org/folio/service/orders/flows/update/open/OpenCompositeOrderHolderBuilder.java
src/main/java/org/folio/service/orders/flows/update/open/OpenCompositeOrderInventoryService.java
src/main/resources/log4j2-json.properties
src/main/resources/log4j2.properties
src/test/java/org/folio/helper/InventoryInteractionTestHelper.java
src/test/java/org/folio/orders/events/handlers/HandlersTestHelper.java
src/test/java/org/folio/orders/utils/HelperUtilsTest.java
src/test/java/org/folio/rest/impl/AcquisitionMethodAPITest.java
src/test/java/org/folio/rest/impl/OrderTemplateTest.java
src/test/java/org/folio/service/inventory/InventoryManagerTest.java
src/test/java/org/folio/service/invoice/InvoiceLineServiceTest.java
src/test/java/org/folio/service/orders/AcquisitionsUnitsServiceTest.java

https://issues.folio.org/browse/MODORDERS-641
* cached mod-configuration requests
* switched to sequential poline processing
* cached isbn requests …

MODORDERS-641 fixed parallel processing

---

src/main/java/org/folio/service/FundsDistributionService.java
src/test/java/org/folio/service/orders/FundsDistributionServiceTest.java
src/test/java/org/folio/service/orders/ReEncumbranceHoldersBuilderTest.java

Reverts folio-org/mod-orders#567

Revert "[MODFIN-238] - Using the exchange rate when opening an order"

---

src/main/java/org/folio/config/ApplicationConfig.java
src/main/java/org/folio/service/orders/HoldingsSummaryService.java
src/test/java/org/folio/service/inventory/HoldingsSummaryServiceTest.java

Holdings related to package POLs are not displaying Order information in acquisition accordion …

[MODORDERS-672] - Displaying Order information in acquisition accordion

---

src/main/java/org/folio/service/FundsDistributionService.java
src/test/java/org/folio/service/orders/FundsDistributionServiceTest.java
src/test/java/org/folio/service/orders/ReEncumbranceHoldersBuilderTest.java

Exchange Rate is ignored for encumbrance calculating …

[MODORDERS-677] - Exchange Rate

---

src/main/java/org/folio/helper/PurchaseOrderLineHelper.java

After edit Encumbrance detail not shown on POL fund distribution …

[MODORDERS-673] - Encumbrance detail shown on POL fund distribution

---

src/main/java/org/folio/service/pieces/flows/create/PieceCreateFlowManager.java

[MODORDERS-681](https://issues.folio.org/browse/MODORDERS-681) - Errors when creating pieces in quick succession
Fixed PieceCreateFlowManager's createPiece implementation. There is an integration test for it (extracted from MODFISTO-260).
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …

[MODORDERS-681] Order line updates should not be async

---

descriptors/ModuleDescriptor-template.json

[MODORDERS-662] - Fix permissions

---

descriptors/ModuleDescriptor-template.json

Reverts folio-org/mod-orders#579

Revert "[MODORDERS-662] - Fix permissions"

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/rest/impl/BaseApi.java
src/main/java/org/folio/service/finance/transaction/EncumbranceRelationsHoldersBuilder.java

[MODFISTO-303](https://issues.folio.org/browse/MODFISTO-303) - Enable optimistic locking
- Updated schemas
- Updated affected API versions
- Report a 409 if a 409 is returned from mod-finance.
- Made sure a transaction update uses the previous version
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking …

[MODFISTO-303] update for finance optimistic locking

---

src/main/java/org/folio/service/invoice/InvoiceService.java

[MODORDERS-664] - Fix CQL issue

---

src/main/java/org/folio/helper/PurchaseOrderLineHelper.java
src/main/java/org/folio/orders/utils/POLineProtectedFields.java
src/test/java/org/folio/rest/impl/PurchaseOrderLinesApiTest.java
src/test/resources/mockdata/lines/0009662b-8b80-4001-b704-ca10971f222d.json

[MODEORDERS-700] - Receive 'protected fields can’t be modified' error for eresource fields on PO line that is a Physical Resource

---

src/main/java/org/folio/service/orders/flows/update/open/OpenCompositeOrderManager.java

[MODORDERS-691]-Updated class OpenCompositeOrderManager.java

---

src/main/java/org/folio/helper/PurchaseOrderHelper.java
src/main/java/org/folio/service/orders/PurchaseOrderLineService.java
src/main/java/org/folio/service/orders/flows/update/reopen/ReOpenCompositeOrderManager.java
src/test/java/org/folio/rest/impl/MockServer.java
src/test/java/org/folio/rest/impl/PurchaseOrdersApiTest.java

Fill incoming order with POLs
While it's helpful for reviewers to help identify …

[MODORDERS-664] - Release encumbrances when POL payment status is set to canceled.

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/config/ApplicationConfig.java
src/main/java/org/folio/models/orders/lines/update/OrderLineUpdateInstanceHolder.java
src/main/java/org/folio/rest/core/RestClient.java
src/main/java/org/folio/service/inventory/InventoryManager.java
src/main/java/org/folio/service/orders/lines/update/OrderLinePatchOperationService.java
src/main/java/org/folio/service/orders/lines/update/OrderLineUpdateInstanceHandler.java
src/main/java/org/folio/service/orders/lines/update/OrderLineUpdateInstanceHolder.java
src/main/java/org/folio/service/orders/lines/update/OrderLineUpdateInstanceStrategy.java
src/main/java/org/folio/service/orders/lines/update/PatchOperationHandler.java
src/main/java/org/folio/service/orders/lines/update/instance/WithHoldingOrderLineUpdateInstanceStrategy.java
src/main/java/org/folio/service/orders/lines/update/instance/WithoutHoldingOrderLineUpdateInstanceStrategy.java
src/test/java/org/folio/ApiTestSuite.java
src/test/java/org/folio/RestTestUtils.java
src/test/java/org/folio/rest/core/RestClientTest.java
src/test/java/org/folio/rest/impl/MockServer.java
src/test/java/org/folio/rest/impl/PurchaseOrderLinesApiTest.java
src/test/java/org/folio/service/inventory/InventoryManagerTest.java
src/test/java/org/folio/service/orders/lines/update/OrderLineUpdateInstanceHandlerTest.java
src/test/java/org/folio/service/orders/lines/update/instance/WithHoldingOrderLineUpdateInstanceStrategyTest.java
src/test/resources/mockdata/patchOrderLines/patch.json

[MODORDERS-684](https://issues.folio.org/browse/MODORDERS-684) …

MODORDERS-684 Implement edit instance connection logic of POL

---

pom.xml
src/main/java/org/folio/config/ApplicationConfig.java
src/main/java/org/folio/service/orders/lines/update/OrderLineUpdateInstanceHandler.java
src/main/java/org/folio/service/orders/lines/update/instance/BaseOrderLineUpdateInstanceStrategy.java
src/main/java/org/folio/service/orders/lines/update/instance/WithHoldingOrderLineUpdateInstanceStrategy.java
src/main/java/org/folio/service/orders/lines/update/instance/WithoutHoldingOrderLineUpdateInstanceStrategy.java
src/test/java/org/folio/ApiTestSuite.java
src/test/java/org/folio/service/orders/lines/update/OrderLineUpdateInstanceHandlerTest.java
src/test/java/org/folio/service/orders/lines/update/instance/WithHoldingOrderLineUpdateInstanceStrategyTest.java
src/test/java/org/folio/service/orders/lines/update/instance/WithoutHoldingOrderLineUpdateInstanceStrategyTest.java

https://issues.folio.org/browse/MODORDERS-685
* Implemented edit instance connection logic of POL - create inventory set to Instance or none …

MODORDERS-685 Implement edit instance connection logic of POL

---

descriptors/ModuleDescriptor-template.json

MODORDERS-684 Update permissions

---

descriptors/ModuleDescriptor-template.json

MODORDERS-684 Added missing permission

---

src/main/java/org/folio/service/orders/lines/update/instance/WithHoldingOrderLineUpdateInstanceStrategy.java

https://issues.folio.org/browse/MODORDERS-716 …

MODORDERS-716 Failing change instance connection from POL when Create inventory is "None"

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/config/ApplicationConfig.java
src/main/java/org/folio/service/finance/transaction/OpenToClosedEncumbranceStrategy.java
src/main/java/org/folio/service/orders/OrderRolloverService.java
src/test/java/org/folio/ApiTestSuite.java
src/test/java/org/folio/service/finance/transaction/OpenToClosedEncumbranceStrategyTest.java
src/test/java/org/folio/service/orders/OrderRolloverServiceTest.java
src/test/resources/mockdata/compositeOrders/a1465131-ed35-4308-872c-d7cdf0afc5f7.json

[MODORDERS-712](https://issues.folio.org/browse/MODORDERS-712) - Encumbrances are created for closed orders during FYRO
[MODORDERS-706](https://issues.folio.org/browse/MODORDERS-706) should be reviewed first.
- Update the order status for encumbrances an order is closed and they are released
- During order rollover, delete encumbrances for a closed order and remove the related links in the po lines
- Updated permissions
- Unrelated fix of permissions
- Updated a unit test and added a new one …

[MODORDERS-712] Fix rollover for closed orders

---

pom.xml

https://issues.folio.org/browse/MODORDERS-710
Update versions in pom.xml
While it's …

MODORDERS-710 - upgrade rmb to version 34

---

src/main/java/org/folio/orders/utils/FundDistributionUtils.java
src/main/java/org/folio/rest/core/exceptions/ErrorCodes.java
src/test/java/org/folio/ApiTestSuite.java
src/test/java/org/folio/orders/utils/FundDistributionUtilsTest.java

[MODORDERS-715](https://issues.folio.org/browse/MODORDERS-715) - Resolve issue with failing test
- Added a specific implementation for the case of a price of 0
- Added a unit test
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to …

[MODORDERS-715] Support fund distributions without the price

---

src/main/java/org/folio/rest/RestConstants.java
src/main/java/org/folio/rest/core/RestClient.java

[MODORDERS-725](https://issues.folio.org/browse/MODORDERS-725) - Temporary workaround for issue with x-okapi-tenant header
Updated RestClient as described in the JIRA. …

[MODORDERS-725] Temporary fix for x-okapi-tenant header

---

src/main/java/org/folio/service/orders/flows/update/reopen/ReOpenCompositeOrderManager.java

[MODORDERS-706](https://issues.folio.org/browse/MODORDERS-706) - Create encumbrances if needed when reopening an order
This is a fix to PR #598.
Do not clone the composite po before processing encumbrances, so that the encumbrance link can be added when an encumbrance is created (as when opening an order).
There is an [updated integration test](https://github.com/folio-org/folio-integration-tests/pull/641).
- Are the JIRAs under …

[MODORDERS-706] Fixed encumbrance link creation when reopening

---

src/main/java/org/folio/service/inventory/InventoryManager.java
src/main/java/org/folio/service/orders/lines/update/instance/WithHoldingOrderLineUpdateInstanceStrategy.java
src/test/java/org/folio/service/inventory/InventoryManagerTest.java
src/test/java/org/folio/service/orders/lines/update/instance/WithHoldingOrderLineUpdateInstanceStrategyTest.java
src/test/resources/mockdata/holdingsRecords/holdingRecords-1.json
src/test/resources/mockdata/holdingsRecords/holdingRecords-old-new.json

All existing items in Holdings (not only items related to POL) are moved with Holdings when editing instance connection from POL …

[MODORDERS-720] - Updating only the required items

---

src/main/java/org/folio/helper/PurchaseOrderHelper.java
src/main/java/org/folio/helper/PurchaseOrderLineHelper.java

The problem was due to an asynchronous code call to check for acq-unit permissionsfor UPDATE operation …

[MODORDERS-728] - Fix periodically failing PurchaseOrderLinesApiTestNested test

---

descriptors/ModuleDescriptor-template.json
ramls/order-lines.raml
src/main/java/org/folio/orders/utils/FundDistributionUtils.java
src/main/java/org/folio/rest/core/exceptions/HttpException.java
src/main/java/org/folio/rest/impl/CompositePoLineAPI.java
src/test/java/org/folio/rest/impl/PurchaseOrderLinesApiTest.java

https://issues.folio.org/browse/MODORDERS-708
Provide new endpoint to validate fund distributions for a PO line that will be called by UI to have consistent validation with BE

[MODORDERS-708]. Provide endpoint to validate fund distributions for a po line

---

src/main/java/org/folio/service/orders/OrderRolloverService.java

https://issues.folio.org/browse/MODORDERS-732
* adjusted searches of fund distributions by fund ids …

MODORDERS-732 adjusted searches of fund distributions by fund ids

---

NEWS.md
descriptors/ModuleDescriptor-template.json
ramls/order-lines.raml
src/main/java/org/folio/config/ApplicationConfig.java
src/main/java/org/folio/helper/PurchaseOrderHelper.java
src/main/java/org/folio/helper/PurchaseOrderLineHelper.java
src/main/java/org/folio/orders/utils/FundDistributionUtils.java
src/main/java/org/folio/rest/core/exceptions/HttpException.java
src/main/java/org/folio/rest/impl/CompositePoLineAPI.java
src/main/java/org/folio/service/finance/transaction/EncumbranceService.java
src/main/java/org/folio/service/inventory/InventoryManager.java
src/main/java/org/folio/service/orders/flows/update/reopen/ReOpenCompositeOrderManager.java
src/main/java/org/folio/service/orders/lines/update/OrderLinePatchOperationService.java
src/main/java/org/folio/service/orders/lines/update/instance/WithHoldingOrderLineUpdateInstanceStrategy.java
src/main/java/org/folio/service/titles/TitlesService.java
src/test/java/org/folio/orders/utils/FundDistributionUtilsTest.java
src/test/java/org/folio/rest/impl/MockServer.java
src/test/java/org/folio/rest/impl/PurchaseOrderLinesApiTest.java
src/test/java/org/folio/rest/impl/PurchaseOrdersApiTest.java
src/test/java/org/folio/rest/impl/protection/LinesProtectionTest.java
src/test/java/org/folio/rest/impl/protection/ReceivingCheckinProtectionTest.java
src/test/java/org/folio/service/inventory/InventoryManagerTest.java
src/test/java/org/folio/service/orders/flows/update/reopen/ReOpenCompositeOrderManagerTest.java
src/test/java/org/folio/service/orders/lines/update/instance/WithHoldingOrderLineUpdateInstanceStrategyTest.java
src/test/resources/mockdata/holdingsRecords/holdingRecords-1.json
src/test/resources/mockdata/holdingsRecords/holdingRecords-old-new.json
src/test/resources/mockdata/instances/instance.json
src/test/resources/mockdata/instances/instances.json

Prepare for 12.4.1 bugfix release, that includes updating readme and cherry-picked commits

Prepare for 12.4.1 bugfix release

---

src/main/java/org/folio/orders/utils/HelperUtils.java
src/main/java/org/folio/service/TagService.java
src/test/java/org/folio/service/finance/FundServiceTest.java

Modorders 735

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/config/ApplicationConfig.java
src/main/java/org/folio/service/orders/lines/update/instance/WithHoldingOrderLineUpdateInstanceStrategy.java
src/test/java/org/folio/service/orders/lines/update/OrderLineUpdateInstanceHandlerTest.java
src/test/java/org/folio/service/orders/lines/update/instance/WithHoldingOrderLineUpdateInstanceStrategyTest.java

Provide to make operations with piece holdings.
Retrieving holdings by poLineId from orders storage piece endpoint and execute holding ids from connected pieces.
[MODORDERS-730](https://issues.folio.org/browse/MODORDERS-730)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing …

[MODORDERS-730] Item not appearing under holdings after instance connection change

---

NEWS.md
descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/config/ApplicationConfig.java
src/main/java/org/folio/orders/utils/HelperUtils.java
src/main/java/org/folio/service/TagService.java
src/main/java/org/folio/service/orders/OrderRolloverService.java
src/main/java/org/folio/service/orders/lines/update/instance/WithHoldingOrderLineUpdateInstanceStrategy.java
src/test/java/org/folio/service/orders/lines/update/OrderLineUpdateInstanceHandlerTest.java
src/test/java/org/folio/service/orders/lines/update/instance/WithHoldingOrderLineUpdateInstanceStrategyTest.java

https://issues.folio.org/browse/MODORDERS-746
Release 2022 R2 Morning Glory Bug Fix 2

[MODORDERS-746] Release 2022 R2 Morning Glory Bug Fix 2

---

src/main/java/org/folio/service/inventory/InventoryManager.java

https://issues.folio.org/browse/MODORDERS-748
Adjusting Instance status, instance type and loan type defaults . …

Modorders 748-Adjusting Instance status, instance type and loan type defaults is ignored buy order creation

---

descriptors/ModuleDescriptor-template.json

mod-inventory-storage (MODINVSTOR-576) has new major interface versions:
instance-storage 9.0
holdings-storage 6.0
item-storage 10.0
mod-orders uses holdings-storage and item-storage APIs, but not instance-storage API.
mod-orders is not affected because the incompatible change is in the DELETE all records APIs only that is not used by mod-orders.
Only the okapiInterfaces need to be bumped in "requires" section of ModuleDescriptor-template.json
- Do JIRAs exist to update the …

MODORDERS-757: Support holdings-storage 6.0, item-storage 10.0

---

NEWS.md
src/main/java/org/folio/service/inventory/InventoryManager.java
src/main/java/org/folio/service/orders/OrderRolloverService.java

Release 2022 R2 Morning Gloxy Bug Fix 12.4.3

[MODORDERS-751] Release 2022 R2 Morning Gloxy Bug Fix 12.4.3

---

src/main/java/org/folio/orders/utils/POLineProtectedFieldsUtil.java

Unprotected lastEDIExportDate field

---

pom.xml

[MODORDERS-776]-upgraded raml

---

src/main/java/org/folio/service/finance/transaction/ClosedToOpenEncumbranceStrategy.java
src/main/java/org/folio/service/finance/transaction/EncumbranceService.java
src/test/java/org/folio/orders/events/handlers/HandlersTestHelper.java

https://issues.folio.org/browse/MODORDERS-779 …

[MODORDERS-779]-updated reopen order logic

---

src/main/java/org/folio/completablefuture/FolioVertxCompletableFuture.java

https://issues.folio.org/browse/FOLIO-3604
* added copyright notice to be merged into Morning Glory release branch …

added copyright notice

---

NEWS.md

[MODORDERS-785] - Module release Morning Glory R2 2022 Hot Fix #1

---

src/main/java/org/folio/orders/utils/ResourcePathResolver.java
src/main/java/org/folio/service/ExportHistoryService.java
src/test/java/org/folio/rest/impl/ExportHistoryImplTest.java
src/test/java/org/folio/rest/impl/MockServer.java

https://issues.folio.org/browse/MODORDERS-783
* fixed endpoint path …

MODORDERS-783 fixed endpoint

---

descriptors/ModuleDescriptor-template.json

Mod-orders could not get the item by id and created an item a second time.
- Added sub permission for retrieve item by id to POST endpoint composite order line
[MODORDERS-790](https://issues.folio.org/browse/MODORDERS-790) …

[MODORDERS-790] Duplicate Holding and Item when ordering something from GOBI

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

[MODORDERS-794](https://issues.folio.org/browse/MODORDERS-794) …

[MODORDERS-794] - module release Nolana R3 Bug Fix 1

---

src/main/java/org/folio/helper/PurchaseOrderLineHelper.java
src/test/java/org/folio/rest/impl/PurchaseOrderLinesApiTest.java
src/test/resources/mockdata/compositeLines/cc189777-fd26-4ae8-b0e5-08abebb50b51.json
src/test/resources/mockdata/itemsRecords/inventoryItemsCollection.json

Inconsistent behavior with PO v. POL cancellation on multi-line orders
While it's …

[MODORDERS-792] - POL cancellation on multi-line orders

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/config/ApplicationConfig.java
src/main/java/org/folio/helper/PurchaseOrderLineHelper.java
src/main/java/org/folio/models/PoLineInvoiceLineHolder.java
src/main/java/org/folio/service/invoice/POLInvoiceLineRelationService.java
src/main/java/org/folio/service/invoice/PoLineInvoiceLineHolderBuilder.java
src/test/java/org/folio/rest/impl/MockServer.java
src/test/java/org/folio/rest/impl/PurchaseOrderLinesApiTest.java

To give an ability to fetch related invoice lines and filter by flow needs specified in the https://miro.com/app/board/uXjVPQunluM=/
- Created holder which contains filtered related invoices
- Created holder builder which filters invoice lines by specified in the flows parameters and sets in the holder
[MODORDERS-788](https://issues.folio.org/browse/MODORDERS-788)
- Do PRs exist for …

[MODORDERS-788] Implement fetching related invoices on PUT PO Line method to be able to implement all futher flows

---

src/main/java/org/folio/helper/PoNumberHelper.java
src/main/java/org/folio/helper/PurchaseOrderHelper.java
src/main/java/org/folio/orders/utils/HelperUtils.java
src/main/java/org/folio/rest/core/exceptions/ErrorCodes.java
src/test/java/org/folio/rest/impl/PurchaseOrdersApiTest.java
src/test/resources/mockdata/compositeOrders/9d56b621-202d-414b-9e7f-5fefe4422ab3.json

[MODORDERS-713]-updated validation for prefix and suffix . 

---

src/main/java/org/folio/helper/PurchaseOrderLineHelper.java
src/test/java/org/folio/rest/impl/PurchaseOrderLinesApiTest.java

[MODORDERS-792] - Fix for order line cancellation

---

NEWS.md
src/main/java/org/folio/helper/PurchaseOrderLineHelper.java
src/test/java/org/folio/rest/impl/PurchaseOrderLinesApiTest.java

[MODORDERS-806] - Release 12.5.3

---

src/main/java/org/folio/service/invoice/PoLineInvoiceLineHolderBuilder.java
src/test/java/org/folio/rest/impl/PurchaseOrderLinesApiTest.java

https://issues.folio.org/browse/FAT-3525
https://issues.folio.org/browse/FAT-3526
https://issues.folio.org/browse/FAT-3538
https://issues.folio.org/browse/FAT-3537
https://issues.folio.org/browse/MODORDERS-788 …

[FAT-3525] For fixing FAT-3525, FAT-3526, FAT- 3538, FAT-3537

---

src/main/java/org/folio/helper/PurchaseOrderLineHelper.java
src/test/java/org/folio/rest/impl/PurchaseOrderLinesApiTest.java

https://issues.folio.org/browse/MODORDERS-804
We have disabled encumberence update while changing the fundDistribution for paid invoices connected to the order …

[MODORDERS-804]-updated encumberance update validation.

---

src/main/java/org/folio/rest/core/exceptions/ErrorCodes.java
src/main/java/org/folio/service/invoice/PoLineInvoiceLineHolderBuilder.java
src/test/java/org/folio/rest/impl/PurchaseOrderLinesApiTest.java

Provide error code for flow 3
While it's helpful for reviewers to help identify …

[MODORDERS-803] - Provided error code for flow #3

---

NEWS.md
src/main/java/org/folio/orders/utils/POLineProtectedFieldsUtil.java

[MODORDERS-812](https://issues.folio.org/browse/MODORDERS-812) …

[MODORDERS-812] - Release 12.4.5

---

src/main/java/org/folio/orders/utils/PoLineCommonUtil.java
src/test/java/org/folio/orders/utils/PoLineCommonUtilTest.java

Invoice is unable to approve due to protected fields on productIds …

[MODORDERS-810] - Invoice is unable to approve due to protected fields on productIds

---

descriptors/ModuleDescriptor-template.json

Permissions added
While it's helpful for reviewers to help identify potential problems, …

[MODORDERS-816] - A user with order create permission can not add suffix and prefix to the order

---

src/main/java/org/folio/config/ApplicationConfig.java
src/main/java/org/folio/helper/PurchaseOrderLineHelper.java
src/main/java/org/folio/models/PoLineInvoiceLineHolder.java
src/main/java/org/folio/service/finance/transaction/PendingToOpenEncumbranceStrategy.java
src/main/java/org/folio/service/invoice/POLInvoiceLineRelationService.java
src/main/java/org/folio/service/invoice/PoLineInvoiceLineHolderBuilder.java
src/test/java/org/folio/rest/impl/MockServer.java
src/test/java/org/folio/rest/impl/PurchaseOrderLinesApiTest.java

- Catch invoice related errors after encumbrances will be processed
- Fix NPE bugs
[MODORDERS-800](https://issues.folio.org/browse/MODORDERS-800) …

[MODORDERS-800] - Implement moving encumbered value from budget 1 to budget 2 (FLOW #2)

---

src/main/java/org/folio/service/inventory/InventoryManager.java
src/test/java/org/folio/rest/impl/PurchaseOrdersApiTest.java
src/test/java/org/folio/service/inventory/InventoryManagerTest.java

New holding is being created with the barcode instead of the barcode being attached to the existing holding
Added finding holdingId before creating new
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as …

[MODORDERS-647] - Added finding holdingId before creating new

---

PULL_REQUEST_TEMPLATE.md
src/main/resources/log4j2-json.properties

https://issues.folio.org/browse/MODORDERS-784
The property file and all logging commands have been adjusted. …

[MODORDERS-784] - Logging Improvement - Configuration

---

src/test/java/org/folio/rest/impl/PurchaseOrdersApiTest.java

To have an opportunity to work with the field "isAcknowledged" in the "Details"-object.
Dependency on the acq-models updated. …

MODORDSTOR-328: dependency on acq-models updated.

---

src/main/java/org/folio/helper/CheckinHelper.java
src/main/java/org/folio/helper/ReceivingHelper.java
src/main/java/org/folio/service/inventory/InventoryManager.java
src/main/java/org/folio/service/pieces/flows/update/PieceUpdateFlowInventoryManager.java

Copy number does not get applied to item when creating item through receiving app …

[MODORDERS-807] - Added copyNumber field updates

---

pom.xml
src/main/java/org/folio/config/ApplicationConfig.java
src/main/java/org/folio/helper/PoNumberHelper.java
src/main/java/org/folio/helper/PurchaseOrderHelper.java
src/main/java/org/folio/helper/PurchaseOrderLineHelper.java
src/main/java/org/folio/rest/RestConstants.java
src/main/java/org/folio/rest/impl/OrdersApi.java
src/main/java/org/folio/service/finance/transaction/EncumbranceService.java
src/main/java/org/folio/service/finance/transaction/PendingToOpenEncumbranceStrategy.java
src/main/java/org/folio/service/inventory/InventoryManager.java
src/main/java/org/folio/service/inventory/InventoryService.java
src/main/java/org/folio/service/orders/OrderLinesSummaryPopulateService.java
src/main/java/org/folio/service/orders/PurchaseOrderLineService.java
src/main/java/org/folio/service/orders/flows/update/open/OpenCompositeOrderFlowValidator.java
src/main/java/org/folio/service/orders/flows/update/open/OpenCompositeOrderInventoryService.java
src/main/java/org/folio/service/pieces/PieceStorageService.java
src/test/java/org/folio/service/orders/lines/update/OrderLineUpdateInstanceHandlerTest.java

https://issues.folio.org/browse/MODORDERS-789
* switched sequential Future processing to parallel with semaphores …

MODORDERS-789 introduced vertx semaphores

---

src/main/java/org/folio/helper/CheckinHelper.java
src/main/java/org/folio/helper/ReceivingHelper.java
src/test/java/org/folio/helper/CheckinHelperTest.java

[MODORDERS-807] - Updating copyNumber in checkIn

---

src/main/java/org/folio/config/ApplicationConfig.java
src/main/java/org/folio/helper/CheckinReceivePiecesHelper.java
src/main/java/org/folio/helper/PurchaseOrderHelper.java
src/main/java/org/folio/rest/RestConstants.java
src/main/java/org/folio/service/finance/FundService.java
src/main/java/org/folio/service/finance/LedgerService.java
src/main/java/org/folio/service/finance/budget/BudgetService.java
src/main/java/org/folio/service/finance/transaction/TransactionService.java
src/main/java/org/folio/service/inventory/InventoryManager.java
src/main/java/org/folio/service/invoice/InvoiceLineService.java
src/main/java/org/folio/service/invoice/InvoiceService.java
src/main/java/org/folio/service/orders/OrderRolloverService.java
src/main/java/org/folio/service/orders/PurchaseOrderLineService.java
src/main/java/org/folio/service/orders/PurchaseOrderStorageService.java
src/main/java/org/folio/service/pieces/PieceStorageService.java
src/main/java/org/folio/service/titles/TitlesService.java
src/test/java/org/folio/rest/impl/CheckinReceivingApiTest.java
src/test/java/org/folio/service/PrefixServiceTest.java
src/test/java/org/folio/service/finance/FundServiceTest.java
src/test/java/org/folio/service/orders/OrderReEncumberServiceTest.java
src/test/java/org/folio/service/orders/OrderRolloverServiceTest.java

https://issues.folio.org/browse/MODORDERS-473
* Fixed processing order lines by small chunks. Do not load all orders into memory anymore
* Removed the step of retreiving orders
to avoid breaking the folio-testing …

MODORDERS-473 - rollover memory leak

---

src/main/java/org/folio/helper/PurchaseOrderLineHelper.java
src/main/java/org/folio/service/invoice/InvoiceLineService.java
src/main/java/org/folio/service/invoice/POLInvoiceLineRelationService.java

To provide ability to edit fund distribution of POL without any corruptions from linked invoices side which has opened or reviewed.
- Triggered when fund distribution of POL was updated
- Replace fund distribution of linked invoice lines which have Open or Reviewed status
[MODORDERS-801](https://issues.folio.org/browse/MODORDERS-801)
- Did you modify code …

[MODORDERS-801] Check and correct encumbrance ID links for invoices with Open or Reviewed status (FLOW #4)

---

src/main/java/org/folio/config/ApplicationConfig.java
src/main/java/org/folio/helper/PurchaseOrderHelper.java
src/main/java/org/folio/helper/PurchaseOrderLineHelper.java
src/test/java/org/folio/helper/PurchaseOrderHelperTest.java
src/test/java/org/folio/rest/impl/PurchaseOrdersApiTest.java

https://issues.folio.org/browse/MODORDERS-827 …

[MODORDERS-827]-updated getting purchaseOrders logic.

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml
src/main/java/org/folio/helper/PurchaseOrderLineHelper.java
src/main/java/org/folio/orders/utils/HelperUtils.java
src/main/java/org/folio/rest/impl/CompositePoLineAPI.java
src/main/java/org/folio/rest/impl/InitAPIs.java
src/main/java/org/folio/service/dataimport/OrderWriterFactory.java
src/main/java/org/folio/service/dataimport/handlers/CreateOrderEventHandler.java
src/main/java/org/folio/verticle/DataImportConsumerVerticle.java
src/main/java/org/folio/verticle/consumers/DataImportKafkaHandler.java
src/test/java/org/folio/ApiTestSuite.java
src/test/java/org/folio/DataImportTestSuite.java
src/test/java/org/folio/TestConfig.java
src/test/java/org/folio/di/DiAbstractRestTest.java
src/test/java/org/folio/rest/impl/MockServer.java
src/test/java/org/folio/service/dataimport/handlers/CreateOrderEventHandlerTest.java

to create order and order line from incoming MARC-BIB record
* implement [EventHandler](https://github.com/folio-org/data-import-processing-core/blob/master/src/main/java/org/folio/processing/events/services/handler/EventHandler.java) to handle received event and create a new order and related order line from incoming MARC record
* add logic for 'activationDue' calculation
* add logic for po lines limit overriding
* override 'createInventory' po line field depending on actions in a job profile
* add tests
[MODORDERS-773](https://issues.folio.org/browse/MODORDERS-773)

MODORDERS-773 - Implement action profile handler for order creation

---

src/main/java/org/folio/config/ApplicationConfig.java
src/main/java/org/folio/service/inventory/InventoryManager.java
src/main/java/org/folio/service/orders/flows/update/open/OpenCompositeOrderInventoryService.java
src/main/java/org/folio/service/pieces/flows/strategies/ProcessInventoryElectronicStrategy.java
src/main/java/org/folio/service/pieces/flows/strategies/ProcessInventoryMixedStrategy.java
src/main/java/org/folio/service/pieces/flows/strategies/ProcessInventoryPhysicalStrategy.java
src/main/java/org/folio/service/pieces/flows/strategies/ProcessInventoryStrategy.java
src/test/java/org/folio/service/inventory/InventoryManagerTest.java
src/test/java/org/folio/service/orders/flows/update/open/OpenCompositeOrderInventoryServiceTest.java
src/test/resources/mockdata/compositeLines/2c4c29fd-fb8a-4c70-8561-931690bae8a4.json

Implement "Create new holdings for location" …

[MODORDERS-821] - Logic updated for find or create holdings for location

---

descriptors/ModuleDescriptor-template.json

Align the module with API breaking change …

[MODORDERS-825] - Inventory API increase to version 13.0

---

src/main/java/org/folio/service/dataimport/handlers/CreateOrderEventHandler.java
src/test/java/org/folio/service/dataimport/handlers/CreateOrderEventHandlerTest.java

Extend CreateOrderEventHandler to clear "ordedId" from POLine-entity (which will be sent in the DI_ERROR payload) if there is an error.
Clear orderId while error handling and covered with tests

[MODORDERS-840] Clear orderId in poLine while error handling

---

descriptors/ModuleDescriptor-template.json

With permission sets below user will be able to delete item but gets error message regarding with missed permission.
- Finance: View fund and budget
- Inventory: View instances, holdings, and items
- Orders: Can view Orders and Order lines
- Receiving: View, edit, delete
- Added missed permission …

[MODFISTO-368] - Added missed permission for DELETE piece by id endpoint

---

NEWS.md
pom.xml
src/main/java/org/folio/service/caches/MappingParametersCache.java
src/test/java/org/folio/di/CacheTest.java

Add cache to store organisations info for mapping params
Added cache for storing mapping params with organizations, storing cache by tenantId

[MODORDERS-844] Add cache to store organisations info for mapping params

---

pom.xml
src/main/java/org/folio/service/dataimport/handlers/CreateOrderEventHandler.java
src/test/java/org/folio/rest/impl/MockServer.java
src/test/java/org/folio/service/dataimport/handlers/CreateOrderEventHandlerTest.java

Allow for mapping the vendor, material supplier, and access provider based on CODE in MARC record
Retrieve MappingParameters from cache on mapping orders, covered with tests
Jira: https://issues.folio.org/browse/MODDICORE-303

[MODDICORE-303] Allow for mapping the vendor, material supplier, and access provider based on CODE in MARC record

---

pom.xml

Update mod-di-converter-storage-client and data-import-processing-core dependencies
Updated dependencies

[MODDICORE-306] Update mod-di-converter-storage-client and data-import-processing-core dependencies

---

NEWS.md
pom.xml

[MODORDERS-845] - Release v12.6.0

---

src/main/java/org/folio/service/finance/transaction/EncumbranceService.java
src/main/java/org/folio/service/orders/OrderRolloverService.java
src/main/java/org/folio/service/orders/PurchaseOrderLineService.java
src/main/java/org/folio/service/orders/flows/update/open/OpenCompositeOrderInventoryService.java

https://issues.folio.org/browse/MODORDERS-855
* fixed vertx semaphores …

MODORDERS-855 fixed vertx semaphores

---

pom.xml

upgrade di-utils to v1.11.0 containing updated dependencies to prevent possible vulnerabilities

MODDATAIMP-786 - Upgrade di-utils to v1.11.0

---

descriptors/ModuleDescriptor-template.json

[MODORDERS-859](https://issues.folio.org/browse/MODORDERS-859) - Encumbrances are not always released when an order is closed
Added missing permissions for `/orders/receive` and `/orders/check-in`.
to avoid breaking the …

[MODORDERS-859-2] Receiving: added permission for transaction summaries

---

descriptors/ModuleDescriptor-template.json
pom.xml

[FAT-4844]-updated permissions

---

descriptors/ModuleDescriptor-template.json

[FAT-4999](https://issues.folio.org/browse/FAT-4999) - Karate test fail: receive-20-pieces.feature
- Added missing permission for check-in: `inventory-storage.loan-types.collection.get`.
- Checked it is probably not needed elsewhere.
Ideally, all the PRs involved in breaking changes would be merged …

[FAT-4999] Added missing permission for check-in

---

src/main/java/org/folio/service/orders/OrderRolloverService.java

https://issues.folio.org/browse/FAT-4863
* fixed orders chunk counting …

FAT-4863 fixed orders chunk counting

---

src/main/java/org/folio/rest/core/RestClient.java
src/main/java/org/folio/rest/impl/BaseApi.java

* empty logs when error occurs
* fixed error logging …

fixed logger error message

---

src/main/java/org/folio/service/orders/flows/update/unopen/UnOpenCompositeOrderManager.java

Fix order unopen when there are items in holding

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/orders/utils/ResourcePathResolver.java
src/main/java/org/folio/service/finance/rollover/LedgerRolloverErrorService.java
src/test/java/org/folio/service/finance/rollover/LedgerRolloverErrorServiceTest.java

https://issues.folio.org/browse/MODORDERS-865
* added missed permission
* fixed endpoint for error flow
especially …

MODORDERS-865 added missed permission

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/orders/utils/ResourcePathResolver.java
src/main/java/org/folio/service/finance/rollover/LedgerRolloverErrorService.java
src/test/java/org/folio/service/finance/rollover/LedgerRolloverErrorServiceTest.java

https://issues.folio.org/browse/MODORDERS-865
* fixed permissions and request routing …

Modorders 865 fixed permissions and request routing

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml
src/main/java/org/folio/config/ApplicationConfig.java
src/main/java/org/folio/orders/utils/ResourcePathResolver.java
src/main/java/org/folio/service/finance/rollover/LedgerRolloverErrorService.java
src/main/java/org/folio/service/finance/rollover/LedgerRolloverProgressService.java
src/main/java/org/folio/service/finance/rollover/LedgerRolloverService.java
src/main/java/org/folio/service/orders/OrderReEncumberService.java
src/main/java/org/folio/service/orders/OrderRolloverService.java
src/main/java/org/folio/service/orders/ReEncumbranceHoldersBuilder.java
src/test/java/org/folio/ApiTestSuite.java
src/test/java/org/folio/service/finance/rollover/LedgerRolloverErrorServiceTest.java
src/test/java/org/folio/service/finance/rollover/LedgerRolloverProgressServiceTest.java
src/test/java/org/folio/service/finance/rollover/LedgerRolloverServiceTest.java
src/test/java/org/folio/service/orders/OrderReEncumberServiceTest.java
src/test/java/org/folio/service/orders/OrderRolloverServiceTest.java
src/test/java/org/folio/service/orders/ReEncumbranceHoldersBuilderTest.java

[MODORDERS-873] - Release v12.6.4

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/orders/utils/ResourcePathResolver.java
src/main/java/org/folio/service/finance/rollover/LedgerRolloverErrorService.java
src/test/java/org/folio/service/finance/rollover/LedgerRolloverErrorServiceTest.java

[MODFIN-316](https://issues.folio.org/browse/MODFIN-316) - Provide proxy endpoints to add and delete ledger rollover error in the business layer
- Replaced the endpoints with the finance ones
- Fixed permissions
- Updated tests
See related [PR](https://github.com/folio-org/mod-finance/pull/204) in mod-finance.
- Did you modify code to call some additional …

[MODFIN-316] Using new proxy endpoints for ledger rollover errors

---

src/main/java/org/folio/helper/PurchaseOrderHelper.java
src/test/java/org/folio/service/dataimport/handlers/CreateOrderEventHandlerTest.java

Add prefix and suffix for poNumber in result of DI
Adjust prefix and suffix for generated poNumber in orders logic
Jira: https://issues.folio.org/browse/MODORDERS-878

[MODORDERS-878] Adjust prefix and suffix for generated poNumber

---

src/main/java/org/folio/service/pieces/flows/strategies/ProcessInventoryMixedStrategy.java
src/main/java/org/folio/service/pieces/flows/strategies/ProcessInventoryStrategy.java
src/test/java/org/folio/rest/impl/PurchaseOrdersApiTest.java

Prevent redundant holdings record creation during import open P/E mix order
especially as the number of inter-module …

[MODORDERS-871] - Finding holdings record during import open P/E mix orderLine

---

src/main/java/org/folio/rest/core/RestClient.java
src/main/java/org/folio/rest/core/exceptions/ExceptionUtil.java
src/test/java/org/folio/service/dataimport/handlers/CreateOrderEventHandlerTest.java

[MODFISTO-405] - error response processing

---

src/main/java/org/folio/service/orders/OrderRolloverService.java

[MODORDERS-869](https://issues.folio.org/browse/MODORDERS-869) - Optimize rollover lookup for po lines
Used optimized query for fundId in po line fundDistribution, using the index added in mod-orders-storage.
This PR should be reviewed and merged at the same time as [the one in mod-orders-storage](https://github.com/folio-org/mod-orders-storage/pull/341). …

[MODORDERS-869] Using optimized fund distribution query

---

descriptors/ModuleDescriptor-template.json
src/test/resources/mockdata/itemRequests/itemRequests.json

Changing to be in line with changes in CIRC-253

MODORDERS-887: changing interface version

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/config/ApplicationConfig.java
src/main/java/org/folio/rest/core/exceptions/ErrorCodes.java
src/main/java/org/folio/service/orders/PurchaseOrderLineService.java
src/main/java/org/folio/service/orders/lines/update/OrderLinePatchOperationService.java
src/main/java/org/folio/service/orders/utils/HelperUtils.java
src/main/java/org/folio/service/orders/utils/ProductIdUtils.java
src/test/java/org/folio/service/orders/lines/update/OrderLineUpdateInstanceHandlerTest.java

When using POL "Change instance" the product ID can be made invalid blocking Invoice approve and pay
especially as …

[MODORDERS-890] - Normalize the product ID when "Changing instance"

---

src/main/java/org/folio/service/inventory/InventoryManager.java
src/main/java/org/folio/service/orders/flows/update/unopen/UnOpenCompositeOrderManager.java
src/test/java/org/folio/helper/InventoryInteractionTestHelper.java
src/test/java/org/folio/rest/impl/PurchaseOrdersApiTest.java

https://issues.folio.org/browse/MODORDERS-902 …

[MODORDERS-902]-updated InventoryManager

---

pom.xml
src/main/java/org/folio/config/ApplicationConfig.java
src/main/java/org/folio/models/PoLineInvoiceLineHolder.java
src/main/java/org/folio/service/invoice/POLInvoiceLineRelationService.java
src/main/java/org/folio/service/invoice/PoLineInvoiceLineHolderBuilder.java

This code is not used and causes issue described in MODFIN-323 so can be deleted

MODFIN-323. Delete unnecessary code

---

src/main/java/org/folio/rest/core/exceptions/ErrorCodes.java
src/main/java/org/folio/service/ProtectionService.java
src/test/java/org/folio/rest/impl/protection/LinesProtectionTest.java
src/test/java/org/folio/rest/impl/protection/OrdersProtectionTest.java
src/test/java/org/folio/rest/impl/protection/PiecesProtectionTest.java

Resolves: [MODORDERS-882](https://issues.folio.org/browse/MODORDERS-882) Update the error message displayed when importer is not a member of the specified acq unit …

[MODORDERS-882] - Update the error message displayed when importer is not a member of the specified acq unit

---

descriptors/ModuleDescriptor-template.json

Due to change a link for fetching ledgers from bussines to storage module dozhens karate were failed.
- Updated module descriptor
[MODORDERS-914](https://issues.folio.org/browse/MODORDERS-914)
to avoid breaking the …

[MODORDERS-914] - User cannot open order when ledger has separate acquisition unit

---

src/main/java/org/folio/service/orders/OrderRolloverService.java

https://issues.folio.org/browse/MODORDERS-904
* fixed po_line filter. regression …

MODORDERS-904 fixed po_line filter

---

NEWS.md
src/main/java/org/folio/service/caches/MappingParametersCache.java
src/test/java/org/folio/di/CacheTest.java

To be able to obtain large amount of organizations by REST (up to 100K ).
Organizations are got by REST with pagination. For now config is 20 requests with 5000 organizations in one chunk (should be tested and confirmed on PTF NLA env).
[MODORDERS-908](https://issues.folio.org/browse/MODORDERS-908) 
Tested locally via vagrant that pagination is working as expected:
Measured cache with 100K organizations (roughly it takes about **27MiB**):
Idle cache state:
Loaded cache:
- Do …

MODORDERS-908: Obtain Organizations with pagination

---

src/main/java/org/folio/service/caches/MappingParametersCache.java

To be able to observe and trace received amount of organizations from mod-organizations …

MODORDERS-908: expand logs with amount of organizations

---

src/main/java/org/folio/config/ApplicationConfig.java
src/main/java/org/folio/dao/FailedLedgerRolloverPoLineDao.java
src/main/java/org/folio/dao/FailedLedgerRolloverPoLineDaoImpl.java
src/main/java/org/folio/dao/PoLinesImportProgressDaoImpl.java
src/main/java/org/folio/dao/RecordIdStorageDaoImpl.java
src/main/java/org/folio/dao/SequentialOrderIdStorageDaoImpl.java
src/main/java/org/folio/dao/util/DbUtils.java
src/main/java/org/folio/models/FailedLedgerRolloverPoLineDto.java
src/main/java/org/folio/rest/core/exceptions/ErrorCodes.java
src/main/java/org/folio/service/orders/OrderRolloverService.java
src/main/java/org/folio/service/orders/PurchaseOrderLineService.java
src/main/resources/templates/db_scripts/create_failed_ledger_rollover_po_line_table.sql
src/main/resources/templates/db_scripts/schema.json
src/test/java/org/folio/service/orders/OrderRolloverServiceTest.java

* https://issues.folio.org/browse/MODORDERS-905
* Continue processing polines after any poline failure
* store failures into database
Communication is paramount if that …

MODORDERS-905 persist rollover failures per poLine

---

src/main/java/org/folio/helper/PurchaseOrderLineHelper.java
src/main/java/org/folio/service/caches/InventoryCache.java
src/main/java/org/folio/service/inventory/InventoryService.java
src/main/java/org/folio/service/orders/PurchaseOrderLineService.java
src/main/java/org/folio/service/orders/lines/update/OrderLinePatchOperationService.java
src/main/java/org/folio/service/orders/utils/ProductIdUtils.java
src/test/java/org/folio/rest/impl/PurchaseOrderLinesApiTest.java

If no affected protected fields are involved during a PUT operation, perform normalization, remove qualifiers, or change the type to "Invalid ISBN" based on the specific case.
- Move the ISBN validation step after the check for protected fields.
- Implement logic for normalization or update type to Invalid ISBN
[MODORDERS-927](https://issues.folio.org/browse/MODORDERS-927)
- Do PRs exist …

[MODORDERS-927] - Implement interception and update of invalid ISBNs during the POL update process

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/service/orders/OrderRolloverService.java
src/main/java/org/folio/service/orders/PurchaseOrderLineService.java
src/test/java/org/folio/service/orders/OrderRolloverServiceTest.java
src/test/java/org/folio/service/orders/PurchaseOrderLineServiceTest.java

Was decided to switch a new batch endpoint for update POL.
[MODORDERS-907](https://issues.folio.org/browse/MODORDERS-907) …

[MODORDERS-907] - Use new orders-storage endpoint to update order lines in batch during rollover

---

descriptors/ModuleDescriptor-template.json

https://issues.folio.org/browse/MODORDERS-928
Adding corresponding module permission …

[MODORDERS-928] - Can not delete acquisition methods with Order settings "All" permission

---

descriptors/ModuleDescriptor-template.json
pom.xml
src/main/java/org/folio/config/ApplicationConfig.java
src/main/java/org/folio/helper/PurchaseOrderLineHelper.java
src/main/java/org/folio/models/consortium/ConsortiumConfiguration.java
src/main/java/org/folio/models/consortium/SharingInstance.java
src/main/java/org/folio/models/consortium/SharingStatus.java
src/main/java/org/folio/orders/utils/ResourcePathResolver.java
src/main/java/org/folio/rest/core/exceptions/ConsortiumException.java
src/main/java/org/folio/service/consortium/ConsortiumConfigurationService.java
src/main/java/org/folio/service/consortium/SharingInstanceService.java
src/main/java/org/folio/service/inventory/InventoryManager.java
src/main/java/org/folio/service/orders/lines/update/OrderLinePatchOperationService.java
src/main/java/org/folio/service/titles/TitlesService.java
src/test/java/org/folio/ApiTestSuite.java
src/test/java/org/folio/rest/impl/MockServer.java
src/test/java/org/folio/service/consortium/SharingInstanceServiceTest.java
src/test/java/org/folio/service/inventory/InventoryManagerTest.java
src/test/java/org/folio/service/orders/lines/update/OrderLineUpdateInstanceHandlerTest.java

[MODORDERS-929] - Local shadow instance creation for linked instances

---

NEWS.md
pom.xml

https://issues.folio.org/browse/MODORDERS-939 …

[MODORDERS-939] - Release v12.7.0

---

src/main/java/org/folio/service/invoice/POLInvoiceLineRelationService.java

It was observed that the encumbrance status was incorrect after changing fund distributions in the Open status of a POL
- Iterate through connected invoice lines to know 'releaseEncumbrance' flag state
- Let to set 'Released' status only in case when releaseEncumbrance is true
[MODORDERS-943](https://issues.folio.org/browse/MODORDERS-943)
- Did you modify …

[MODORDERS-943] - Encumbrance status becomes "Unreleased" after changing fund distribution

---

NEWS.md
pom.xml
src/main/java/org/folio/service/invoice/POLInvoiceLineRelationService.java

[MODORDERS-949](https://issues.folio.org/browse/MODORDERS-949) …

[MODORDERS-949] - Release v12.7.1

---

pom.xml

The import of file is completed with errors for orders creation
Update data-import-processing-core version to 4.2.0-SNAPSHOT

[MODDICORE-373] Update data-import-processing-core version to 4.2.0-SNAPSHOT

---

pom.xml

https://issues.folio.org/browse/MODORDERS-937

MODORDERS-937. Update RMB and vertx to the latest version

---

descriptors/ModuleDescriptor-template.json

https://issues.folio.org/browse/MODORDERS-669
Tested on ranacher in this way:
- Create and open order by admin user
- Create new user with permission sets: Orders: Can view Orders and Order lines and Receiving: View, edit, delete
- Go to receving and delete piece by new user

MODORDERS-669. Cannot delete a piece in receiving

---

src/main/java/org/folio/service/pieces/flows/update/PieceUpdateFlowManager.java
src/test/java/org/folio/rest/impl/PieceApiTest.java
src/test/java/org/folio/service/pieces/flows/update/PieceUpdateFlowManagerTest.java

For piece batch job needs we should identify piece status change date.
[MODORDSTOR-356](https://issues.folio.org/browse/MODORDSTOR-356)
Communication is paramount if that …

[MODORDSTOR-356] - Initial setup of claiming batch job

---

src/main/java/org/folio/config/ApplicationConfig.java
src/main/java/org/folio/rest/core/exceptions/ErrorCodes.java
src/main/java/org/folio/service/titles/TitlesService.java

[MODORDSTOR-360](https://issues.folio.org/browse/MODORDSTOR-360) - Inherit acqUnitIds from Purchase Order when creating new Title
Communication is paramount if that is to …

[MODORDSTOR-360] - Title populating removed

---

pom.xml
src/test/java/org/folio/rest/impl/PieceApiTest.java
src/test/java/org/folio/rest/impl/TitlesApiTest.java
src/test/resources/mockdata/titles/package_title.json

https://issues.folio.org/browse/MODORDERS-852
Configured JunitProvider to able to run junit4 and junit5 tests
```
<plugin>
<groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-surefire-plugin</artifactId>
<version>${maven-surefire-plugin.version}</version>
<configuration>
<argLine>@{argLine} -Xmx1024m -Duser.language=en -Duser.region=US</argLine>
<excludes>
<exclude>org/folio/rest/impl/**Test.class</exclude>
</excludes>
<includes>
<include>org/folio/ApiTestSuite.java</include>
<include>org/folio/DataImportTestSuite.java</include>
</includes>
</configuration>
<dependencies>
<dependency>
<groupId>org.apache.maven.surefire</groupId>
<artifactId>surefire-junit-platform</artifactId>
<version>${maven-surefire-plugin.version}</version>
</dependency>
</dependencies>
</plugin>
```
Before …

[MODORDERS - 852] - Configured JUnitPlatformProvider to run ApiTestSuite and DataImportTestSuite

---

src/main/java/org/folio/helper/CheckinHelper.java
src/main/java/org/folio/helper/CheckinReceivePiecesHelper.java
src/main/java/org/folio/helper/ReceivingHelper.java
src/main/java/org/folio/orders/events/handlers/ReceiptStatusConsistency.java
src/test/java/org/folio/rest/impl/CheckinReceivingApiTest.java

https://issues.folio.org/browse/MODORDERS-967
D not modify PO lines with receipt status ONGOING
especially as the …

[MODORDERS-967] Defect in Order Receipt Status Update for 'Ongoing' Orders

---

src/main/java/org/folio/service/orders/flows/update/open/OpenCompositeOrderFlowValidator.java
src/test/java/org/folio/service/orders/flows/update/open/OpenCompositeOrderFlowValidatorTest.java

https://issues.folio.org/browse/MODORDERS-969 …

[MODORDERS-969] - Opening and editing POs with location-restricted funds

---

src/main/java/org/folio/service/orders/lines/update/instance/WithHoldingOrderLineUpdateInstanceStrategy.java

[MODORDERS-980](https://issues.folio.org/browse/MODORDERS-980) - Update dto schema with recent changes for holdingsItems …

[MODORDERS-980] - Update dto schema with recent changes for holdings

---

descriptors/ModuleDescriptor-template.json

[MODORDERS-980] - Added permission

---

pom.xml

https://issues.folio.org/browse/MODORDERS-985 …

[MODORDERS-985] - Add internal note and external note in Piece schema

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/config/ApplicationConfig.java
src/main/java/org/folio/helper/PurchaseOrderHelper.java
src/main/java/org/folio/orders/utils/AcqDesiredPermissions.java
src/main/java/org/folio/orders/utils/PermissionsUtil.java
src/main/java/org/folio/rest/impl/TitlesApi.java
src/main/java/org/folio/service/ProtectionService.java
src/main/java/org/folio/service/dataimport/handlers/CreateOrderEventHandler.java
src/main/java/org/folio/service/titles/TitlesService.java
src/test/java/org/folio/rest/impl/PurchaseOrdersApiTest.java
src/test/java/org/folio/rest/impl/TitlesApiTest.java

[MODORDERS-972](https://issues.folio.org/browse/MODORDERS-972) - Protect Title acq units management with permissions …

[MODORDERS-972] - Protect Title acq units management with permissions

---

src/main/java/org/folio/service/pieces/flows/update/PieceUpdateFlowManager.java

[MODORDERS-984](https://issues.folio.org/browse/MODORDERS-984) - Receipt status remains "Fully received" after unreceiving piece
Update the po line receipt status after updating the piece.
[Integration test PR](https://github.com/folio-org/folio-integration-tests/pull/1176)
Ideally, all the PRs …

[MODORDERS-984] Update po line receipt status after updating the piece

---

descriptors/ModuleDescriptor-template.json

Add missed module permissions for https://issues.folio.org/browse/UIREC-292

UIREC-292. Add missed module permission

---

src/main/java/org/folio/rest/core/exceptions/ErrorCodes.java
src/main/java/org/folio/rest/impl/OrderTemplatesAPI.java
src/test/java/org/folio/TestConstants.java
src/test/java/org/folio/rest/impl/MockServer.java
src/test/java/org/folio/rest/impl/OrderTemplateTest.java

[MODORDERS-886](https://issues.folio.org/browse/MODORDERS-886) - The unclear error message is displayed when a user is trying to save the order template with already existing name
to avoid breaking the folio-testing …

[MODORDERS-886] - Updated Error for templateName

---

src/main/java/org/folio/helper/CheckinReceivePiecesHelper.java
src/main/java/org/folio/orders/events/handlers/ReceiptStatusConsistency.java
src/test/java/org/folio/rest/impl/CheckinReceivingApiTest.java
src/test/resources/mockdata/lines/1196fcd9-7607-447d-ae85-6e91883d7e4f.json
src/test/resources/mockdata/lines/po_line_collection.json
src/test/resources/mockdata/pieces/pieceRecords-06a95f03-eb00-4248-9f2e-2bd05957ff05.json
src/test/resources/mockdata/pieces/pieceRecordsCollection.json
src/test/resources/mockdata/receiving/receive-physical-cancelled.json

https://issues.folio.org/browse/MODORDERS-983
Added check for PO receipt status = CANCELLED to not modify it in this case. …

[MODORDERS-983] - Receiving a piece on a closed/cancelled PO will reopen the PO

---

src/test/java/org/folio/ApiTestSuite.java
src/test/java/org/folio/service/TagServiceTest.java
src/test/java/org/folio/service/finance/FiscalYearServiceTest.java
src/test/java/org/folio/service/finance/transaction/ClosedToOpenEncumbranceStrategyTest.java
src/test/java/org/folio/service/finance/transaction/TransactionSummariesServiceTest.java

TransactionSummariesServiceTest is fixed
TagServiceTest Broken Function Committed
FiscalYearServiceTest Broken Function Committed
Communication is paramount if that is to …

MODORDERS-852-Some unit tests are not executed 

---

src/main/java/org/folio/service/orders/lines/update/OrderLinePatchOperationService.java
src/test/java/org/folio/TestConstants.java
src/test/java/org/folio/rest/impl/PurchaseOrderLinesApiTest.java
src/test/resources/mockdata/lines/13c4c3c2-90d9-4090-8694-edae7e79e7ac.json

After importing orders, orders are created without details and when deserialized they store null. Accordingly, we have NPE.
- Empty initialization of details if it is null when changing instance connection 
[MODORDERS-986](https://issues.folio.org/browse/MODORDERS-986)
Ideally, all the PRs involved …

[MODORDERS-986] - Error thrown during change instance connection

---

src/main/java/org/folio/helper/CheckinHelper.java
src/main/java/org/folio/helper/ReceivingHelper.java
src/main/java/org/folio/service/inventory/InventoryManager.java
src/test/java/org/folio/rest/impl/CheckinReceivingApiTest.java
src/test/java/org/folio/service/inventory/InventoryManagerTest.java
src/test/resources/mockdata/checkIn/checkin-pe-mix-2-electronic-resources.json
src/test/resources/mockdata/checkIn/checkin-pe-mix-2-physical-resources.json

https://issues.folio.org/browse/MODORDERS-1000
Populate item "Display summary" field. Update save/receive/unreceive action behaviors identical.
Communication is paramount …

[MODORDERS-1000] - Populate Item "Display summary" field with Piece "Display summary" field value

---

src/main/java/org/folio/helper/CheckinHelper.java
src/test/java/org/folio/helper/CheckinHelperTest.java

https://folio-org.atlassian.net/browse/MODORDERS-1022

MODORDERS-1022. Add receipt Date to the CheckIng Piece schema

---

src/main/java/org/folio/service/orders/flows/update/open/OpenCompositeOrderFlowValidator.java
src/test/java/org/folio/service/orders/flows/update/open/OpenCompositeOrderFlowValidatorTest.java

https://folio-org.atlassian.net/browse/MODORDERS-1020
Fixed logic to produce desired result
especially as the number …

[MODORDERS-1020] - Adjust Restricted Location + Fund validation rules

---

descriptors/ModuleDescriptor-template.json

https://folio-org.atlassian.net/browse/MODORDERS-1053

MODORDERS-1053. Missing interface dependencies in module descriptor

---

pom.xml
src/test/java/org/folio/rest/core/RestClientTest.java
src/test/java/org/folio/service/orders/flows/update/open/OpenCompositeOrderInventoryServiceTest.java
src/test/java/org/folio/service/orders/flows/update/open/OpenCompositeOrderManagerTest.java
src/test/java/org/folio/service/orders/flows/update/open/OpenCompositeOrderPieceServiceTest.java
src/test/java/org/folio/service/orders/flows/update/reopen/ReOpenCompositeOrderManagerTest.java
src/test/java/org/folio/service/pieces/PieceServiceTest.java
src/test/java/org/folio/service/pieces/PieceStorageServiceTest.java
src/test/java/org/folio/service/pieces/PieceUpdateInventoryServiceTest.java
src/test/java/org/folio/service/pieces/flows/BasePieceFlowHolderBuilderTest.java
src/test/java/org/folio/service/pieces/flows/create/PieceCreateFlowInventoryManagerTest.java
src/test/java/org/folio/service/pieces/flows/create/PieceCreateFlowPoLineServiceTest.java
src/test/java/org/folio/service/pieces/flows/delete/PieceDeleteFlowManagerTest.java
src/test/java/org/folio/service/pieces/flows/delete/PieceDeleteFlowPoLineServiceTest.java
src/test/java/org/folio/service/pieces/flows/update/PieceUpdateFlowInventoryManagerTest.java
src/test/java/org/folio/service/pieces/flows/update/PieceUpdateFlowManagerTest.java
src/test/java/org/folio/service/pieces/flows/update/PieceUpdateFlowPoLineServiceTest.java

https://folio-org.atlassian.net/browse/MODORDERS-1052
Inspired by: https://github.com/folio-org/raml-module-builder/pull/1146

MODORDERS-1052. mod-orders: Upgrade RAML Module Builder for Quesnelia

---

src/main/java/org/folio/helper/PurchaseOrderLineHelper.java
src/main/java/org/folio/orders/events/handlers/AbstractOrderStatusHandler.java
src/main/java/org/folio/service/finance/transaction/EncumbranceRelationsHoldersBuilder.java
src/main/java/org/folio/service/finance/transaction/EncumbranceService.java
src/main/java/org/folio/service/finance/transaction/OpenToPendingEncumbranceStrategy.java
src/test/java/org/folio/orders/events/handlers/CheckInOrderStatusChangeChangeHandlerTest.java
src/test/java/org/folio/orders/events/handlers/ReceiveOrderStatusChangeHandlerTest.java
src/test/java/org/folio/service/dataimport/handlers/OrderPostProcessingEventHandlerTest.java

https://folio-org.atlassian.net/browse/MODORDERS-1044 …

[MODORDERS-1044] - Do not update orderStatus for past fiscal years

---

pom.xml

https://folio-org.atlassian.net/browse/MODORDERS-1052
Inspired by: https://github.com/folio-org/raml-module-builder/pull/1146

[MODORDERS-1052] Upgrade RAML Module Builder for Quesnelia

---

NEWS.md
pom.xml
src/main/java/org/folio/service/inventory/InventoryManager.java

Release bug fix for Poppy: https://folio-org.atlassian.net/browse/MODORDERS-1061 …

Tmp release 12.7.2

---

pom.xml
src/main/java/org/folio/config/ApplicationConfig.java

Upgrade to the latest folio-di-support
https://github.com/folio-org/folio-di-support/releases/tag/v2.1.0
Release notes: https://github.com/folio-org/folio-di-support/blob/v2.1.0/doc/RELEASE_NOTES.md

MODORDERS-1052. Upgrade to the latest folio-di-support

---

NEWS.md
pom.xml

https://folio-org.atlassian.net/browse/MODORDERS-1064

[MODORDERS-1064] - Release v12.8.0

---

NEWS.md

https://folio-org.atlassian.net/browse/MODORDERS-1064

[MODORDERS-1064] - Update NEWS

---

NEWS.md
src/main/java/org/folio/service/orders/flows/update/unopen/UnOpenCompositeOrderManager.java
src/test/java/org/folio/service/orders/flows/update/unopen/UnOpenCompositeOrderManagerTest.java

https://folio-org.atlassian.net/browse/MODORDERS-1066

MODORDERS-1066. Item records are NOT deleted from Instance when Order is unopened and "Delete items" option is picked

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml
src/main/java/org/folio/helper/PurchaseOrderHelper.java
src/main/java/org/folio/orders/utils/AcqDesiredPermissions.java
src/main/java/org/folio/orders/utils/PermissionsUtil.java
src/main/java/org/folio/service/ProtectionService.java
src/main/java/org/folio/service/dataimport/handlers/CreateOrderEventHandler.java
src/main/java/org/folio/service/orders/flows/update/reopen/ReOpenCompositeOrderManager.java
src/main/java/org/folio/service/orders/flows/update/unopen/UnOpenCompositeOrderManager.java
src/test/java/org/folio/rest/impl/PurchaseOrdersApiTest.java
src/test/java/org/folio/rest/impl/TitlesApiTest.java
src/test/java/org/folio/rest/impl/protection/LinesProtectionTest.java
src/test/java/org/folio/rest/impl/protection/OrdersProtectionTest.java
src/test/java/org/folio/service/orders/flows/update/reopen/ReOpenCompositeOrderManagerTest.java
src/test/java/org/folio/service/orders/flows/update/unopen/UnOpenCompositeOrderManagerTest.java

Bug Fix Release v12.8.1

---

src/main/java/org/folio/service/inventory/InventoryManager.java
src/test/java/org/folio/service/inventory/InventoryManagerTest.java

https://folio-org.atlassian.net/browse/MODORDERS-1080

MODORDERS-1080. ECS - Receiving: cannot create a new Receiving title from scratch

---

descriptors/ModuleDescriptor-template.json

```
status code was: 403, expected: 204, response time in milliseconds: 472, url: https://folio-testing-karate-okapi.ci.folio.org/orders/order-lines/6ecbb3e5-bb05-4041-a89d-d656098bc079, response: 
{
"errors" : [ {
"message" : "Access for user 'test-user' (00000000-1111-5555-9999-999999999992) requires permission: configuration.entries.collection.get",
"code" : "genericError",
"parameters" : [ ]
} ],
"total_records" : 1
}
classpath:thunderjet/mod-orders/features/poline_change_instance_connection.feature:160
```
added desired permission
If there are breaking changes, please **STOP** and consider the …

added required permission to fix karate test

---

pom.xml

Bug Fix Release v12.8.2

---

pom.xml

https://folio-org.atlassian.net/browse/MODDICORE-388
Allow to map vendor details with code that contains brackets during order creation
Update data-import-processing-core dependency to enable the fix MODDICORE-388

MODDICORE-388 Update di-core dependency

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/service/orders/flows/update/open/OpenCompositeOrderFlowValidator.java
src/test/java/org/folio/service/orders/flows/update/open/OpenCompositeOrderFlowValidatorTest.java

https://folio-org.atlassian.net/browse/MODORDERS-1046
Updated check to use tenantId from location objects and retrieve corresponding location using that tenant …

[MODORDERS-1046] - Retrieve holdings from member tenants for Restrict by Locations feature

---

src/main/java/org/folio/service/routinglists/RoutingListService.java
src/main/java/org/folio/service/routinglists/validators/RoutingListValidatorUtil.java
src/test/java/org/folio/rest/impl/RoutingListsApiTest.java
src/test/java/org/folio/service/routinglists/RoutingListServiceTest.java
src/test/java/org/folio/service/routinglists/validators/RoutingListValidatorTest.java

[https://folio-org.atlassian.net/browse/MODORDERS-1006](https://folio-org.atlassian.net/browse/MODORDERS-1006)
- Add new API
- Implement a service for API
- Add validation logic for creating routing lists

[MODORDERS-1006] Create Routing Lists API

---

descriptors/ModuleDescriptor-template.json

Add missed module permissions for https://folio-org.atlassian.net/browse/MODORDERS-1006

MODORDERS-1006. Create Routing Lists API

---

descriptors/ModuleDescriptor-template.json

[MODFIN-352](https://folio-org.atlassian.net/browse/MODFIN-352) - Remove the old transaction API
- Updated finance API version
[mod-finance PR](https://github.com/folio-org/mod-finance/pull/245)
to avoid breaking the …

[MODFIN-352] Updated finance API version support

---

src/main/java/org/folio/config/ApplicationConfig.java
src/main/java/org/folio/helper/PurchaseOrderLineHelper.java
src/main/java/org/folio/service/orders/PurchaseOrderLineService.java
src/main/java/org/folio/service/pieces/flows/create/PieceCreateFlowInventoryManager.java
src/test/java/org/folio/rest/impl/MockServer.java
src/test/java/org/folio/rest/impl/PurchaseOrdersApiTest.java
src/test/java/org/folio/service/orders/lines/update/OrderLineUpdateInstanceHandlerTest.java
src/test/resources/mockdata/holdingsRecords/holdingRecords.json

[MODORDERS-1085](https://folio-org.atlassian.net/browse/MODORDERS-1085) …

[MODORDERS-1085] - Add ability to search by location and holding in POL

---

descriptors/ModuleDescriptor-template.json

[MODORDERS-1085] - add missed permissions

---

NEWS.md
pom.xml
src/main/java/org/folio/service/caches/MappingParametersCache.java
src/main/java/org/folio/service/dataimport/handlers/CreateOrderEventHandler.java
src/test/java/org/folio/di/CacheTest.java

Bug Fix Release v12.8.3

---

src/main/java/org/folio/service/inventory/InventoryManager.java
src/main/java/org/folio/service/orders/PurchaseOrderLineService.java
src/main/java/org/folio/service/orders/utils/HelperUtils.java

[MODORDERS-1085, MODORDERS-1047] - Remove unnecessary holding verification

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml
src/main/java/org/folio/config/ApplicationConfig.java
src/main/java/org/folio/helper/PurchaseOrderLineHelper.java
src/main/java/org/folio/service/inventory/InventoryManager.java
src/main/java/org/folio/service/orders/PurchaseOrderLineService.java
src/main/java/org/folio/service/orders/utils/HelperUtils.java
src/main/java/org/folio/service/pieces/flows/create/PieceCreateFlowInventoryManager.java
src/test/java/org/folio/rest/impl/MockServer.java
src/test/java/org/folio/rest/impl/PurchaseOrdersApiTest.java
src/test/java/org/folio/service/orders/lines/update/OrderLineUpdateInstanceHandlerTest.java
src/test/resources/mockdata/holdingsRecords/holdingRecords.json

Release v12.8.4

---

descriptors/ModuleDescriptor-template.json

Add Get user-tenants permissions for cross tenant ordering

Fix user tenants permissions

---

descriptors/ModuleDescriptor-template.json

Add missed requird interfaces for Ramsons features

Add missed required interfaces for Ramsoms features

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

Bug Fix Release v12.8.6

---

descriptors/ModuleDescriptor-template.json

Small renaming for routing lists functionality to have consistent naming

Rename routing lists to have consistent name

---

NEWS.md

https://folio-org.atlassian.net/browse/MODORDSTOR-393
Updating acq-modules to include changes for Title

Update acq-models to include boundItemIds field in Title

---

src/main/java/org/folio/orders/utils/RequestContextUtil.java
src/main/java/org/folio/service/consortium/ConsortiumConfigurationService.java
src/main/java/org/folio/service/consortium/SharingInstanceService.java
src/main/java/org/folio/service/inventory/InventoryHoldingManager.java
src/main/java/org/folio/service/inventory/InventoryInstanceManager.java
src/main/java/org/folio/service/inventory/InventoryItemManager.java
src/main/java/org/folio/service/orders/flows/update/open/OpenCompositeOrderFlowValidator.java
src/main/java/org/folio/service/orders/flows/update/unopen/UnOpenCompositeOrderManager.java
src/main/java/org/folio/service/pieces/flows/strategies/ProcessInventoryMixedStrategy.java
src/main/java/org/folio/service/pieces/flows/strategies/ProcessInventoryStrategy.java
src/test/java/org/folio/ApiTestSuite.java
src/test/java/org/folio/service/consortium/ConsortiumConfigurationServiceTest.java
src/test/java/org/folio/service/inventory/InventoryManagerTest.java
src/test/java/org/folio/service/orders/flows/update/open/OpenCompositeOrderFlowValidatorTest.java
src/test/java/org/folio/service/orders/flows/update/open/OpenCompositeOrderInventoryServiceTest.java
src/test/java/org/folio/service/orders/flows/update/unopen/UnOpenCompositeOrderManagerTest.java

https://folio-org.atlassian.net/browse/MODORDERS-1084
Update places touching inventory items and holdings based on PO line locations
Communication is paramount if that is …

[MODORDERS-1084] - Create Inventory objects in appropriate tenant from location during UnOpen order

---

src/test/java/org/folio/rest/impl/RoutingListsApiTest.java

Adding metadata to routing lists

[MODORDSTOR-364] Add metadata to routing lists

---

src/main/java/org/folio/config/ApplicationConfig.java
src/main/java/org/folio/service/inventory/InventoryInstanceManager.java
src/main/java/org/folio/service/inventory/InventoryService.java
src/test/java/org/folio/rest/impl/RoutingListsApiTest.java
src/test/java/org/folio/service/inventory/InventoryManagerTest.java
src/test/java/org/folio/service/orders/lines/update/OrderLineUpdateInstanceHandlerTest.java

https://folio-org.atlassian.net/browse/MODORDERS-1106

MODORDERS-1106. New receiving tile erroneously links to pre-existing instance record

---

NEWS.md
pom.xml
src/main/java/org/folio/service/inventory/InventoryManager.java

Release Quesnelia Bug Fix 12.8.7 for ticket https://folio-org.atlassian.net/browse/MODORDERS-1106

Prepare for 12.8.7 Q Bug Fix release

---

src/main/java/org/folio/config/ApplicationConfig.java
src/main/java/org/folio/helper/PurchaseOrderHelper.java
src/main/java/org/folio/helper/PurchaseOrderLineHelper.java
src/main/java/org/folio/orders/utils/PoLineCommonUtil.java
src/main/java/org/folio/orders/utils/RequestContextUtil.java
src/main/java/org/folio/service/inventory/InventoryItemStatusSyncService.java
src/test/java/org/folio/ApiTestSuite.java
src/test/java/org/folio/helper/PurchaseOrderHelperTest.java
src/test/java/org/folio/service/inventory/InventoryItemStatusSyncServiceTest.java
src/test/resources/mockdata/compositeOrders/9d56b621-202d-414b-9e7f-5fefe4422ab3.json

https://folio-org.atlassian.net/browse/MODORDERS-1105

MODORDERS-1105. Update logic to handle item status "On order" "Order closed" in correct tenant

---

descriptors/ModuleDescriptor-template.json

karate tests are failing because of non-existing permission

added missed permission

---

src/main/java/org/folio/service/orders/flows/update/unopen/UnOpenCompositeOrderManager.java

https://folio-org.atlassian.net/browse/MODORDERS-1103
Fixed request context usages to work with pieces using central tenant and with items and holdings using location tenant.
to avoid breaking the folio-testing …

[MODORDERS-1103] - Update UnOpenCompositeOrderManager::deleteHoldings to use tenantId parameter

---

src/main/java/org/folio/helper/BindHelper.java
src/main/java/org/folio/helper/CheckinHelper.java
src/main/java/org/folio/helper/CheckinReceivePiecesHelper.java
src/main/java/org/folio/helper/ExpectHelper.java
src/main/java/org/folio/helper/ReceivingHelper.java
src/main/java/org/folio/service/inventory/InventoryHoldingManager.java
src/main/java/org/folio/service/inventory/InventoryItemManager.java
src/main/java/org/folio/service/orders/flows/update/open/OpenCompositeOrderPieceService.java
src/main/java/org/folio/service/pieces/PieceUpdateInventoryService.java
src/main/java/org/folio/service/pieces/flows/create/PieceCreateFlowInventoryManager.java
src/main/java/org/folio/service/pieces/flows/update/PieceUpdateFlowInventoryManager.java
src/test/java/org/folio/service/inventory/InventoryManagerTest.java
src/test/java/org/folio/service/orders/flows/update/open/OpenCompositeOrderPieceServiceTest.java
src/test/java/org/folio/service/orders/lines/update/OrderLineUpdateInstanceHandlerTest.java
src/test/java/org/folio/service/pieces/flows/create/PieceCreateFlowInventoryManagerTest.java

https://folio-org.atlassian.net/browse/MODORDERS-1096
Use location context when working with inventory holdings and items …

Modorders 1096

---

src/main/java/org/folio/service/orders/CompositePoLineValidationService.java
src/test/java/org/folio/service/orders/CompositePoLineValidationServiceTest.java

https://folio-org.atlassian.net/browse/MODORDERS-1014 …

updated acq-models to include typo fix

---

src/main/java/org/folio/service/orders/lines/update/instance/WithHoldingOrderLineUpdateInstanceStrategy.java

After some our refactroring in previous sprint populating of holder with holdings ids was deleted from MoveHolding logic that caused karate test to fail:
https://folio-org.atlassian.net/browse/FAT-13856
In this PR we revert back this holder invocation:

FAT-13856. Fixed poline_change_instance_connection.feature karate test

---

src/main/java/org/folio/helper/PurchaseOrderLineHelper.java
src/main/java/org/folio/orders/utils/HelperUtils.java
src/main/java/org/folio/orders/utils/StreamUtils.java
src/main/java/org/folio/service/inventory/InventoryHoldingManager.java
src/main/java/org/folio/service/orders/PurchaseOrderLineService.java
src/test/java/org/folio/ApiTestSuite.java
src/test/java/org/folio/helper/PurchaseOrderLineHelperTest.java
src/test/java/org/folio/orders/utils/HelperUtilsTest.java
src/test/java/org/folio/orders/utils/StreamUtilsTest.java
src/test/java/org/folio/service/inventory/InventoryManagerTest.java

https://folio-org.atlassian.net/browse/MODORDERS-1120
Update `updateSearchLocations` logic to retrieve permanent locations by holdings from corresponding tenants …

[MODORDERS-1120] - Support populating searchLocationId for correct tenant during order opening

---

pom.xml

https://folio-org.atlassian.net/browse/MODFIN-370 …

Update acq-models to include changes in credit fields

---

src/main/java/org/folio/models/consortium/SharingInstanceCollection.java
src/main/java/org/folio/service/consortium/SharingInstanceService.java
src/main/java/org/folio/service/inventory/InventoryInstanceManager.java
src/test/java/org/folio/ApiTestSuite.java
src/test/java/org/folio/service/inventory/InventoryInstanceManagerTest.java
src/test/java/org/folio/service/inventory/InventoryManagerTest.java

https://folio-org.atlassian.net/browse/MODORDERS-1130
mod-consortia has endpoint that we can use to know in each tenant instanse was shared that should be used

[MODORDERS-1130] ECS | Order can not be opened if contains three locations from different tenants

---

descriptors/ModuleDescriptor-template.json

Add missed module permission for https://github.com/folio-org/mod-orders/pull/963

MODORDERS-1130. Add missed module permission

---

src/main/java/org/folio/helper/BindHelper.java
src/main/java/org/folio/helper/CheckinHelper.java
src/main/java/org/folio/helper/CheckinReceivePiecesHelper.java
src/main/java/org/folio/helper/ExpectHelper.java
src/main/java/org/folio/helper/ReceivingHelper.java
src/main/java/org/folio/service/inventory/InventoryItemManager.java
src/main/java/org/folio/service/inventory/InventoryUtils.java
src/test/java/org/folio/ApiTestSuite.java
src/test/java/org/folio/helper/CheckinHelperTest.java
src/test/java/org/folio/rest/impl/CheckinReceivingApiTest.java
src/test/java/org/folio/service/inventory/InventoryManagerTest.java
src/test/java/org/folio/service/inventory/InventoryUtilsTest.java

https://folio-org.atlassian.net/browse/MODORDERS-1133
1. Consider receiving tenant id when creating holdings for changed locations
2. Check that instance is shared for that tenant before creating a holding
to avoid …

[MODORDERS-1133] - Add support of creating holding in member tenants for Receiving

---

src/main/java/org/folio/service/inventory/InventoryItemManager.java
src/test/java/org/folio/rest/impl/CheckinReceivingApiTest.java

[[MODORDERS-1131] Fix piece, item, title relationship in bind piece features](https://folio-org.atlassian.net/browse/MODORDERS-1131)
- Change newly created bind item status to "In Process" from "On Order"

[MODORDERS-1131] Change bind item status

---

src/main/java/org/folio/helper/BindHelper.java

[[MODORDERS-1131] Fix piece, item, title relationship in bind piece features](https://folio-org.atlassian.net/browse/MODORDERS-1131)
- Implement overridden method to validate and bind pieces correctly

[MODORDERS-1131] Fix binding endpoint piece validation

---

src/main/java/org/folio/service/orders/PurchaseOrderLineService.java
src/test/java/org/folio/rest/impl/PurchaseOrdersApiTest.java

Fix issue to not create new Po Line object for https://folio-org.atlassian.net/browse/MODORDERS-1120

MODORDERS-1120. Fix into populating searchLocationIds

---

src/main/java/org/folio/service/CirculationRequestsRetriever.java

[[MODORDERS-1138] Implement endpoint to fetch Circulation requests for pieces](https://folio-org.atlassian.net/browse/MODORDERS-1138)
- Add tenantId to requests only for new endpoint
Karate tests pass:

[MODORDERS-1138] Add tenantId to requests only for new endpoint

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/models/TemplateProcessingRequest.java
src/main/java/org/folio/service/routinglists/RoutingListService.java
src/test/java/org/folio/service/routinglists/RoutingListServiceTest.java
src/test/resources/mockdata/routingLists/eee951de-ea49-400a-96e8-705ae5a1e1e8-expected-template-request.json

https://folio-org.atlassian.net/browse/MODORDERS-1145
Related karate change: https://github.com/folio-org/folio-integration-tests/pull/1448

MODORDERS-1145. Add Instance Title to Context for template request

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/helper/BindHelper.java

[[MODORDERS-1146] Add link to original item for piece that is bound](https://folio-org.atlassian.net/browse/MODORDERS-1146)
- Update module descriptor

[MODORDERS-1146] Update module descriptor

---

src/main/java/org/folio/service/orders/flows/update/open/OpenCompositeOrderFlowValidator.java

https://folio-org.atlassian.net/browse/MODORDERS-1151 …

[MODORDERS-1151] - Central ordering - Opening and editing POs with cation-restricted funds (FE)

---

src/main/java/org/folio/service/inventory/InventoryInstanceManager.java

[[MODORDERS-1154] 500 response when opening order with 2 restricted funds and appropriate locations for each fund from Member tenant](https://folio-org.atlassian.net/browse/MODORDERS-1154)
Remove duplicate tenantIds while sharing

[MODORDERS-1154] Remove duplicate tenantId's while sharing

---

src/main/java/org/folio/service/inventory/InventoryItemRequestService.java

[[MODORDERS-1154] 500 response when opening order with 2 restricted funds and appropriate locations for each fund from Member tenant](https://folio-org.atlassian.net/browse/MODORDERS-1154)
Moving several requests at the same time could be erroneous as the API does not guarantee requests' order for items would be correct, thus need to move the requests sequentially for the sake of correct reordering of requests
Associated bug report for circulation: [[CIRC-2123] Unable to move circulation requests to a new item](https://folio-org.atlassian.net/browse/CIRC-2123)

[MODORDERS-1154] Move requests during binding sequentially

---

src/main/java/org/folio/service/exchange/ManualCurrencyConversion.java
src/test/java/org/folio/orders/utils/HelperUtilsTest.java
src/test/java/org/folio/service/orders/OrderRolloverServiceTest.java
src/test/java/org/folio/utils/CurrencyConversionMockHelper.java

- Apply minor test refactoring and cleaning (for better long-term maintenance)
- Update comments, rename & refactor methods

[MODORDERS-1150-2]. Apply minor test refactoring and cleaning

---

src/main/java/org/folio/service/orders/flows/update/unopen/UnOpenCompositeOrderManager.java

- <https://folio-org.atlassian.net/browse/FAT-16265>
- Add extra logging on unopening to improve the debugging of failing Karate test

[FAT-16265]. Update logging on unopening

---

src/main/java/org/folio/orders/utils/PoLineCommonUtil.java
src/test/java/org/folio/orders/utils/PoLineCommonUtilTest.java

https://folio-org.atlassian.net/browse/MODORDERS-1160

MODORDERS-1160. Unable to edit PO line when details field is empty.

---

descriptors/ModuleDescriptor-template.json

https://folio-org.atlassian.net/browse/MODORDERS-1182

MODORDERS-1182. Bump pieces interfaces minor version to 3.1 after new endpoint was added

---

descriptors/ModuleDescriptor-template.json

- <https://folio-org.atlassian.net/browse/MODORDERS-1173>
- Add missing receive permissions

[MODORDERS-1173-2]. Add missing receive permissions

---

NEWS.md
pom.xml
src/main/java/org/folio/helper/PurchaseOrderLineHelper.java
src/test/java/org/folio/helper/PurchaseOrderLineHelperTest.java

Make hot fix release for Quesnelia service patch 4 to include ticket 
https://folio-org.atlassian.net/browse/MODORDERS-1185

MODORDERS-1185. mod-orders 12.8.10 bug fix release

---

src/main/java/org/folio/service/consortium/ConsortiumUserTenantsRetriever.java
src/main/java/org/folio/service/pieces/PieceStorageService.java
src/test/java/org/folio/service/pieces/PieceStorageServiceTest.java

[[MODORDERS-1174] Filter pieces based on user affiliations](https://folio-org.atlassian.net/browse/MODORDERS-1174)
- Fix piece filtering for member tenants
- Update tests

[MODORDERS-1174] Fix piece filtering for member tenants

---

src/main/java/org/folio/service/dataimport/handlers/CreateOrderEventHandler.java
src/test/java/org/folio/service/dataimport/handlers/CreateOrderEventHandlerTest.java

Avoid NPE if fund mapping rule does not contain accepted values
Use mapping parameters to ensure fund code

[MODDICORE-411] Use mapping parameters to ensure fund code

---

src/main/java/org/folio/service/pieces/PieceStorageService.java
src/test/java/org/folio/orders/utils/QueryUtilsTest.java
src/test/java/org/folio/service/pieces/PieceStorageServiceTest.java

[[MODORDERS-1174] Filter pieces based on user affiliations](https://folio-org.atlassian.net/browse/MODORDERS-1174)
- Fix CQL generation with sortby operation present
- Update tests

[MODORDERS-1174] Fix CQL generation for filtering pieces with sortby query

---

descriptors/ModuleDescriptor-template.json

bump up inventory interface version

---

NEWS.md
descriptors/ModuleDescriptor-template.json

[MODORDERS-1193](https://folio-org.atlassian.net/browse/MODORDERS-1193)
Upgrade the API version in the ModuleDescriptor-template.json:
-`holdings-storage 8.0` …

[MODORDERS-1193] Upgrade "holdings-storage" API

---

src/main/java/org/folio/rest/core/exceptions/ErrorCodes.java
src/main/java/org/folio/service/pieces/flows/delete/PieceDeleteFlowManager.java

https://folio-org.atlassian.net/browse/MODORDERS-1195
- Updated error code message to be concise

[MODORDERS-1195] - Rename error code name

---

src/main/java/org/folio/rest/core/exceptions/ErrorCodes.java

https://folio-org.atlassian.net/browse/MODORDERS-1195
- improved msg …

[MODORDERS-1195] - Improve messages

---

NEWS.md
pom.xml
src/main/java/org/folio/helper/PurchaseOrderLineHelper.java
src/main/java/org/folio/service/consortium/ConsortiumUserTenantsRetriever.java
src/main/java/org/folio/service/inventory/InventoryItemStatusSyncService.java
src/main/java/org/folio/service/invoice/InvoiceLineService.java
src/main/java/org/folio/service/orders/CompositeOrderTotalFieldsPopulateService.java
src/main/java/org/folio/service/pieces/PieceStorageService.java
src/test/java/org/folio/helper/PurchaseOrderLineHelperTest.java
src/test/java/org/folio/service/inventory/InventoryItemStatusSyncServiceTest.java
src/test/java/org/folio/service/orders/CompositeOrderTotalFieldsPopulateServiceTest.java

Bug Fix Release v12.9.1

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml
src/main/java/org/folio/config/ApplicationConfig.java
src/main/java/org/folio/helper/BindHelper.java
src/main/java/org/folio/service/consortium/ConsortiumConfigurationService.java
src/main/java/org/folio/service/orders/lines/update/OrderLinePatchOperationService.java
src/main/java/org/folio/service/orders/lines/update/instance/BaseOrderLineUpdateInstanceStrategy.java
src/main/java/org/folio/service/orders/lines/update/instance/WithHoldingOrderLineUpdateInstanceStrategy.java
src/test/java/org/folio/service/CirculationRequestsRetrieverTest.java
src/test/java/org/folio/service/consortium/ConsortiumConfigurationServiceTest.java
src/test/java/org/folio/service/orders/lines/update/OrderLineUpdateInstanceHandlerTest.java
src/test/java/org/folio/service/pieces/PieceStorageServiceTest.java

Prepare for Ramsons Bug Fix release v12.9.2 that includes fix for https://folio-org.atlassian.net/browse/MODORDERS-1211

Ramsons Bug Fix release v12.9.2

---

NEWS.md
pom.xml
src/main/java/org/folio/service/orders/lines/update/OrderLinePatchOperationService.java

Buf Fix release for tickets:
https://folio-org.atlassian.net/browse/MODORDERS-1218
https://folio-org.atlassian.net/browse/MODORDERS-1219

Ramsons v12.9.3 release

---

src/main/java/org/folio/helper/PurchaseOrderHelper.java
src/main/java/org/folio/helper/PurchaseOrderLineHelper.java
src/main/java/org/folio/service/orders/CompositePoLineValidationService.java
src/test/java/org/folio/helper/PurchaseOrderHelperTest.java
src/test/java/org/folio/service/orders/CompositePoLineValidationServiceTest.java

- <https://folio-org.atlassian.net/browse/EUREKA-561>
- Add validation to Update Order action
- Update method arguments for Update Order Line action
- Simplify location validation
- Update unit tests

[EUREKA-561-5]. Simplify location validation, update tests

---

NEWS.md
pom.xml
src/main/java/org/folio/config/ApplicationConfig.java
src/main/java/org/folio/helper/PurchaseOrderHelper.java
src/main/java/org/folio/helper/PurchaseOrderLineHelper.java
src/main/java/org/folio/service/ProtectionService.java
src/main/java/org/folio/service/consortium/ConsortiumConfigurationService.java
src/main/java/org/folio/service/finance/transaction/EncumbranceRelationsHoldersBuilder.java
src/main/java/org/folio/service/orders/CompositePoLineValidationService.java
src/test/java/org/folio/helper/PurchaseOrderHelperTest.java
src/test/java/org/folio/helper/PurchaseOrderLineHelperTest.java
src/test/java/org/folio/service/finance/transaction/EncumbranceRelationsHoldersBuilderTest.java
src/test/java/org/folio/service/orders/CompositePoLineValidationServiceTest.java

Release Ramsons bug fix that includes these 2 tickets:
https://folio-org.atlassian.net/browse/MODORDERS-1223
https://folio-org.atlassian.net/browse/MODORDERS-1222

Release Ramsons bugfix 12.9.4

---

descriptors/ModuleDescriptor-template.json

MODORDERS-1223 add missed permission

---

NEWS.md
pom.xml
src/main/java/org/folio/service/orders/lines/update/OrderLinePatchOperationService.java

https://folio-org.atlassian.net/browse/MODORDERS-1218 …

Bug Fix Release - 12.9.7 

---

NEWS.md
pom.xml
src/main/java/org/folio/service/CirculationRequestsRetriever.java
src/main/java/org/folio/service/consortium/ConsortiumConfigurationService.java
src/main/java/org/folio/service/inventory/InventoryItemRequestService.java
src/main/java/org/folio/service/inventory/util/RequestFields.java

https://folio-org.atlassian.net/browse/MODORDERS-1211
https://folio-org.atlassian.net/browse/MODORDERS-1231 …

Bug Fix Release v12.9.8

---

src/main/java/org/folio/service/orders/OrderRolloverService.java
src/test/java/org/folio/service/orders/OrderRolloverServiceTest.java

[MODORDERS-1217](https://folio-org.atlassian.net/browse/MODORDERS-1217): Ongoing orders cannot be reopened with inactive budget for fund
We are already removing encumbrance links for closed orders during order rollover.
This change will remove encumbrance links for pending orders at the same time, so we don't have a situation where a pending order cannot be opened because of an inactive budget.
- The encumbrance transactions are not affected by the change, so it is possible an encumbrance persists without any reference to it. It can also happen for closed orders. This issue will be addressed in a separate ticket.
- This PR does not try to fix bad existing data after a FYRO, this will also be addressed separately.
[Related integration test …

[MODORDERS-1217] FYRO: remove encumbrance links for pending orders

---

descriptors/ModuleDescriptor-template.json

```
sidecar-mod-orders,/change-manager/jobExecutions/d9d7194a-c1a0-4c18-add8-94d3bec0a8f8,2
sidecar-mod-orders,/organizations/organizations,13
sidecar-mod-orders,/data-import-profiles/jobProfileSnapshots/19306325-d449-4af7-835e-13677bd881fd,4
sidecar-mod-orders,/chanager/jobExecutionnge-mas/f837904f-f4bc-46ef-b54b-5a30fc0608bb,1
sidecar-mod-orders,/circulation/requests/285d0a68-00f8-45e6-ba50-46da3fd007a3/move,1
sidecar-mod-orders,/data-import-profiles/jobProfileSnapshots/90811447-e5dc-46d3-9535-0994b292ee23,5
sidecar-mod-orders,/data-import-profiles/jobProfileSnapshots/1312bb9a-7f56-43f2-bcca-93e012f0befa,9
sidecar-mod-orders,/data-import-profiles/jobProfileSnapshots/7cdb5ab9-6c9e-4210-b3ff-dbbb5316991e,1
sidecar-mod-orders,/data-import-profiles/jobProfileSnapshots/7eaa2122-e19a-4ab7-8208 …
```

[MODORDERS-1244] - Add missing required interfaces to Module Descriptor

---

src/main/java/org/folio/rest/core/exceptions/ErrorCodes.java
src/main/java/org/folio/service/finance/FinanceHoldersBuilder.java
src/test/java/org/folio/service/finance/FinanceHoldersBuilderTest.java

…
https://folio-org.atlassian.net/browse/MODORDERS-1235 …

[MODORDERS-1235] - Wrong error message appears when trying to open or der with two POLs contain funds from different fiscal years

---

NEWS.md
pom.xml
src/main/java/org/folio/service/orders/CompositeOrderTotalFieldsPopulateService.java
src/test/java/org/folio/service/orders/CompositeOrderTotalFieldsPopulateServiceTest.java

Bug Fix Release v12.9.11

---

.github/workflows/buildMaven.yml
Dockerfile
Jenkinsfile
pom.xml

[[FOLIO-4209] Update to mod-orders Java 21](https://folio-org.atlassian.net/browse/FOLIO-4209)
Update java and dependency versions

[FOLIO-4209] Update to mod-orders Java 21

---

pom.xml

[[FOLIO-4209] Update to mod-orders Java 21](https://folio-org.atlassian.net/browse/FOLIO-4209)
Update maven-compiler-plugin to Java 21

[FOLIO-4209] Update maven-compiler-plugin to Java 21

---

NEWS.md
pom.xml

https://folio-org.atlassian.net/browse/MODORDERS-1259 …

Release v13.0.0

---

NEWS.md
pom.xml
src/main/java/org/folio/models/claiming/IntegrationDetailField.java
src/main/java/org/folio/service/pieces/PiecesClaimingService.java
src/test/java/org/folio/rest/impl/PiecesClaimingApiTest.java

Make Bug Fix release for Sunflower for ticket:
https://folio-org.atlassian.net/browse/MODORDERS-1264

[MODEXPW-578]. Bug fix release 13.0.1 for Sunflower

---

src/main/java/org/folio/helper/PurchaseOrderHelper.java
src/main/java/org/folio/orders/utils/POProtectedFields.java
src/test/java/org/folio/rest/impl/PurchaseOrdersApiTest.java

https://folio-org.atlassian.net/browse/UIOR-1105
Remove Close Reason from protected fields

UIOR-1105. Remove CloseReason from protected fields

---

NEWS.md
pom.xml
src/main/java/org/folio/helper/PurchaseOrderHelper.java
src/main/java/org/folio/orders/utils/HelperUtils.java
src/test/java/org/folio/helper/PurchaseOrderHelperTest.java

Prepare for Sunflower Bug Fix v13.0.2 release

Sunflower v13.0.2 release

---

descriptors/ModuleDescriptor-template.json

- settings related permission missed in delete title feature …

Add missed permission for delete title 

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/models/TitleHolder.java
src/main/java/org/folio/service/titles/TitlesService.java
src/test/java/org/folio/service/TitlesServiceTest.java

Found several issue on current implementation after working with karate tests
https://folio-org.atlassian.net/browse/MODORDERS-1260
- item and pieces should be deleted even deleteHoldings=false because title cannot be deleted before clearing pieces
- if there are holdings are connected to other title, then related to item and pieces should be only deleted and holding iteself should be remain
- Are the JIRAs under active …

Fix deletion of item and pieces related to title

---

src/main/java/org/folio/helper/PurchaseOrderLineHelper.java

Fix failing karate test. After applying this change ebsconet karate tests run

MODORDERS-1287. Fix failing karate tests for ebsconet

---

src/main/java/org/folio/config/ApplicationConfig.java
src/main/java/org/folio/service/orders/CompositeOrderTotalFieldsPopulateService.java
src/test/java/org/folio/service/orders/CompositeOrderTotalFieldsPopulateServiceTest.java
src/test/java/org/folio/service/orders/OrderRolloverServiceTest.java
src/test/java/org/folio/utils/CurrencyConversionMockHelper.java

[MODORDERS-1308](https://folio-org.atlassian.net/browse/MODORDERS-1308) - Order expended amount is not converting the invoice currency
- Gather exchange rates for invoices and encumbrances before calculations
- Calculate totals using the exchange rates to the system currency
- New unit tests
[integration test PR](https://github.com/folio-org/folio-integration-tests/pull/1902)
- Do PRs …

[MODORDERS-1308] Convert invoice and encumbrance currencies for total amounts

---

.github/dependabot.yml
CODEOWNERS
PULL_REQUEST_TEMPLATE.md

https://folio-org.atlassian.net/browse/MODORDERS-1324

MODORDERS-1324. Setup dependabot for your module

---

src/main/java/org/folio/rest/impl/PiecesAPI.java

Support related UI story https://folio-org.atlassian.net/browse/UIREC-450
_Provide a brief technical summary of the changes._
---

UIREC-450. internal and external note fields not populated when user sets new piece to "Claim sent"

---

NEWS.md
pom.xml
src/main/java/org/folio/helper/CheckinHelper.java
src/main/java/org/folio/helper/ReceivingHelper.java
src/main/java/org/folio/service/inventory/InventoryItemManager.java
src/main/java/org/folio/service/inventory/InventoryUtils.java
src/main/java/org/folio/service/orders/flows/update/open/OpenCompositeOrderPieceService.java
src/main/java/org/folio/service/pieces/flows/update/PieceUpdateFlowInventoryManager.java
src/test/java/org/folio/service/inventory/InventoryUtilsTest.java
src/test/java/org/folio/service/orders/flows/update/open/OpenCompositeOrderPieceServiceTest.java
src/test/java/org/folio/service/pieces/flows/update/PieceUpdateFlowInventoryManagerTest.java

Prepare for Ramsons v12.9.3 release 
Includes ticket https://folio-org.atlassian.net/browse/MODORDERS-1330
---

MODORDERS-1330. Prepare for Ramsons 12.9.13 release

---

pom.xml
src/main/java/org/folio/verticle/DataImportConsumerVerticle.java

to configure groupInstanceId parameter during consumer wrapper creation
[MODORDERS-1341](https://issues.folio.org/browse/MODORDERS-1341)

MODORDERS-1341 - Configure consumer groupInstanceId
