folio-org/mod-orders

- pom.xml
- ramls/order.raml
- src/test/java/org/folio/rest/impl/OrdersResourceImplTest.java
- src/test/resources/po_creation_failure.json
- src/test/resources/po_line_creation_failure.json
- src/test/resources/po_listed_print_monograph.json
The composite_purchase_order schema was updated to refer to a new composite_po_line schema that combines the po_line schema and all of its UUID references as schema "refs".
> MODORDERS-24: Add support for composite PO line

- src/main/java/org/folio/rest/impl/PostOrdersHelper.java
see [MODORDERS-29](https://issues.folio.org/browse/MODORDERS-29)
The algorithm I chose is based on a hex representation of milliseconds since an arbitrary epoch (9/1/2018), with 1-2 hex digits at the end (obtained from nanotime) for entropy.  The entire string is upper-cased.
Append a dash followed by a sequential number (1-999)
**Example:**
* PONumber: `2274C0AF60`
* POLNumbers:  `2274C0AF60-1`, `2274C0AF60-2`, `2274C0AF60-3`
If we need to change the algorithm later, we can.  I just wanted to get _something_ in place so we can move forward.
> generate poNumber and polNumber

- src/main/java/org/folio/rest/impl/OrdersResourceImpl.java
- src/main/java/org/folio/rest/impl/PostOrdersHelper.java
- src/test/java/org/folio/rest/impl/OrdersResourceImplTest.java
- src/test/resources/po_listed_print_monograph.json
see [MODORDERS-27](https://issues.folio.org/browse/MODORDERS-27) and [MODORDERS-28](https://issues.folio.org/browse/MODORDERS-28)
I actually went as far as implementing this for:
- cost
- details
- eresource
- location
- vendor_details
NOTE:  the POLine <-> SubObject relationships are doubly linked in the schemas, i.e. the POLine references the SubObject by Id and the SubObject references POLine by Id.  For now I just reference the SubObject from POLine.
We can later add additional calls to add the backwards reference.
> MODORDERS-27 MODORDERS-28

- src/main/resources/mockdata/07f65192-44a4-483d-97aa-b137bbd96390.json
- src/main/resources/mockdata/1d6a455f-29c5-4e51-84d9-e28450ef86ad.json
- src/main/resources/mockdata/9447d062-89ec-486e-a14b-572f3efb9f8c.json
- src/main/resources/mockdata/c27e60f9-6361-44c1-976e-0c4821a33a7d.json
- src/main/resources/mockdata/e20af8c8-b07d-47a1-9ebd-f1187e9335bd.json
- src/main/resources/mockdata/e41e0161-2bc6-41f3-a6e7-34fc13250bf1.json
- src/main/resources/mockdata/e5ae4afd-3fa9-494e-a972-f541df9b877e.json
- src/main/resources/mockdata/f4dc647c-ec82-442e-b13d-f9505b7ce8e9.json
There were a few minor issues we missed in MODORDERS-48... e.g. typos, enum fields set to "" or null, etc.
> MODORDERS-48 (follow-on) remove empty/null renewal.cycle fields

- src/main/java/org/folio/rest/impl/PostOrdersHelper.java
- src/main/resources/mockdata/00ed10af-fac2-46ad-9f94-a298358646a2.json
- src/main/resources/mockdata/05bdf3c8-01f0-4ddb-bd6c-6efd465f9e33.json
- src/main/resources/mockdata/0610be6d-0ddd-494b-b867-19f63d8b5d6d.json
- src/main/resources/mockdata/07f65192-44a4-483d-97aa-b137bbd96390.json
- src/main/resources/mockdata/1ab7ef6a-d1d4-4a4f-90a2-882aed18af14.json
- src/main/resources/mockdata/1d6a455f-29c5-4e51-84d9-e28450ef86ad.json
- src/main/resources/mockdata/55b97a4a-6601-4488-84e1-8b0d47a3f523.json
- src/main/resources/mockdata/589a6016-3463-49f6-8aa2-dc315d0665fd.json
- src/main/resources/mockdata/8c328a18-5761-4329-95f6-599412c32310.json
- src/main/resources/mockdata/9447d062-89ec-486e-a14b-572f3efb9f8c.json
- src/main/resources/mockdata/c27e60f9-6361-44c1-976e-0c4821a33a7d.json
- src/main/resources/mockdata/e20af8c8-b07d-47a1-9ebd-f1187e9335bd.json
- src/main/resources/mockdata/e41e0161-2bc6-41f3-a6e7-34fc13250bf1.json
- src/main/resources/mockdata/e5ae4afd-3fa9-494e-a972-f541df9b877e.json
- src/main/resources/mockdata/f4dc647c-ec82-442e-b13d-f9505b7ce8e9.json
- src/main/resources/mockdata/getOrders.json
- src/test/java/org/folio/rest/impl/OrdersResourceImplTest.java
- src/test/resources/po_creation_failure.json
- src/test/resources/po_line_creation_failure.json
- src/test/resources/po_listed_electronic_monograph.json
- src/test/resources/po_listed_print_monograph.json
- src/test/resources/po_listed_print_serial.json
The latest schema changes include pulling the purchase_order fields up to the top-level of composite_purchase_order.
See [MODORDERS-53](https://issues.folio.org/browse/MODORDERS-53) for additional details.
Due to a discrepancy between composite_purchase_order and purchase_order schemas, I added a bit of code to strip off any adjustment fields in orders during placement.  The top/po-level adjustments are calculated based on the po_line adjustment data (summation).  I added a rudimentary impl of this too while I was at it.
*NOTE* the acq-models submodule was updated to point to the MODORDERS-53 branch of that repo.  Once https://github.com/folio-org/acq-models/pull/38 is merged, I'll update it to be the latest commit.  There shouldn't be any schemas differences, just the submodule …
> MODORDERS-53 Update mock data, code and tests to work with latest schema changes

- pom.xml
- src/main/java/org/folio/rest/impl/PostOrdersHelper.java
- src/test/java/org/folio/rest/impl/OrdersResourceImplTest.java
* Now builds pojos for all the mod-orders-storage schemas - helpful for validation of objects in unit test mocks
* Implemented sub-obj creation for Physical and Adjustment
* Stub/Temporarily remove other sub-objs that aren't being created (marked with TODO) - alerts, claims, fund_distribution, reporting_codes, source
* Updated the unit test mocks to validate against the schema via the auto-generated pojos
See [MODORDERS-56](https://issues.folio.org/browse/MODORDERS-56) for additional details.
> MODORDERS-56 Fix PoLine and sub object creation

- src/main/java/org/folio/rest/impl/PostOrdersHelper.java
Fix for below:
On creating a new order by doing POST /orders throws this error -
Json content error Can not deserialize instance of java.lang.String out of START_OBJECT token
at [Source: java.io.StringReader@6b35e036; line: 1, column: 1067] (through reference chain: org.folio.rest.jaxrs.model.PoLine["renewal"])
This means `renewal` is missing and it is not created via mod-orders-storage. Also, it is not being removed from the po_line(temporary workaround)
Adding `license` to the removal list.
> Remove renewal so create does not break

- .gitmodules
- NEWS.md
- pom.xml
- ramls/order.raml
- src/main/java/org/folio/orders/utils/HelperUtils.java
- src/main/java/org/folio/rest/impl/DeleteOrdersByIdHelper.java
- src/main/java/org/folio/rest/impl/GetOrdersByIdHelper.java
- src/main/java/org/folio/rest/impl/GetOrdersHelper.java
- src/main/java/org/folio/rest/impl/OrdersImpl.java
- src/main/java/org/folio/rest/impl/PostOrdersHelper.java
- src/test/java/org/folio/rest/impl/OrdersImplTest.java
- Migrate order.raml to 1.0 version
- RMB version changed from 19.3.1 to 23.2.0
- Updating ramls/raml-util submodule to latest commit
- Switching from apache log4j to vert.x Logger (the RMB runtime defines `Log4j2LogDelegateFactory` for vert.x Logger)
- Generated interface does not have the 'Resource' suffix and the response codes have changed
- OrdersResourceImpl renamed to OrdersImpl (and corresponding unit test class)
- Helper classes udated to use new method names
Note: the [RMB upgrade notes](https://github.com/folio-org/raml-module-builder/blob/master/doc/upgrading.md) describes details on what is required for migration.
> MODORDERS-62 Update to RAML 1.0 and RMB 23

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- ramls/order.raml
- src/main/java/org/folio/rest/impl/DeleteOrdersByIdHelper.java
- src/main/java/org/folio/rest/impl/OrdersImpl.java
- Defining PO line endpoints in raml and module descriptor files
- Defining permissions for PO line endpoints
- Adding composite PO line sample
- Add `post-item` as a resource type (post-empty-body.raml) and define request body when it is used
- Switch acq-models to latest `b0fd771` commit
- Updating News file
> Modorders 75 order line endpoints

- pom.xml
- src/main/java/org/folio/orders/utils/HelperUtils.java
- src/main/java/org/folio/rest/impl/DeleteOrderLineByIdHelper.java
- src/main/java/org/folio/rest/impl/OrdersImpl.java
- Closing `HttpClientInterface` on success case in `DeleteOrderLineByIdHelper`
- Setting `forceAjcCompile` to `true` for `aspectj-maven-plugin`. For local re-builds the interface is recompiled each time and in some cases aspectj plugin skipps updating class files with required join points
> MODORDERS-79 Delete PO line

- src/main/resources/mockdata/00ed10af-fac2-46ad-9f94-a298358646a2.json
- src/main/resources/mockdata/05bdf3c8-01f0-4ddb-bd6c-6efd465f9e33.json
- src/main/resources/mockdata/0610be6d-0ddd-494b-b867-19f63d8b5d6d.json
- src/main/resources/mockdata/07f65192-44a4-483d-97aa-b137bbd96390.json
- src/main/resources/mockdata/1ab7ef6a-d1d4-4a4f-90a2-882aed18af14.json
- src/main/resources/mockdata/1d6a455f-29c5-4e51-84d9-e28450ef86ad.json
- src/main/resources/mockdata/55b97a4a-6601-4488-84e1-8b0d47a3f523.json
- src/main/resources/mockdata/589a6016-3463-49f6-8aa2-dc315d0665fd.json
- src/main/resources/mockdata/8c328a18-5761-4329-95f6-599412c32310.json
- src/main/resources/mockdata/9447d062-89ec-486e-a14b-572f3efb9f8c.json
- src/main/resources/mockdata/c27e60f9-6361-44c1-976e-0c4821a33a7d.json
- src/main/resources/mockdata/e20af8c8-b07d-47a1-9ebd-f1187e9335bd.json
- src/main/resources/mockdata/e41e0161-2bc6-41f3-a6e7-34fc13250bf1.json
- src/main/resources/mockdata/e5ae4afd-3fa9-494e-a972-f541df9b877e.json
- src/main/resources/mockdata/f4dc647c-ec82-442e-b13d-f9505b7ce8e9.json
- src/test/resources/mockdata/compositeLines/0009662b-8b80-4001-b704-ca10971f175d.json
- src/test/resources/mockdata/compositeLines/c0d08448-347b-418a-8c2f-5fb50248d67e.json
- src/test/resources/mockdata/compositeLines/c2755a78-2f8d-47d0-a218-059a9b7391b4.json
- src/test/resources/mockdata/compositeLines/fca5fa9e-15cb-4a3d-ab09-eeea99b97a47.json
- src/test/resources/po_listed_print_monograph.json
- src/test/resources/po_listed_print_serial.json
The module needs to be updated to use the latest acquisitions schema in order to be able to proceed with implementation of new features.
- update acq-models submodule to point to the latest commit
- update mock data to be consistent with the new schema
- move mock data to test resources and remove all the samples which are not used in tests
> Modorders 70 orders schema updates

- src/main/java/org/folio/rest/impl/PostOrderLineHelper.java
- src/test/java/org/folio/rest/impl/OrdersImplTest.java
Calling POST /orders with an open purchase order (single POL for something that didn't exist in inventory) we currently get a 422:
```
{
"errors" : [ {
"message" : "{\"errors\":[{\"message\":\"must match \\\"^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$\\\"\",\"type\":\"1\",\"code\":\"-1\",\"parameters\":[{\"key\":\"instanceId\",\"value\":\"/88f80ba8-7d68-4c0f-a7bd-c820123065c9\"}]}]}",
"parameters" : [ ]
} ]
}
```
However, it appears the instance is created. Repeating the exact same call yields a 201 created. As expected, a duplicate instance is NOT created.
The problem is that there's a leading '/' in the instanceId value (from the error message). This would cause the UUID regex pattern check to fail.
See recent comments in …
> MODORDERS-69 fix how location header is parsed and unit test

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- ramls/order.raml
- src/main/java/org/folio/orders/utils/HelperUtils.java
- src/main/java/org/folio/rest/impl/GetOrdersByIdHelper.java
- src/main/java/org/folio/rest/impl/OrdersImpl.java
- src/main/java/org/folio/rest/impl/ValidationHelper.java
- src/test/java/org/folio/rest/impl/OrdersImplTest.java
https://issues.folio.org/browse/MODORDERS-89
Adding a new end point to validate a PO Number to ensure a user entered PO Number is unique and matches the pattern 5-16 alphanumeric characters
Using the RMB specified @validate annotation to ensure it follows the pattern specified in the acq models
A call to the /orders-storage/purchase-orders endpoint to check if the entered PO number is distinct.
> Modorders 89- /orders/po_number/validate endpoint

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
See [MODORDERS-131](https://issues.folio.org/browse/MODORDERS-131)
Changes required for release 2.0.0
See https://dev.folio.org/guidelines/release-procedures/#maven-based-modules for release procedure documentation
> MODORDERS-131 - Release 2.0.0

- NEWS.md
- pom.xml
- ramls/order.raml
See [MODORDERS-131](https://issues.folio.org/browse/MODORDERS-131)
This is a follow-on release to fix the RAML so that the API version is consistent with that specified in the module descriptor.
Push button, turn crank, voila! New and improved.
> MODORDERS-131 - Release 2.0.1

- descriptors/ModuleDescriptor-template.json
The purpose is to fix a bug related to not provided endpoint `GET /orders/composite-orders` by module
Adding GET /orders/composite-orders to module descriptor, adding required permissions for the endpoint
> MODORDERS-124 GET orders collection bug

- descriptors/ModuleDescriptor-template.json
- ramls/order.raml
Increment order interface according to new implemented features
Upgrade order interface to v3.0 after temporary downgrade https://github.com/folio-org/mod-orders/pull/71
Should be merged together with
* https://github.com/folio-org/mod-gobi/pull/36
* https://github.com/folio-org/ui-orders/pull/174
> MODORDERS-124 - orders interface upgrade to v3.0

- src/main/java/org/folio/rest/impl/GetOrdersHelper.java
- src/test/java/org/folio/rest/impl/OrdersImplTest.java
[MODORDERS-126](https://issues.folio.org/browse/MODORDERS-126): Fixing case when query parameter is not provided or empty. This resulted to `QueryValidationException` on the storage side
Do not pass `query` parameter to storage if it is empty in the `/orders/composite-orders` request
> MODORDERS-126 Implement GET orders by query endpoint

- src/main/java/org/folio/rest/impl/InventoryHelper.java
- src/main/java/org/folio/rest/impl/PutOrderLineByIdHelper.java
- src/test/java/org/folio/rest/impl/OrdersImplTest.java
since `po_line.source` and `instance.source` are not the same thing, we should set `instance.source` to hardcoded value `FOLIO` instead of mapping it from `po_line.source`
Change "update inventory" logic in PutOrderLineByIdHelper to populate Instance Record source with hardcoded value.
> MODORDERS-145 Unable to create new Purchase Order with PO Line

- src/main/java/org/folio/rest/impl/PutOrdersByIdHelper.java
- src/test/java/org/folio/rest/impl/OrdersImplTest.java
- src/test/resources/README
- src/test/resources/mockdata/compositeOrders/41d56e59-46db-4d5e-a1ad-a178228913e5.json
[MODORDERS-150](https://issues.folio.org/browse/MODORDERS-150) - handling the case when the order's workflow status is not set in the storage.
- The main issue resolved by [MODORDERS-145](https://issues.folio.org/browse/MODORDERS-145) where latest acq-models schemas added and default value for `workflow_status` set to `Pending` for composite purchase order. In this case if UI does not send workflow status for order, the default one will be always used.
- The second case when some 3rd party service sends requests directly to storage endpoints. In this case there is potentially might happen that workflow status is not defined. Using `Pending` as a default one in the business logic.
- Adding unit test to verify this case
> Modorders 150 edit po withot status

- PULL_REQUEST_TEMPLATE.md
In order to reduce the chance of breaking the nightly folio-testing build by merging breaking changes to master, we need to be more careful and consider the wider impact of the merge.
Add a pre-merge checklist to the PR template.  Ideally the assignee of the PR will quickly go through the checklist before merging.
> Add pre-merge checklist to PR template

- descriptors/ModuleDescriptor-template.json
- ramls/order.raml
- src/main/java/org/folio/orders/utils/HelperUtils.java
- src/main/java/org/folio/orders/utils/ResourcePathResolver.java
- src/main/java/org/folio/rest/impl/AbstractHelper.java
- src/main/java/org/folio/rest/impl/GetOrdersByIdHelper.java
- src/main/java/org/folio/rest/impl/GetPOLineByIdHelper.java
- src/main/java/org/folio/rest/impl/GetPOLinesHelper.java
- src/main/java/org/folio/rest/impl/InventoryHelper.java
- src/main/java/org/folio/rest/impl/OrdersImpl.java
- src/main/java/org/folio/rest/impl/PostOrderLineHelper.java
- src/main/java/org/folio/rest/impl/PostOrdersHelper.java
- src/main/java/org/folio/rest/impl/PutOrderLineByIdHelper.java
- src/main/java/org/folio/rest/impl/PutOrdersByIdHelper.java
- src/test/java/org/folio/rest/impl/OrdersImplTest.java
- src/test/resources/minimal_order.json
- src/test/resources/mockdata/compositeOrders/07f65192-44a4-483d-97aa-b137bbd96390.json
- src/test/resources/mockdata/compositeOrders/1ab7ef6a-d1d4-4a4f-90a2-882aed18af14.json
- src/test/resources/mockdata/compositeOrders/bad500aa-aaaa-500a-aaaa-aaaaaaaaaaaa.json
- src/test/resources/mockdata/compositeOrders/e5ae4afd-3fa9-494e-a972-f541df9b877e.json
- src/test/resources/mockdata/compositeOrders/getOrders.json
- src/test/resources/mockdata/lines/po_line_collection.json
- src/test/resources/po_creation_failure.json
- src/test/resources/po_line_creation_failure.json
- src/test/resources/po_listed_electronic_monograph.json
- src/test/resources/po_listed_print_monograph.json
- src/test/resources/po_listed_print_serial.json
- src/test/resources/put_order_with_mismatch_id_in_po_lines.json
- src/test/resources/put_order_with_po_lines.json
https://issues.folio.org/browse/MODORDERS-142
The purpose is to implement endpoint GET /orders/order-lines endpoint
* Resolving naming collisions after merging https://github.com/folio-org/acq-models/pull/48
* Implementing GET /orders/order-lines endpoint
* Unit test updates
Firstly https://github.com/folio-org/acq-models/pull/48 should be merged
Once this is done the following modules have to be updated to consume schema change:
* mod-orders (by current PR)
* UI orders app
* mod-gobi https://github.com/folio-org/mod-gobi/pull/41
> MODORDERS-142 GET /orders/order-lines

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/rest/impl/InventoryHelper.java
- src/main/java/org/folio/rest/impl/PutOrderLineByIdHelper.java
- src/test/java/org/folio/rest/impl/OrdersImplTest.java
[MODORDERS-149](https://issues.folio.org/browse/MODORDERS-149) Add PO Line identifier to item record
The https://github.com/folio-org/mod-inventory-storage/pull/240 has been already merged and updated inventory storage is already available in testing
- populating `purchaseOrderLineIdentifier` item's property
- required Inventory module permissions added to module descriptor
- update `item-storage`'s interface version to 7.2
- in case number of items created less than expected, create piece records for successfully created items and return exception after this
- Does this PR meet or exceed the expected quality standards ([sonar PR#97](https://sonarcloud.io/project/issues?id=org.folio%3Amod-orders&pull …
>  MODORDERS-149 Add PO Line identifier to item record

- src/main/java/org/folio/orders/rest/exceptions/HttpException.java
- src/main/java/org/folio/rest/impl/AbstractHelper.java
Error code is absent in error response in case of handling HttpException.
(example: POST purchase order with the existing `po_number`)
* adding error code for error response mapping
* adding default error code for other exceptions
> MODORDERS-146 error code is absent in error message (BUG)

- src/main/java/org/folio/orders/utils/HelperUtils.java
- src/main/java/org/folio/rest/impl/PutOrderLineByIdHelper.java
- src/test/java/org/folio/rest/impl/OrdersImplTest.java
- src/test/resources/po_listed_print_monograph_pe_mix.json
https://issues.folio.org/browse/MODORDERS-100
- Create piece records, even if not creating item records
- Calculate total quantity using `compPOL.getCost().getQuantityPhysical()` and `compPOL.getCost().getQuantityElectronic()`
- Subtract inventory items from total quantity to create remaining pieces
- Update tests
Extra:
Update `dateOrdered` tests to verify against month and year to avoid time zone issues
- Are the JIRAs under …
> Create pieces when item record does not exists

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
[MODORDERS-161](https://issues.folio.org/browse/MODORDERS-161) Create release v3.0.0
- The required orders storage interface version dependencies are updated
- News file is updates for v3.0.0
> Release 3.0.0

- README.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/java/org/folio/orders/utils/ErrorCodes.java
- src/main/java/org/folio/orders/utils/HelperUtils.java
- src/main/java/org/folio/rest/impl/InventoryHelper.java
- src/main/java/org/folio/rest/impl/OrdersImpl.java
- src/main/java/org/folio/rest/impl/PutOrderLineByIdHelper.java
- src/main/java/org/folio/rest/impl/ReceivingHelper.java
- src/test/java/org/folio/rest/impl/OrdersImplTest.java
- src/test/resources/mockdata/compositeLines/2bafc9e1-9dd3-4ede-9f23-c4a03f8bb2d5.json
- src/test/resources/mockdata/itemsRecords/inventoryItemsCollection.json
- src/test/resources/mockdata/lines/po_line_collection.json
- src/test/resources/mockdata/pieces/pieceRecords-0dd8f1d2-ac2e-4155-a407-72071f6d5f4a.json
- src/test/resources/mockdata/pieces/pieceRecords-daa9cfd1-b330-4b65-8c2a-3663aaae5130.json
- src/test/resources/mockdata/pieces/pieceRecordsCollection.json
- src/test/resources/mockdata/receiving/receive-500-error-for-items-lookup.json
- src/test/resources/mockdata/receiving/receive-500-error-for-pieces-lookup.json
- src/test/resources/mockdata/receiving/receive-electronic-5-of-10-resources-no-items.json
- src/test/resources/mockdata/receiving/receive-physical-all-resources.json
- src/test/resources/mockdata/receiving/receive-physical-resources-6-of-10-with-errors.json
- src/test/resources/mockdata/receivingHistory/receivingHistory.json
- src/test/resources/po_one_physical_one_electronic_lines.json
[MODORDERS-103](https://issues.folio.org/browse/MODORDERS-103) Implement receiving flow for physical resources
[MODORDERS-162](https://issues.folio.org/browse/MODORDERS-162) Implement receiving flow for electronic resources
Upon receiving a request to receive resources, it does the following:
* Retrieve piece records from the orders storage based on the [request body](https://github.com/folio-org/acq-models/blob/master/mod-orders/schemas/receivingCollection.json).
* For those pieces which have item id the process is like following:
* Retrieve items from inventory.
* Update item entities with barcode (if specified) and status
* Send PUT requests to inventory to update items. In case any errors happen while updating items, the logic just collects them and does not stop entire process
* …
> MODORDERS-103/162 receiving flow for physical and electronic resources

- src/test/java/org/folio/rest/impl/OrdersImplTest.java
- src/test/resources/mockdata/receivingHistory/receivingHistory.json
[MODORDERS-171](https://issues.folio.org/browse/MODORDERS-171) The GET /orders/receiving-history endpoint needs to be enhanced to return additional data required for [UIREC-16](https://issues.folio.org/browse/UIREC-16) and [UIREC-20](https://issues.folio.org/browse/UIREC-20):
- PO Line's receipt status
- PO Line's order format
- updated ramls/acq-models submodule
- unit tests updated
- …
> Modorders 171 receieving history additional data for receiving flow

- README.md
- ramls/order.raml
- src/main/java/org/folio/rest/impl/InventoryHelper.java
- src/main/java/org/folio/rest/impl/ReceivingHelper.java
- src/test/java/org/folio/rest/impl/OrdersImplTest.java
- src/test/resources/mockdata/itemsRecords/inventoryItemsCollection.json
- src/test/resources/mockdata/lines/po_line_collection.json
- src/test/resources/mockdata/pieces/pieceRecords-cf447221-29b9-481e-947c-9ad545f22888.json
- src/test/resources/mockdata/pieces/pieceRecords-f217a5c2-2c56-4d05-9412-a96cfc8e52de.json
- src/test/resources/mockdata/pieces/pieceRecords-fe47e95d-24e9-4a9a-9dc0-bcba64b51f56.json
- src/test/resources/mockdata/pieces/pieceRecordsCollection.json
- src/test/resources/mockdata/receiving/revert-electronic-1-of-1-resource.json
- src/test/resources/mockdata/receiving/revert-pe-mix-4-of-5-resources.json
[MODORDERS-175](https://issues.folio.org/browse/MODORDERS-175) Add ability to move a received piece back to "Expected"
The logic extends functionality implemented in scope of PR #107:
* client sends request like following:
```json
{
"toBeReceived": [
{
"poLineId": "f217a5c2-2c56-4d05-9412-a96cfc8e52de",
"received": 2,
"receivedItems": [
{
"itemStatus": "On order",
"pieceId": "56fbfde4-6335-4dd7-9a03-d100821f1d18"
},
{
"itemStatus": "On order",
"pieceId": "a6ff14ad-8a65-57f9-bb89-f4654a3923fb"
}
]
}
],
"totalRecords": 2
}
```
* retrieve piece records
* for those piece records which have an item id reference, retrieve items from inventory storage
* ~~remove item's barcode~~ the item's barcode remains as is
* update item's status to `On order`
* update item record in inventory
* update each …
> MODORDERS-175 Add ability to move a received piece back to "Expected"

- pom.xml
- src/main/java/org/folio/orders/rest/exceptions/HttpException.java
- src/main/java/org/folio/orders/utils/ErrorCodes.java
- src/main/java/org/folio/orders/utils/HelperUtils.java
- src/main/java/org/folio/rest/impl/OrdersImpl.java
- src/main/java/org/folio/rest/impl/VendorHelper.java
- src/test/java/org/folio/rest/impl/OrdersImplTest.java
- src/test/resources/mockdata/compositeOrders/bad500aa-aaaa-500a-aaaa-aaaaaaaaaaaa.json
- src/test/resources/mockdata/vendors/active_inactive_access_providers.json
- src/test/resources/mockdata/vendors/active_vendor.json
- src/test/resources/mockdata/vendors/all_access_providers_active.json
- src/test/resources/mockdata/vendors/all_access_providers_not_found.json
- src/test/resources/mockdata/vendors/all_inactive_access_providers.json
- src/test/resources/mockdata/vendors/inactive_vendor.json
- src/test/resources/mockdata/vendors/one_access_provider_not_found.json
- src/test/resources/mockdata/vendors/pending_vendor.json
- src/test/resources/po_listed_print_monograph.json
[MODORDERS-170](https://issues.folio.org/browse/MODORDERS-170) - Prevent ordering from Inactive vendors/access provider
To keep users from ordering from inappropriate Vendors/Access Providers
In the case of an inactive or non-existent vendor/access provider during purchase order creation/updating client will receive a response containing the corresponding errors with vendor's id as an additional parameter.
1. **folio-api-tests** (as a result of vendor's id generation each time …
> MODORDERS-170 - Prevent ordering from Inactive vendors/access provider

- src/main/java/org/folio/rest/impl/PurchaseOrderHelper.java
- src/test/java/org/folio/rest/impl/OrdersImplTest.java
- src/test/resources/mockdata/compositeOrders/11111111-dddd-4444-9999-ffffffffffff.json
[MODORDERS-193](https://issues.folio.org/browse/MODORDERS-193) totalItems should be calculated and returned from mod-orders when an order is retrieved.
- added calculation totalItems quantity on purchaseOrder retrieval
- tests updated to check totalItems quantity
> MODORDERS-193 Sum total quantity on PO retrieval

- src/main/java/org/folio/orders/utils/HelperUtils.java
- src/test/java/org/folio/rest/impl/OrdersImplTest.java
[MODORDERS-197](https://issues.folio.org/browse/MODORDERS-197) Allow 0.0 for unit price in Cost for Orders
Update validation to allow zero prices and verify that discount amount does not exceed total estimated price
> MODORDERS-197 Allow 0.0 for unit price in Cost for Orders

- src/main/java/org/folio/rest/impl/PurchaseOrderHelper.java
- src/main/java/org/folio/rest/impl/VendorHelper.java
- src/test/java/org/folio/rest/impl/OrdersImplTest.java
[MODORDERS-199](https://issues.folio.org/browse/MODORDERS-199) - VendorHelper refactoring in accordance with the general helpers structure
Refactoring of an existing VendorHelper from PR [#111](https://github.com/folio-org/mod-orders/pull/111) in accordance with the general helper structure implemented in scope of [MODORDERS-141](https://issues.folio.org/browse/MODORDERS-141) .
Implemented inheritance of the VendorHelper from the AbstractHelper.
PR [#120](https://github.com/folio-org/mod-orders/pull/120) should be closed as duplicated.
> MODORDERS-199 - VendorHelper refactoring in accordance with the general helpers structure

- src/main/java/org/folio/orders/utils/HelperUtils.java
- src/main/java/org/folio/rest/impl/PurchaseOrderHelper.java
- src/test/java/org/folio/rest/impl/OrdersImplTest.java
[MODORDERS-201](https://issues.folio.org/browse/MODORDERS-201) Incorrect PO total estimated cost in some cases
Replacing sum of regular `double` values by operation with `BigDecimal`
[Why You Should Never Use Float and Double for Monetary Calculations](https://dzone.com/articles/never-use-float-and-double-for-monetary-calculatio)
> MODORDERS-201 correct PO total estimated cost calculation

- src/main/java/org/folio/orders/utils/ErrorCodes.java
- src/main/java/org/folio/orders/utils/HelperUtils.java
- src/main/java/org/folio/rest/impl/InventoryHelper.java
- src/main/java/org/folio/rest/impl/PurchaseOrderLineHelper.java
- src/test/java/org/folio/rest/impl/OrdersImplTest.java
- src/test/resources/mockdata/pieces/pieceRecord.json
- src/test/resources/mockdata/receivingHistory/receivingHistory.json
[MODORDERS-194](https://issues.folio.org/browse/MODORDERS-194) Adjustments to piece and receiving-history regarding piece vs order type
- Build piece record of corresponding format on item creation in InventoryHelper
- Build piece record of corresponding format without linked item in PurchaseOrderLineHelper
- Updating unit tests to verify piece format
- Does this PR meet or exceed the expected quality standards ([sonar PR#131](https://sonarcloud.io/dashboard?id=org.folio%3Amod-orders&pullRequest=131))?
- Do JIRAs exist to update the …
> MODORDERS-194 Piece and receiving-history: piece format

- src/main/java/org/folio/rest/impl/PurchaseOrderLineHelper.java
- src/test/resources/mockdata/configurations.entries/test_diku_limit_10.json
https://issues.folio.org/browse/MODORDERS-179
During reviewing the story a bug was found. Json configuration values are stored as strings that need to be parsed.
* changing the code to get configuration values as strings instead of JsonObject.
> MODORDERS-179 Json config parsing bug

- descriptors/ModuleDescriptor-template.json
https://issues.folio.org/browse/MODORDERS-206 - Add missing permission to access purchase order collection
Add orders-storage.purchase-orders.collection.get to POST /orders/composite-orders
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if …
> MODORDERS-206-adding purchase Order Collection permission

- src/main/java/org/folio/rest/impl/PurchaseOrderLineHelper.java
- src/test/java/org/folio/rest/impl/OrdersImplTest.java
https://issues.folio.org/browse/MODORDERS-209
Bugfix needed for the case of order creation with `poLine.physical.createInventory/poLine.eresource.createInventory` not specified in the order and the tenant-specific settings are empty.
* fixing future completion, adding unit test to cover this piece of code
> MODORDERS-209 fix for the hanging orders bug

- src/main/java/org/folio/orders/utils/ResourcePathResolver.java
- src/main/java/org/folio/rest/impl/PurchaseOrderHelper.java
- src/test/java/org/folio/rest/impl/OrdersImplTest.java
[MODORDERS-211](https://issues.folio.org/browse/MODORDERS-211) POL paymentStatus should be updated when opening an order
When order is opened, paymentStatus of POLs transitions as follows:
- if "Pending" -> "Awaiting Payment"
- If not "Pending", leave as-is.
> MODORDERS-211  Order Status: Align POL Payment and Receipt status with PO Status when opening order

- src/main/java/org/folio/orders/utils/ErrorCodes.java
- src/main/java/org/folio/rest/impl/CheckinHelper.java
- src/main/java/org/folio/rest/impl/CheckinReceivePiecesHelper.java
- src/main/java/org/folio/rest/impl/ReceivingHelper.java
- src/test/java/org/folio/rest/impl/OrdersImplTest.java
- src/test/resources/mockdata/pieces/pieceRecordsCollection.json
[MODORDERS-210](https://issues.folio.org/browse/MODORDERS-210) - Make locationId as not required in Check-in flow
After removing locationId from required fields [PR#114](https://github.com/folio-org/acq-models/pull/114) one need to validate that locationId is provided when createInventory is set to "Instance, Holding" or "Instance, Holding, Item". If not, an appropriate error message & code are returned.
1. Logic for checking locationId presence implemented as part of checkin flow. If the conditions are not met, the corresponding error is added without finishing flow execution.
2. POLines added as  property of Receiving/Checkin helper because we need to retrieve this information several times during checkin flow execution.
3. Unit test implemented.
Before merging this PR, please go …
> MODORDERS-210 - Make locationId as not required in Check-in flow

- src/main/java/org/folio/rest/impl/PurchaseOrderHelper.java
- src/main/java/org/folio/rest/impl/PurchaseOrderLineHelper.java
- src/test/java/org/folio/rest/impl/PurchaseOrdersApiTest.java
- src/test/resources/mockdata/compositeOrders/9a952cd0-842b-4e71-bddd-014eb128dc8e.json
[MODORDERS-229](https://issues.folio.org/browse/MODORDERS-229) - Sort PO Lines array by POLNumber in composite PO GET by id response
To support default sorting in PO Lines list with minimal efforts.
Approach | Advantages | Disadvantages
-- | -- | --
Custom "comparator" in the PostgreSQL | "Native approach" | Hard implementation related to work on DB side
PoLineNumber format changing - adding zeroes at the begin of poLineNumber suffix |Simple implementation | This approach relates with additional difficulties in  the implementation of this approach, since it is necessary to provide  additional comparison logic and to process the string value for correct  displaying.
Comparator for suffix in mod-orders code | Simple implementation | Negative performance impact
Comparator for suffix in …
> MODORDERS-229 - Sort PO Lines array by POLNumber in composite PO GET by id response

- src/main/java/org/folio/orders/utils/ErrorCodes.java
- src/main/java/org/folio/rest/impl/InventoryHelper.java
- src/test/java/org/folio/rest/impl/ApiTestBase.java
- src/test/java/org/folio/rest/impl/MockServer.java
- src/test/java/org/folio/rest/impl/PurchaseOrdersApiTest.java
- src/test/resources/mockdata/instanceTypes/empty_instance_type.json
https://issues.folio.org/browse/MODORDERS-231
https://issues.folio.org/browse/MODORDERS-231 - throw proper error if instance-type is not present
1) throwing a new error with proper code and message for the UI to map easily …
> MODORDERS-231-fixing error message for instance type

- descriptors/ModuleDescriptor-template.json
[MODORDERS-244](https://issues.folio.org/browse/MODORDERS-244) - Missing module permission for getting contributor-name-types.
Fixing of missing module permission.
Permission inventory-storage.contributor-name-types.collection.get added to endpoints: POST /orders/composite-orders and PUT /orders/composite-orders/<id>.
> MODORDERS-244 - Missing module permission for getting contributor-name-types

- src/main/java/org/folio/rest/impl/PurchaseOrderHelper.java
- src/test/java/org/folio/rest/impl/PurchaseOrdersApiTest.java
[MODORDERS-234](https://issues.folio.org/browse/MODORDERS-234) The workflowStatus, closeReason  of the order from the response to POST request does not correspond to the persisted.
- return updated workflowStatus, closeReason 
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing …
> MODORDERS-234 Update PO status based on receipt/payment status

- descriptors/ModuleDescriptor-template.json
[MODORDERS-245](https://issues.folio.org/browse/MODORDERS-245) Update API tests to use a user account with limited permissions
- Adding missing permissions
- Replacing `orders-storage.*.all` by individual permissions (see [discussion in #development](https://folio-project.slack.com/archives/C210RP0T1/p1559047992010100?thread_ts=1559047980.010000&cid=C210RP0T1))
- Adding `configuration` interface as required because there are a lot functionality which relies on configs
> MODORDERS-245 Update module permissions

- descriptors/ModuleDescriptor-template.json
- ramls/acquisitions-units.raml
- src/main/java/org/folio/orders/utils/ResourcePathResolver.java
- src/main/java/org/folio/rest/impl/AcquisitionsUnitsHelper.java
- src/main/java/org/folio/rest/impl/AcquisitionsUnitsImpl.java
- src/test/java/org/folio/rest/impl/AcquisitionsUnitsTests.java
- src/test/java/org/folio/rest/impl/ApiTestSuite.java
- src/test/java/org/folio/rest/impl/MockServer.java
- src/test/resources/mockdata/acquisitionsUnits/units/units.json
[MODORDERS-249](https://issues.folio.org/browse/MODORDERS-249) Implement basic CRUD for /acquisitions-units/units
Define and implement the acquisitions-units API
- new interfrace: `acquisitions-units`
- Proxies to corresponding storage endpoint
> Modorders 249 acquisitions units

- descriptors/ModuleDescriptor-template.json
- ramls/acquisitions-units.raml
- src/main/java/org/folio/orders/utils/ResourcePathResolver.java
- src/main/java/org/folio/rest/impl/AcquisitionsMembershipsHelper.java
- src/main/java/org/folio/rest/impl/AcquisitionsUnitsImpl.java
- src/test/java/org/folio/rest/impl/AcquisitionsMembershipsTests.java
- src/test/java/org/folio/rest/impl/ApiTestSuite.java
- src/test/java/org/folio/rest/impl/MockServer.java
- src/test/resources/mockdata/acquisitionsUnits/units/memberships.json
[MODORDERS-250](https://issues.folio.org/browse/MODORDERS-250) - Implement basic CRUD for /acquisitions-units/memberships
Define and implement the acquisitions-unit memberships API
Memberships API implementation in accordance with https://docs.google.com/spreadsheets/d/1se-a2owRfHLG5eaAZglx4vLvRClCKGp2wZCfD39ZJRY/edit#gid=894044560
> MODORDERS-250 - Implement basic CRUD for /acquisitions-units/memberships

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/rest/impl/PurchaseOrderHelper.java
- src/main/java/org/folio/rest/impl/PurchaseOrderLineHelper.java
- src/main/java/org/folio/rest/impl/ReceivingHelper.java
[MODORDERS-256](https://issues.folio.org/browse/MODORDERS-256) Restrict search of PO and POL records and receiving history based upon acquisitions unit
Adding acquisitions units CQL expression in the beginning of the query to allow sorting criteria to be specified (this is to resolve UIOR-327)
- Adding acq units cql expression as first part of the query
- Adding acq units permissions
> MODORDERS-256 Restrict search/view of PO, POL, Piece records based upon acquisitions unit

- descriptors/ModuleDescriptor-template.json
- src/test/resources/mockdata/instances/instance.json
[MODORDERS-277](https://issues.folio.org/browse/MODORDERS-277) Update inventory interface version
- Updating `inventory` interface version including `9.0` along with `8.3` (there is no functionality which works with instance's notes)
- Removing unused `inventory-storage.instances.item.get` permission for order creation
- Updating mock instance removing notes
The changes verified locally by API tests
> MODORDERS-277 Update inventory interface version

- src/main/java/org/folio/rest/impl/InitAPIs.java
Some of the API tests for the poLine update fell with an error `protectedFieldChanging`, although the body of the request was fully consistent with what was stored in the storage. It turned out that `RestVerticle` uses a `ObjectMapper` with different serialization configs for Date serialization from that used by Vertx.
`org.folio.rest.tools.utils.ObjectMapperTool.MAPPER` сonverts the `Date` into  `String`
`io.vertx.core.json.Json.mapper` сonverts the `Date` to `long`
- applying `org.folio.rest.tools.utils.ObjectMapperTool.MAPPER` serialization and deserialization configs to `io.vertx.core.json.Json.mapper` in `InitAPI.init()` phase
API test run on folio-testing:
After the fix locally:
- Does this PR …
> MODORDERS-265 Restrict which fields can be edited once worflowStatus = Open

- src/main/java/org/folio/orders/utils/POLineProtectedFields.java
- src/main/java/org/folio/orders/utils/POProtectedFields.java
- src/main/java/org/folio/rest/impl/PurchaseOrderHelper.java
- src/test/java/org/folio/rest/impl/PurchaseOrdersApiTest.java
https://issues.folio.org/browse/MODORDERS-284
- Exclude "CLOSE REASON" while closing orders(Order status "OPEN" in storage, and incoming request is in "CLOSED")
- adding Physical.createInventory, from comments in https://issues.folio.org/browse/MODORDERS-265
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid …
> MODORDERS-284- closeReason is protected, unable to close Order

- NEWS.md
- pom.xml
This release includes fix from story [MODORDERS-284](https://issues.folio.org/browse/MODORDERS-284) - closeReason is protected, so unable to close Order.
> MODORDERS-279 - Release 7.0.1

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/rest/impl/PurchaseOrderHelper.java
- src/main/java/org/folio/rest/impl/PurchaseOrderLineHelper.java
- src/test/java/org/folio/rest/impl/ApiTestBase.java
- src/test/java/org/folio/rest/impl/MockServer.java
- src/test/java/org/folio/rest/impl/protection/LinesProtectionTest.java
- src/test/java/org/folio/rest/impl/protection/OrdersProtectionTest.java
- src/test/java/org/folio/rest/impl/protection/ProtectedEntityTestBase.java
[MODORDERS-256](https://issues.folio.org/browse/MODORDERS-256) Restrict search/view of PO, POL, Piece records based upon acquisitions unit
Restrict get order and order line by id operations.
Note: there is no endpoint to get piece by id.
> MODORDERS-256 Restrict view of PO and POL records based upon acquisitions unit

- src/main/java/org/folio/rest/impl/AcquisitionsUnitsHelper.java
- src/test/java/org/folio/rest/impl/AcquisitionsUnitsTests.java
- src/test/java/org/folio/rest/impl/MockServer.java
[MODORDERS-293](https://issues.folio.org/browse/MODORDERS-293) Acquisition units - soft delete
Updating `GET /acquisitions-units/units` logic:
- if query contains `isDeleted` key word, just send query as is to storage. 
- if not, add `isDeleted==false and <original query>`
> MODORDERS-293 GET units - handle soft "deleted" units

- README.md
- ramls/acquisitions-units.raml
- src/main/java/org/folio/orders/utils/ErrorCodes.java
- src/main/java/org/folio/orders/utils/HelperUtils.java
- src/main/java/org/folio/rest/impl/AcquisitionsUnitsHelper.java
- src/main/java/org/folio/rest/impl/ProtectionHelper.java
- src/main/java/org/folio/rest/impl/PurchaseOrderHelper.java
- src/test/java/org/folio/rest/impl/ApiTestBase.java
- src/test/java/org/folio/rest/impl/MockServer.java
- src/test/java/org/folio/rest/impl/protection/OrdersProtectionTest.java
- src/test/java/org/folio/rest/impl/protection/ProtectedEntityTestBase.java
[MODORDERS-294](https://issues.folio.org/browse/MODORDERS-294) Disallow "isDeleted" acq units to be assigned to orders
- On order creation: in case any acq units assigned, check first if all exist and have `isDeleted==false`
- On order update: in case any acq units assigned, check that all newly assigned acq units (comparing to what is in storage) exist and have `isDeleted==false`.
In both cases above on failure, the flow is terminated and an error is returned to client like following
```json
{
"message": "Acquisitions units assigned to order cannot be found",
"code": "orderAcqUnitsNotFound",
"acqUnitIds": [
"a968d9fe-1230-4c44-8e59-87cd462a06e4",
"eab71dbd-b14b-4cfb-9b1e-d6f450b5b00f"
]
}
```
- …
> MODORDERS-294 Disallow "isDeleted" acq units to be assigned to orders

- src/main/java/org/folio/orders/utils/ResourcePathResolver.java
In addition to PR [#217](https://github.com/folio-org/mod-orders/pull/217) fixing of typo in endpoint /orders-storage/order-templates.
> MODORDERS-302 - Create order-templates API (url typo fixing)

- descriptors/ModuleDescriptor-template.json
Enables ready default deployment.
Refer to [FOLIO-2235](https://issues.folio.org/browse/FOLIO-2235) and [documentation](https://dev.folio.org/guides/module-descriptor/#launchdescriptor-properties).
Review is not needed. This is a devops task: Doing similar for all modules.
> Add default LaunchDescriptor settings FOLIO-2235

- pom.xml
- src/main/java/org/folio/rest/impl/AbstractHelper.java
[MODORDERS-310](https://issues.folio.org/browse/MODORDERS-310) Use the new version of the schema with qualifier field
Updating the acq-models
> MODORDERS-310 Use the new version of the schema with qualifier field

- Dockerfile
- descriptors/ModuleDescriptor-template.json
Use new Alpine base docker image with more recent Java 8 (222) with +UseContainerSupport, and JAVA_OPTIONS MaxRAMPercentage to manage container memory.
See notes at [FOLIO-2358](https://issues.folio.org/browse/FOLIO-2358).
Not expecting an actual "review", but this requires an approval so that i can merge and proceed with the remaining steps.
> MODORDERS-339 FOLIO-2358 manage container memory

- src/main/java/org/folio/rest/impl/InventoryHelper.java
- src/test/java/org/folio/rest/impl/CheckinReceivingApiTest.java
- src/test/resources/mockdata/checkIn/checkin-pe-mix-2-physical-resources.json
- src/test/resources/mockdata/receiving/receive-physical-resources-6-of-10-with-errors.json
https://issues.folio.org/browse/MODORDERS-315
- Update checkinItem and recieveItem logic in inventoryHelper to set itemStatus as `"In process"` if it is empty
- Update and add unit tests
- Update test resource
- PR for schema changes - https://github.com/folio-org/acq-models/pull/211
Ideally all of the PRs involved in breaking changes would be merged in …
> MODORDERS-315: Default to In process for item status during receiving/checkin

- src/main/java/org/folio/orders/utils/HelperUtils.java
- src/test/java/org/folio/rest/impl/PurchaseOrdersApiTest.java
[MODORDERS-264](https://issues.folio.org/browse/MODORDERS-264) - Order creates instance when it's not supposed to
When creating an order line and indicating it should not create an instance, it creates an instance. …
> MODORDERS-264 - Order creates instance when it's not supposed to

- src/main/java/org/folio/orders/events/handlers/OrderStatus.java
- src/main/java/org/folio/rest/impl/PurchaseOrderHelper.java
- src/main/java/org/folio/rest/impl/VendorHelper.java
- src/test/java/org/folio/rest/impl/PurchaseOrdersApiTest.java
[Comment on MODORDERS-341](https://issues.folio.org/browse/MODORDERS-341?focusedCommentId=72597&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-72597)
**Updated description:**
PUT /orders/composite-orders (without compositePoLines)
- you should be able to update workflow status (this is what the UI currently does)
PUT /orders/composite-orders (with compositePoLines)
- the eventbus asynch processing will kick in and set the workflowStatus based on paymentStatus/receiptStatus
- We probably want to avoid triggering the asynch processing if workflowStatus is changed. See MODORDERS-369
_Whenever workflowStatus changes (Open/Closed), item statuses should be adjusted_
- if PUT /orders/composite-orders (without compositePoLines) then do not adjust …
> MODORDERS-341 Set item status to "Order closed"

- src/main/java/org/folio/orders/utils/HelperUtils.java
- src/main/java/org/folio/rest/impl/CheckinReceivePiecesHelper.java
- src/test/java/org/folio/rest/impl/CheckinReceivingApiTest.java
- src/test/java/org/folio/rest/impl/MockServer.java
[MODORDERS-360](https://issues.folio.org/browse/MODORDERS-360)  This functionality was added earlier with [MODORDERS-221](https://issues.folio.org/browse/MODORDERS-221).
But one case was missed: the two different settings for physical and electronic need to be honored on P/E mix orders
- updating logic of holding creation upon check-in to honor eresource.createInventory and physical.createInventory settings separately for physical and electronic pieces
- Do JIRAs exist to update …
> MODORDERS-360 Create holding when receiving a piece and location is changed

- src/main/java/org/folio/orders/utils/ErrorCodes.java
- src/main/java/org/folio/rest/impl/PiecesHelper.java
- src/test/java/org/folio/rest/impl/PieceApiTest.java
https://issues.folio.org/browse/MODORDERS-376
* Make field "Piece.receiptDate" optional
* delete validation business logic of "Piece.receiptDate" …
> [MODORDERS-376] - Make field "Piece.receiptDate" optional

- src/main/java/org/folio/orders/utils/ErrorCodes.java
- src/main/java/org/folio/rest/impl/PiecesHelper.java
- src/test/java/org/folio/rest/impl/PieceApiTest.java
https://issues.folio.org/browse/MODORDERS-376
* Make field "Piece.receiptDate" optional
* delete validation business logic of "Piece.receiptDate" …
> [MODORDERS-376] Make field "Piece.receiptDate" optional

- src/main/java/org/folio/orders/utils/ErrorCodes.java
- src/main/java/org/folio/rest/impl/CheckinReceivePiecesHelper.java
- src/test/java/org/folio/rest/impl/CheckinReceivingApiTest.java
[MODORDERS-383](https://issues.folio.org/browse/MODORDERS-383)
- do not fail check-in if item not found
- remove reference from piece to non-existent item upon check-in …
> MODORDERS-383 Can not receive piece when item has been deleted

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/orders/utils/ErrorCodes.java
- src/main/java/org/folio/rest/impl/TitlesHelper.java
- src/test/java/org/folio/rest/impl/TitlesApiTest.java
[MODORDERS-359](https://issues.folio.org/browse/MODORDERS-359)
There's a new requirement that we support the ability for a poLine to represent a single title, that's part of a package represented by another POL.
Upon title creation copy over information from POL -> Title for new fields poLineNumber, receivingNote and expectedReceiptDate
- Title population has been extended based on described business logic
- Tests has been updated …
> [MODORDERS-359] Support "title" and "package" order lines

- src/main/java/org/folio/helper/PurchaseOrderHelper.java
- src/main/java/org/folio/rest/impl/OrdersApi.java
https://issues.folio.org/browse/MODORDERS-429
ongoing.renewalDate comes in different format, so this field marked as changed and invalid by ProtectedFieldsHandler
* workaround for invalid date format from HttpClient …
> MODORDERS-429 workaround for invalid date format from HttpClient

- src/main/java/org/folio/helper/FinanceHelper.java
- src/main/java/org/folio/orders/utils/HelperUtils.java
- src/test/java/org/folio/helper/FinanceHelperTest.java
- src/test/resources/mockdata/configurations.entries/ordertest.json
[MODORDERS-435](https://issues.folio.org/browse/MODORDERS-435)
Send only relevant budgets for verification to the `checkEnoughMoneyInBudgets` method …
> MODORDERS-435 unable to open order that references Funds from different ledgers

- src/main/java/org/folio/helper/FinanceHelper.java
- src/main/java/org/folio/helper/PurchaseOrderHelper.java
- src/test/java/org/folio/helper/FinanceHelperTest.java
[MODORDERS-430](https://issues.folio.org/browse/MODORDERS-430)
User gets error response when clicks Unopen button for opened order with PO line without any fund distribution added.
Number of order transactions have to be greater than 0
Add additional checking of amount of pending encumbrances to avoid transaction creating when there are no encumbrances at all. 
- Do PRs exist for these …
> MODORDERS-430: Can't Unopen order - error response 2

- src/main/java/org/folio/helper/FinanceHelper.java
- src/main/java/org/folio/helper/PurchaseOrderHelper.java
- src/test/java/org/folio/helper/PurchaseOrderHelperTest.java
https://issues.folio.org/browse/MODORDERS-465
* fix array out of bounds error when retreived empty rollover collection …
> MODORDERS-456 Array out of bounds fix

- src/main/java/org/folio/helper/PurchaseOrderHelper.java
- src/main/java/org/folio/orders/utils/OrderStatusTransitionUtil.java
- src/test/java/org/folio/rest/impl/ApiTestBase.java
- src/test/java/org/folio/rest/impl/PurchaseOrdersApiTest.java
- src/test/resources/mockdata/compositeOrders/a1465131-ed35-4308-872c-d7cdf0afc5f7.json
[MODORDERS-391](https://issues.folio.org/browse/MODORDERS-391)
Release all encumbrances when order is closed
- Add logic to release all encumbrances after Close order
- Add test
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …
> MODORDERS-391 Release all encumbrances when order is closed

- src/main/java/org/folio/service/finance/BudgetRestrictionService.java
- src/test/java/org/folio/service/finance/BudgetRestrictionServiceTest.java
[MODORDERS-471](https://issues.folio.org/browse/MODORDERS-471)
- Updated BudgetRestrictionService to use totalFunding instead of allocated.
- Added a test in BudgetRestrictionServiceTest.
@folio-org/acquisitions …
> [MODORDERS-471] Allowable encumbrance restriction should be based on total funding

- descriptors/ModuleDescriptor-template.json
Resolves [MODORDERS-512](https://issues.folio.org/browse/MODORDERS-512).
There is a breaking change in `mod-circulaion` that will be merge soon. Modules that have a dependency on `circulation` interface need to be updated to support version `11.0`.
There are multiple PRs with `circulation` interface version update, they all should be merged on the same day. 
**DO NOT MERGE** this PR until then.
> MODORDERS-512 Update circulation interface version

- pom.xml
- src/main/java/org/folio/config/ApplicationConfig.java
- src/main/java/org/folio/helper/PurchaseOrderHelper.java
- src/main/java/org/folio/orders/events/handlers/AbstractOrderStatusHandler.java
- src/main/java/org/folio/service/finance/transaction/EncumbranceService.java
- src/main/java/org/folio/service/finance/transaction/OpenToPendingEncumbranceStrategy.java
- src/test/java/org/folio/orders/events/handlers/CheckInOrderStatusChangeChangeHandlerTest.java
- src/test/java/org/folio/orders/events/handlers/ReceiveOrderStatusChangeHandlerTest.java
- src/test/java/org/folio/service/finance/transaction/EncumbranceServiceTest.java
- src/test/java/org/folio/service/finance/transaction/OpenToPendingEncumbranceStrategyTest.java
https://issues.folio.org/browse/MODORDERS-542
* updated encumbrances processing to use only transactions from current fiscal year …
> MODORDERS-542 Unopen fails after a rollover for an order created in the previous year

- descriptors/ModuleDescriptor-template.json
[MODFISTO-244](https://issues.folio.org/browse/MODFISTO-244)
Added missing requires for finance.expense-classes to the descriptor.
acq-models was already updated by MODORDSTOR-240.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to …
> [MODFISTO-244] Added API for expense classes to descriptor requires

- src/main/java/org/folio/service/AcquisitionsUnitsService.java
- src/test/java/org/folio/rest/impl/PurchaseOrderLinesApiTest.java
[MODORDERS-610](https://issues.folio.org/browse/MODORDERS-610) - PoLine search querying non-existing poLine.acqUnitIds
- Added `tableAlias` to `NO_ACQ_UNIT_ASSIGNED_CQL`
- Fixed unit tests
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if …
> [MODORDERS-610] Fixed po line query using acqUnitIds

- src/main/java/org/folio/helper/CheckinReceivePiecesHelper.java
[MODORDERS-616](https://issues.folio.org/browse/MODORDERS-616) - New holdingId is not saved into piece when location is changed during receiving
When a piece is received with a new location, a new holding is created. When this happens, update the piece object to have the new holding id. Pieces are saved afterwards.
[MODORDERS-522](https://issues.folio.org/browse/MODORDERS-522) - Receiving API is confusing and implementation is redundant
It would be easier to check this change cannot have side effects with a better API.
- What …
> [MODORDERS-616] Make sure a piece has the latest holdingId when received

- src/main/java/org/folio/models/EncumbrancesProcessingHolder.java
- src/main/java/org/folio/service/finance/transaction/EncumbranceRelationsHoldersBuilder.java
- src/main/java/org/folio/service/finance/transaction/EncumbranceService.java
- src/main/java/org/folio/service/finance/transaction/EncumbrancesProcessingHolderBuilder.java
- src/main/java/org/folio/service/finance/transaction/PendingToPendingEncumbranceStrategy.java
[MODORDERS-626](https://issues.folio.org/browse/MODORDERS-626) - Can't reopen an order after changing the expense class
- Save the whole encumbrance relation holder for encumbrances to delete
- When creating a new holder for a transaction without a matching fund distribution, look if there is a fund distribution that has the reference to that transaction
- If the transaction is deleted (rather than replaced), remove the reference in the matching fund distribution
I thought of using the occasion to set the fiscal year id in buildToBeReleasedHolder, but realized this could break workflows for [code](https://github.com/folio-org/mod-orders/blob/1991c506cf109c1510b5ae895b7379765cb8287f/src/main/java/org/folio/service/finance/transaction/EncumbranceRelationsHoldersBuilder.java#L281) filtering …
> [MODORDERS-626] Delete the encumbrance reference when a transaction is deleted

- descriptors/ModuleDescriptor-template.json
Adapt the module to changed interface of mod-circulation from v12.0 to v13.0
Adapt ModuleDescriptor-template to circulation interface v13.0;
https://issues.folio.org/browse/MODORDERS-634
> MODORDERS-634 Support circulation interface v13

- src/main/java/org/folio/helper/CheckinHelper.java
- src/main/java/org/folio/helper/ReceivingHelper.java
- src/main/java/org/folio/service/inventory/InventoryManager.java
- src/main/java/org/folio/service/orders/flows/update/open/OpenCompositeOrderPieceService.java
- src/main/java/org/folio/service/pieces/flows/create/PieceCreateFlowInventoryManager.java
- src/main/java/org/folio/service/pieces/flows/update/PieceUpdateFlowInventoryManager.java
- src/test/java/org/folio/service/orders/flows/open/OpenCompositeOrderPieceServiceTest.java
- src/test/java/org/folio/service/pieces/flows/update/PieceUpdateFlowInventoryManagerTest.java
Fix an issue with fields of the piece are not populated when receiving/unreceiving
Piece and Item updated from receive and unreceive model …
> [MODORDERS-649] - Some fields of the piece are not populated when receiving/unreceiving

- src/main/java/org/folio/helper/PurchaseOrderHelper.java
- src/main/java/org/folio/orders/utils/HelperUtils.java
- src/test/java/org/folio/TestConstants.java
- src/test/java/org/folio/rest/impl/PurchaseOrdersApiTest.java
- src/test/resources/mockdata/compositeOrders/f56c70bc-8a31-4f56-b606-c6d8e597b7c1.json
[MODORDERS-636](https://issues.folio.org/browse/MODORDERS-636) - Update po lines when an order is closed with the "Cancelled" reason
- Update paymentStatus and receiptStatus for POLs when an order is closed with the "Cancelled" reason, with the exceptions given in the story.
- Changed `isCompletedPoLine()` to take into account the new values for paymentStatus and receiptStatus.
- Added a new unit test.
- Are the JIRAs under active …
> [MODORDERS-636] Update po lines when an order is closed as Cancelled

- Jenkinsfile
- README.md
The doApiLint facility replaces runLintRamlCop
https://dev.folio.org/guides/api-lint/
The doApiDoc facility replaces publishAPI
https://dev.folio.org/guides/api-doc/
The https://dev.folio.org/reference/api/#mod-orders section of API documentation will be automatically reconfigured:
https://dev.folio.org/reference/api/#explain-gather-config
Please fix the JSON errors, as described in the subsequent comment.
> MODORDERS-678 FOLIO-3231 Use new api-lint and api-doc CI facilities

- src/main/java/org/folio/helper/PurchaseOrderLineHelper.java
- src/main/java/org/folio/orders/utils/POLineFieldNames.java
- src/main/java/org/folio/orders/utils/POLineProtectedFieldsUtil.java
- src/test/java/org/folio/rest/impl/PurchaseOrderLinesApiTest.java
- src/test/java/org/folio/rest/impl/PurchaseOrdersApiTest.java
https://issues.folio.org/browse/MODORDERS-700
1. Static lists of protected fields created in the class instead of building in each request new one.
2. Logic to retrieve list of fields moved to utility class
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication …
> [MODORDERS-700] - Receive 'protected fields can’t be modified' error for eresource fields on PO line that is a Physical Resource

- src/main/java/org/folio/service/finance/transaction/EncumbranceService.java
- src/main/java/org/folio/service/finance/transaction/TransactionService.java
- src/main/java/org/folio/service/orders/OrderRolloverService.java
- src/main/java/org/folio/service/orders/ReEncumbranceHoldersBuilder.java
- src/main/java/org/folio/service/orders/TransactionsTotalFieldsPopulateService.java
- src/test/java/org/folio/service/finance/transaction/EncumbranceServiceTest.java
- src/test/java/org/folio/service/orders/OrderReEncumberServiceTest.java
- src/test/java/org/folio/service/orders/OrderRolloverServiceTest.java
- src/test/java/org/folio/service/orders/ReEncumbranceHoldersBuilderTest.java
- src/test/java/org/folio/service/orders/TransactionsTotalFieldsPopulateServiceTest.java
[MODORDERS-699](https://issues.folio.org/browse/MODORDERS-699) - Encumbrances are not deleted after deleting Cancelled order
- Delete all related encumbrances when an order or an order line is deleted, not just unreleased ones.
- Simplified the use of `getTransactions()`, as all calls were using `0, Integer.MAX_VALUE` and `TransactionCollection::getTransactions`. This is now returning a list of all matching transactions.
- Updated unit tests. No new unit test, but a new integration test is checking for the use case.
- What …
> [MODORDERS-699] Delete all encumbrances when an order or line is deleted

- NEWS.md
- pom.xml
https://issues.folio.org/browse/MODORDERS-701
- Add news updated for v 12.4.0 Morning Glory R2 2022 release
- Update release versions
> [MODORDERS-701]. Add news for v12.4.0 Morning Glory R2 2022 release

- src/main/java/org/folio/service/finance/transaction/EncumbranceService.java
- src/main/java/org/folio/service/orders/flows/update/reopen/ReOpenCompositeOrderManager.java
- src/test/java/org/folio/rest/impl/PurchaseOrdersApiTest.java
- src/test/java/org/folio/service/orders/flows/update/reopen/ReOpenCompositeOrderManagerTest.java
Needs to rollback Receipt and Payment statuses after transition order from Cancel to Open (Reopen Flow)
There is a logic in the mod-invoice which a responsible for updating POL statuses when invoice Approve or Paid.
Rollback statuses logic now implemented based on mod-invoice logic 
Still have tests which randomly fail and will be fixed in scope of https://issues.folio.org/browse/MODORDERS-728
Test failing is not related to ReOPen logic and related to Protected field validation  …
> [MODORDERS-714] - Fix issue with Receipt and Payment statuses when order is transited from Cancel to Open(ReOpen)

- src/main/java/org/folio/service/orders/lines/update/instance/WithHoldingOrderLineUpdateInstanceStrategy.java
- src/test/java/org/folio/service/orders/lines/update/instance/WithHoldingOrderLineUpdateInstanceStrategyTest.java
When in  PoLine receiving workflow set as Independent items is not updated.
- Replacing logic of checking need to update item when using patch method with holdingsOperation - find or replace. We should just compare current and new holdings.
[MODORDERS-730](https://issues.folio.org/browse/MODORDERS-730)
Ideally all of the PRs involved in breaking changes …
> [MODORDERS-730] Item not appearing under holdings after instance connection change

- src/main/java/org/folio/rest/impl/InitAPIs.java
- src/test/java/org/folio/di/DataImportTest.java
it is necessary to prevent the mod-orders module from subscription to Kafka events to avoid unused interaction with Kafka, since in the Nolana the module is not involved in the data-import process and data-import events handling.
[MODORDERS-778](https://issues.folio.org/browse/MODORDERS-778)
> MODORDERS-778 - Temporary disable data-import verticle deployment

- src/main/java/org/folio/service/finance/transaction/EncumbranceRelationsHoldersBuilder.java
[MODORDERS-833](https://issues.folio.org/browse/MODORDERS-833) - Negative encumbrance values appear for expense classes after rollover
Preserve the encumbrance status when it is `Released`. This prevents the issue when a piece is deleted after the invoice was approved or paid, and also keeps the `Released` status when an open is reopened after an invoice was approved. See the related [integration tests](https://github.com/folio-org/folio-integration-tests/pull/836).
- Do JIRAs …
> [MODORDERS-833] Preserve encumbrance status when released

- src/main/java/org/folio/service/caches/MappingParametersCache.java
- src/test/java/org/folio/di/CacheTest.java
Prevent returning of 10 first organizations by default if the limit is not defined in the request params
Set limit to 1000 for getting organization for MappingParametersCache
> Add limit for retrieving organizations

- .github/workflows/api-doc.yml
- .github/workflows/api-lint.yml
- .github/workflows/api-schema-lint.yml
- Jenkinsfile
- README.md
- ramls/order.raml
[FOLIO-3678](https://issues.folio.org/browse/FOLIO-3678)
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)
(instead of Jenkins-operated CI stages).
> FOLIO-3678 MODORDERS-854 Use GitHub Workflows api-lint and api-schema-lint and api-doc

- descriptors/ModuleDescriptor-template.json
DI fails because the mod-orders module restarts when importing a large file (500+ records).
After investigation, it has been established that the module needs more memory: 700Mb is not enough (import is not stable), after increasing memory to 1Gb import on 5k was completed.
Increase memory in module-descriptor to deploy on Snapshots
[MODORDERS-858](https://issues.folio.org/browse/MODORDERS-858)
> MODORDERS-858: Increase a memory to Snapshots

- src/main/java/org/folio/helper/PurchaseOrderHelper.java
- src/main/java/org/folio/orders/events/handlers/AbstractOrderStatusHandler.java
- src/main/java/org/folio/service/finance/transaction/EncumbranceService.java
[MODORDERS-859](https://issues.folio.org/browse/MODORDERS-859) - Encumbrances are not always released when an order is closed
Whenever an encumbrance orderStatus is changed to CLOSED, also make sure the encumbrance status is Released.
[Integration tests](https://github.com/folio-org/folio-integration-tests/pull/894)
- Did you modify code to call some …
> [MODORDERS-859] Release encumbrance when orderStatus is set to CLOSED

- src/main/java/org/folio/service/titles/TitlesService.java
[MODORDERS-862](https://issues.folio.org/browse/MODORDERS-862) - Issues with receiving Pieces
Fixed a bug when getting titles, limit should not be set to 15.
See [integration test](https://github.com/folio-org/folio-integration-tests/pull/903).
Ideally, all the PRs involved in breaking changes would …
> [MODORDERS-862] Fixed receiving more than 15 pieces

- src/main/java/org/folio/dao/PoLinesImportProgressDao.java
- src/main/java/org/folio/dao/PoLinesImportProgressDaoImpl.java
- src/main/java/org/folio/service/dataimport/PoLineImportProgressService.java
- src/main/java/org/folio/service/dataimport/PoLineImportProgressServiceImpl.java
- src/main/java/org/folio/service/dataimport/handlers/CreateOrderEventHandler.java
- src/main/java/org/folio/service/dataimport/handlers/OrderPostProcessingEventHandler.java
- src/test/java/org/folio/service/dataimport/handlers/OrderPostProcessingEventHandlerTest.java
to prevent attempts to open an order more than one time during import open order with multiple po lines which in turn causes  validation error in the mod-finance-storage
> "message" : "All expected transactions already processed",
* atomically increase po lines processing progress and check completion of all po lines processing before making decision for corresponding order opening
* update and add tests
[MODSOURCE-301](https://issues.folio.org/browse/MODSOURCE-301)
> MODORDERS-863 - Error after importing open orders for the second time

- src/main/java/org/folio/service/dataimport/handlers/CreateOrderEventHandler.java
- src/test/java/org/folio/service/dataimport/handlers/CreateOrderEventHandlerTest.java
to adjust po line "create inventory" field override based on action profiles and order format
* correct po line "create inventory" field override for open order to set appropriate value based on action profiles, despite the "None" value has been mapped or mapping for physical/electronic details section has not been set up
* add/change tests
[MODORDERS-860](https://issues.folio.org/browse/MODORDERS-860)
> MODORDERS-860 - Adjust POL "create inventory" field override

- src/main/java/org/folio/config/ApplicationConfig.java
- src/main/java/org/folio/service/finance/rollover/LedgerRolloverErrorService.java
- src/main/java/org/folio/service/finance/rollover/LedgerRolloverProgressService.java
- src/main/java/org/folio/service/finance/rollover/LedgerRolloverService.java
- src/main/java/org/folio/service/orders/OrderReEncumberService.java
- src/main/java/org/folio/service/orders/OrderRolloverService.java
- src/main/java/org/folio/service/orders/ReEncumbranceHoldersBuilder.java
- src/test/java/org/folio/ApiTestSuite.java
- src/test/java/org/folio/service/finance/rollover/LedgerRolloverErrorServiceTest.java
- src/test/java/org/folio/service/finance/rollover/LedgerRolloverProgressServiceTest.java
- src/test/java/org/folio/service/finance/rollover/LedgerRolloverServiceTest.java
- src/test/java/org/folio/service/orders/OrderReEncumberServiceTest.java
- src/test/java/org/folio/service/orders/OrderRolloverServiceTest.java
- src/test/java/org/folio/service/orders/ReEncumbranceHoldersBuilderTest.java
Need to rewrite orders rollover in an asynchronous way to avoid issues with socket conection timeout while processing rollover.
- Splitted rollover related services
- Added preparation to orders rollover
- Immediately response after rollover preparation and start orders rollover
- Added calculation overall rollover progress
[MODORDERS-865](https://issues.folio.org/browse/MODORDERS-865)
- …
> [MODORDERS-865] - Rewrite the orders rollover interaction in an asynchronous way

- src/main/java/org/folio/helper/PurchaseOrderHelper.java
- src/test/java/org/folio/rest/impl/PurchaseOrdersApiTest.java
[MODORDERS-514](https://issues.folio.org/browse/MODORDERS-514) - Closing a composite order can fail silently when lines are included
- As suggested in the ticket's description, simply checking if the order status has changed before trying to change it based on the lines. If the status has changed, do not call `changeOrderStatus()`.
- Fixed a unit test.
[Integration test](https://github.com/folio-org/folio-integration-tests/pull/915)
- Do JIRAs exist to update the impacted …
> [MODORDERS-514] Fixed closing a composite order

- src/main/java/org/folio/rest/core/exceptions/ErrorCodes.java
- src/main/java/org/folio/service/finance/transaction/EncumbranceRelationsHoldersBuilder.java
- src/test/java/org/folio/rest/impl/PurchaseOrderLinesApiTest.java
- src/test/java/org/folio/service/finance/transaction/EncumbranceRelationsHoldersBuilderTest.java
- src/test/java/org/folio/service/finance/transaction/PendingToOpenEncumbranceStrategyTest.java
- src/test/resources/mockdata/budgets/budgets.json
- src/test/resources/mockdata/funds/funds.json
- src/test/resources/po_listed_print_serial.json
[MODORDERS-879](https://issues.folio.org/browse/MODORDERS-879) - Prevent creating an order using 2 different fiscal years with clear error message
- Added the check and error message in the encumbrance relations holders builder.
- New unit test + updated existing unit tests (some were using multiple fiscal years!)
- See also: "Implementation Notes" in the ticket.
TODO: Some UI update will be needed.
Open question: we could probably support using multiple fiscal years, which might simplify implementation, but do we want to allow it ?
If there are breaking changes, please **STOP** and consider the …
> [MODORDERS-879] New error returned when using multiple fiscal years

- src/main/java/org/folio/helper/PurchaseOrderLineHelper.java
When saving same fund distribution with differente expense class id it was a cause of duplicating encumbrance id in fund distribution
- Updated check for comparing fund distribution from storage and request
[MODORDERS-894](https://issues.folio.org/browse/MODORDERS-894)
Ideally, all the PRs involved …
> [MODORDERS-894] - Adding fund distribution line in the POL breaks the order record. Can no longer open.

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/orders/utils/ResourcePathResolver.java
- src/main/java/org/folio/service/finance/LedgerService.java
The purpose of this pull request is to address the issue where the order fails to open, citing "Ledger not found for transaction," when a fund is assigned in a fund distribution on a POL (Purchase Order Line) while using an acquisition unit that restricts view in a library. The problem occurs when the acquisition unit is applied to the ledger only but not the fund. The pull request aims to modify the behavior so that the order can be opened successfully, even if the acquisition unit is not assigned to the user.
- Retrieve ledger from storage around bussines module
- Added module permission
[MODORDERS-914](https://issues.folio.org/browse/MODORDERS-914)
- Does this PR meet or exceed the expected …
> [MODORDERS-914] - User cannot open order when ledger has separate acquisition unit

- src/main/java/org/folio/service/dataimport/handlers/OrderPostProcessingEventHandler.java
- src/test/java/org/folio/service/dataimport/handlers/OrderPostProcessingEventHandlerTest.java
Populate locations and material type for POLs when multiple Holdings/Items were created
Populate multiple locations based on holdings locations and poLine location template with quantities, populate material type with the value from the first item 
Jira: https://issues.folio.org/browse/MODORDERS-881
> [MODORDERS-881] Populate locations and material type for POLs when multiple Holdings/Items were created

- src/main/java/org/folio/service/finance/rollover/LedgerRolloverService.java
If two types of Commit and Test rollovers were made in one fiscal year, a conflict occurs when saving them to the HashMap collection.
- Updated query with new field **rolloverType** when fetching fy ledger rollovers 
[MODORDERS-920](https://issues.folio.org/browse/MODORDERS-920)
Ideally, all the PRs …
> [MODORDERS-920] - An error appears after rollover when open order/order line having two fund distributions related to different ledgers

- src/main/java/org/folio/rest/core/exceptions/ErrorCodes.java
- src/main/java/org/folio/service/orders/OrderReEncumberService.java
- src/test/java/org/folio/service/orders/OrderReEncumberServiceTest.java
We are trying to operate with encumbrance which doesn't exists in [the current line](https://github.com/folio-org/mod-orders/blob/358e9124124226df08b0b2cf060bca0b44ae9c46/src/main/java/org/folio/service/orders/OrderReEncumberService.java#L238). It leads us to NPE.
- Added filter to remove from collection holders which has no previous fy encumbrances
- Throwing exception when re encumber holders collection is empty
[MODORDERS-915](https://issues.folio.org/browse/MODORDERS-915)
- …
> [MODORDERS-915] - NPE in OrderReEncumberService.java:245

- src/main/java/org/folio/helper/CheckinHelper.java
- src/main/java/org/folio/service/inventory/InventoryManager.java
In [ui-receiving](https://github.com/folio-org/ui-receiving) the accession number field needs to be included in the “receive all view” table. Changes made to the accession number during receive need to be persisted in the item record.
See https://issues.folio.org/browse/UIREC-285 for more details.
See also [PR#462 in ui-receiving](https://github.com/folio-org/ui-receiving/pull/462).
- Do …
> UIREC-285 Update itemRecord with accessionNumber during checkin

- descriptors/ModuleDescriptor-template.json
This PR updates `acq-models` to include the `customFields` attribute to purchase orders and purchase order lines. This is part of the custom fields integration. See [MODORDERS-964](https://issues.folio.org/browse/MODORDERS-964).
* [MODORDSTOR PR#374](https://github.com/folio-org/mod-orders-storage/pull/374)
* [MODGOBI PR#220](https://github.com/folio-org/mod-gobi/pull/220)
* [MODINVOICE PR#460](https://github.com/folio-org/mod-invoice/pull/460)
* [MODINVOSTO PR#167](https://github.com/folio-org/mod-invoice-storage/pull/167)
> [MODORDERS-964] Update acq-models

- descriptors/ModuleDescriptor-template.json
Add missed module permissions for https://issues.folio.org/browse/MODORDERS-972
> [MODORDERS-972] - Protect Title acq units management with permissions

- src/main/java/org/folio/orders/utils/HelperUtils.java
- src/main/java/org/folio/service/inventory/InventoryManager.java
- src/main/java/org/folio/service/pieces/flows/update/PieceUpdateFlowInventoryManager.java
- src/test/java/org/folio/service/inventory/InventoryManagerTest.java
https://issues.folio.org/browse/MODORDERS-970 …
> Modorders 970

- src/main/java/org/folio/helper/CheckinReceivePiecesHelper.java
[MODORDERS-989](https://issues.folio.org/browse/MODORDERS-989) …
> [MODORDERS-989] - Placeholder - abiblity to move piece from Unrecivable into Expected

- descriptors/ModuleDescriptor-template.json
- ramls/expect.raml
- src/main/java/org/folio/helper/ExpectHelper.java
- src/main/java/org/folio/rest/impl/ReceivingAPI.java
- src/test/java/org/folio/TestConstants.java
- src/test/java/org/folio/rest/impl/CheckinReceivingApiTest.java
> [MODORDERS-989] - Implement batch endpoint to move multiple pieces to Expected status

- src/main/java/org/folio/service/orders/OrderRolloverService.java
- src/test/java/org/folio/service/orders/OrderRolloverServiceTest.java
Conversion didn't apply rounding and led issue with not rounded poLineEstimatedPrice after rollover when primary tenant currency differs from POL currency
- Added default rounding
- Removed setScale from tests. Tests should display real state of returning value without applying any scaling. For example before without scalling tests work as screenshot bellow:
[MODORDERS-991](https://issues.folio.org/browse/MODORDERS-991)
- Are the …
> [MODORDERS-989] - Rounding for the total estimated price of the order line does not work after the rollover

- src/main/java/org/folio/helper/CheckinHelper.java
- src/main/java/org/folio/helper/CheckinReceivePiecesHelper.java
- src/main/java/org/folio/helper/ExpectHelper.java
- src/main/java/org/folio/helper/ReceivingHelper.java
- src/main/java/org/folio/service/pieces/PieceStorageService.java
- src/main/java/org/folio/service/titles/TitlesService.java
- src/test/java/org/folio/helper/CheckinHelperTest.java
- src/test/java/org/folio/rest/impl/CheckinReceivingApiTest.java
- src/test/java/org/folio/rest/impl/MockServer.java
- src/test/java/org/folio/rest/impl/protection/ReceivingCheckinProtectionTest.java
- src/test/resources/mockdata/pieces/pieceRecordsCollection.json
The receiving app objects inherit an acquisition unit from the related POL. Meaning the unit can not be different from ordering to receiving. Some libraries will require these permissions to be separated.
- Retrieve titles and check their acq-units when receiving, checking-in and expecting
[MODORDERS-1005](https://issues.folio.org/browse/MODORDERS-1005)
- …
> [MODORDERS-1005] - Check acq units from Title when receiving/unreceicing pieces

- descriptors/ModuleDescriptor-template.json
https://folio-org.atlassian.net/browse/MODORDERS-1005
Calls to retrieve PO lines and orders were deleted in scope of https://github.com/folio-org/mod-orders/pull/832 , so these permissions are not needed any more
> MODORDERS-989. Remove unused module permissions

- src/main/java/org/folio/service/finance/transaction/TransactionService.java
[MODORDERS-892](https://folio-org.atlassian.net/browse/MODORDERS-892) - Accumulate all transactions in holder to make only single call to mod-finance
In the previous [PR](https://github.com/folio-org/mod-orders/pull/833) I forgot to filter encumbrances to release before deleting encumbrances related to a po line or po. It doesn't have much of an impact, but it is better to avoid updating transactions for nothing. This is just a fix for that.
- Do JIRAs exist to update the …
> [MODORDERS-892] Update only encumbrances to release

- src/main/java/org/folio/config/ApplicationConfig.java
- src/main/java/org/folio/service/orders/flows/update/open/OpenCompositeOrderManager.java
- src/main/java/org/folio/service/orders/flows/update/unopen/UnOpenCompositeOrderManager.java
- src/test/java/org/folio/service/orders/flows/update/open/OpenCompositeOrderManagerTest.java
[MODORDERS-1049](https://folio-org.atlassian.net/browse/MODORDERS-1049) - 500 error appears when trying to open order more than one time
Use the unopen inventory implementation to rollback inventory changes if encumbrances fail to be created despite validation when opening an order.
[Related test PR](https://github.com/folio-org/folio-integration-tests/pull/1267).
- [MODORDERS-1050](https://folio-org.atlassian.net/browse/MODORDERS-1050) - Add expenditure restriction checks when opening an order …
> [MODORDERS-1049] Rollback inventory if open fails to create encumbrances

- .gitignore
- src/main/java/org/folio/service/finance/transaction/EncumbranceRelationsHoldersBuilder.java
- src/main/java/org/folio/service/finance/transaction/EncumbrancesProcessingHolderBuilder.java
- src/main/java/org/folio/service/finance/transaction/PendingToPendingEncumbranceStrategy.java
- src/test/java/org/folio/ApiTestSuite.java
- src/test/java/org/folio/service/finance/transaction/PendingToPendingEncumbranceStrategyTest.java
- src/test/resources/mockdata/compositeOrders/22f0d3dd-267d-405c-9917-29395b8507d8.json
[MODORDERS-1039](https://folio-org.atlassian.net/browse/MODORDERS-1039) - Encumbrance expense class not updated after a change to the fund distribution
- For pending orders, update encumbrances with an expense class change (using the old encumbrance for some fields like the fiscal year id)
- For open orders, match fund distribution lines to old transactions by checking the fund and expense class first, and the encumbrance id next if there is no match; this is to avoid a conflict with the unique encumbrance database restriction when updating or recreating encumbrances.
- Also added `postgres-conf.json` to `.gitignore`.
**See also**: "Implementation Notes" in [MODORDERS-1039](https://folio-org.atlassian.net/browse/MODORDERS-1039).
[Related integration …
> [MODORDERS-1039] Update encumbrance expense class

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/helper/PurchaseOrderHelper.java
- src/main/java/org/folio/orders/utils/AcqDesiredPermissions.java
- src/main/java/org/folio/orders/utils/PermissionsUtil.java
- src/main/java/org/folio/service/ProtectionService.java
- src/main/java/org/folio/service/dataimport/handlers/CreateOrderEventHandler.java
- src/test/java/org/folio/rest/impl/PurchaseOrdersApiTest.java
- src/test/java/org/folio/rest/impl/TitlesApiTest.java
- src/test/java/org/folio/rest/impl/protection/LinesProtectionTest.java
- src/test/java/org/folio/rest/impl/protection/OrdersProtectionTest.java
[MODINVOICE-516](https://folio-org.atlassian.net/browse/MODINVOICE-516) - Invoice transactions should not be changed when acquisition check was failed
- Added a permission to bypass acqunit checks. It will be used in mod-invoice when updating an invoice
- Fixed English for some method names
- Updated unit tests
[Related mod-invoice PR](https://github.com/folio-org/mod-invoice/pull/479)
[Related integration test](https://github.com/folio-org/folio-integration-tests/pull/1299)
- …
> [MODINVOICE-516] Added a permission to bypass acqunit checks

- src/main/java/org/folio/service/orders/flows/update/reopen/ReOpenCompositeOrderManager.java
- src/test/java/org/folio/service/orders/flows/update/reopen/ReOpenCompositeOrderManagerTest.java
[MODORDERS-1071](https://folio-org.atlassian.net/browse/MODORDERS-1071) - PaymentStatus can be wrong after reopening an order
- When reopening and updating paymentStatus, changed invoice status check to ignore approved invoices
- Updated tests
[Integration test](https://github.com/folio-org/folio-integration-tests/pull/1302)
- Did you modify code to call …
> [MODORDERS-1071] Approved invoices should not affect paymentStatus when reopening

- src/main/java/org/folio/helper/PurchaseOrderHelper.java
- src/main/java/org/folio/orders/events/handlers/ReceiptStatusConsistency.java
- src/main/java/org/folio/rest/impl/CompositePoLineAPI.java
- src/main/java/org/folio/service/orders/CompositePoLineValidationService.java
- src/main/java/org/folio/service/orders/OrderReEncumberService.java
- src/main/java/org/folio/service/orders/OrderRolloverService.java
- src/main/java/org/folio/service/orders/flows/update/open/OpenCompositeOrderHolderBuilder.java
- src/main/java/org/folio/service/orders/flows/update/open/OpenCompositeOrderPieceService.java
- src/main/java/org/folio/service/orders/flows/update/reopen/ReOpenCompositeOrderManager.java
- src/main/java/org/folio/service/pieces/flows/create/PieceCreateFlowInventoryManager.java
- src/main/java/org/folio/service/pieces/flows/delete/PieceDeleteFlowManager.java
- src/main/java/org/folio/service/pieces/flows/update/PieceUpdateFlowInventoryManager.java
- src/main/java/org/folio/service/pieces/flows/update/PieceUpdateFlowManager.java
- src/test/java/org/folio/service/orders/flows/update/reopen/ReOpenCompositeOrderManagerTest.java
The handler used in onSuccess was called async and the method was not waiting for it to return. But also the API says:
WARNING: this is a terminal operation. If several handlers are registered, there is no guarantee that they will be invoked in order of registration.
We need to identify places where usage of onSuccess was incorrect and replace to use of map or compose methods
https://folio-org.atlassian.net/browse/MODORDERS-1078
> [MODORDERS-1078] Avoid onSuccess terminal operators in the middle of executing chain

- src/main/java/org/folio/service/orders/OrderRolloverService.java
Revert back change made in https://github.com/folio-org/mod-orders/pull/878 in OrderRolloverService because it was the desired behavior.
Rollover should start asynchronously and update status of completing by additional rest call to mod-finance. It is made in this way to avoid gateway timeout issues when mod-finance http request waits when the order rollover part completes.
Related ticket: https://folio-org.atlassian.net/browse/MODORDERS-865
> MODORDERS-1078. Revert back rollover changes to start it asynchronously

- src/main/java/org/folio/service/pieces/flows/strategies/ProcessInventoryMixedStrategy.java
- src/main/java/org/folio/service/pieces/flows/update/PieceUpdateFlowManager.java
- src/test/java/org/folio/service/pieces/flows/update/PieceUpdateFlowManagerTest.java
[MODORDERS-1079](https://folio-org.atlassian.net/browse/MODORDERS-1079) - Could not edit holdings for piece created from P/E mix Po Line
The piece/location handling code has some constraints on locations after an order is opened (physical/electronic locations have to be merged when they have the same holdingId or locationId, but separate otherwise, and they can't have both holdingId and locationId). These modifications ensure opening an order updates the locations according to these constraints.
- New logic to update locations when an order is opened
- Fixed an unrelated bug causing unwanted async processing and preventing po line location updates (introduced by MODORDERS-1027)
[Integration test](https://github.com/folio-org/folio-integration-tests/pull/1313)
Before merging this PR, …
> [MODORDERS-1079] Change in PE mix location updates + async bug fix

- src/main/java/org/folio/helper/PurchaseOrderHelper.java
- src/main/java/org/folio/helper/PurchaseOrderLineHelper.java
- src/main/java/org/folio/rest/core/exceptions/HttpException.java
- src/main/java/org/folio/rest/impl/BaseApi.java
- src/test/java/org/folio/TestUtils.java
- src/test/java/org/folio/helper/FinanceInteractionsTestHelper.java
- src/test/java/org/folio/helper/PurchaseOrderHelperTest.java
- src/test/java/org/folio/helper/PurchaseOrderLineHelperTest.java
- src/test/java/org/folio/rest/impl/PurchaseOrdersApiTest.java
- src/test/java/org/folio/service/orders/CompositePoLineValidationServiceTest.java
- src/test/java/org/folio/service/orders/OrderValidationServiceTest.java
[MODORDERS-1098](https://folio-org.atlassian.net/browse/MODORDERS-1098) - Rewrite PurchaseOrdersApiTest tests without using MockServer
Converted more tests.
- `testPostOrderWithIncorrectCost()`
-> `CompositePoLineValidationServiceTest.testValidatePoLineWithIncorrectCostForPEMixFormat()`
and `CompositePoLineValidationServiceTest.testValidatePoLineWithIncorrectCostForOtherFormat()`
- `testPostOneTimeOrderWithOngoingFields()`
-> `OrderValidationServiceTest.testValidateOrderForPostWithOngoingField()`
- `testPostOngoingOrderWithoutOngoingFields()`
-> `OrderValidationServiceTest.testValidateOrderForPostWithoutOngoingField()`
- `testPutOneTimeOrderWithOngoingField()`
-> `OrderValidationServiceTest.testValidateOrderForPutWithOngoingField()`
- `testPutOngoingOrderWithoutOngoingField()`
-> …
> [MODORDERS-1098] Converting API unit tests - part 2

- src/main/java/org/folio/service/routinglists/validators/RoutingListValidatorUtil.java
- src/test/java/org/folio/TestUtils.java
- src/test/java/org/folio/service/routinglists/validators/RoutingListValidatorTest.java
NullPointerException is thrown when the P/E Mix order format is used in PO Line and a routing list is added to it.
Add a null check when summing up PO Line location's physical quantities to determine if the routing list can be added or not
> Fix NPE when order format is P/E Mix

- NEWS.md
- src/main/java/org/folio/service/dataimport/handlers/CreateOrderEventHandler.java
- src/test/java/org/folio/service/dataimport/handlers/CreateOrderEventHandlerTest.java
to ensure fund code in imported order lines
* set po line fund code based on fundId populated during order line mapping
* add test
[MODORDERS-1102](https://issues.folio.org/browse/MODORDERS-1102)
> MODORDERS-1102 - Order lines search results do not display fund code for orders created by data import

- src/main/java/org/folio/helper/BindHelper.java
- src/main/java/org/folio/helper/CheckinReceivePiecesHelper.java
- src/main/java/org/folio/service/inventory/InventoryItemManager.java
- src/test/java/org/folio/rest/impl/CheckinReceivingApiTest.java
[[MODORDERS-1122] Add logic to create item in any tenant for binding](https://folio-org.atlassian.net/browse/MODORDERS-1122)
* Add tenantId to BindItem schema
* If tenantId is present while binding, create item in the specified tenant
> MODORDERS-1122] Add logic to create item in any tenant for binding

- src/test/java/org/folio/ApiTestSuite.java
- src/test/java/org/folio/helper/PurchaseOrderHelperTest.java
- src/test/java/org/folio/orders/utils/PoLineCommonUtilTest.java
- src/test/java/org/folio/rest/impl/BaseApiTest.java
- src/test/java/org/folio/rest/impl/PurchaseOrdersApiTest.java
- src/test/java/org/folio/service/finance/budget/BudgetServiceTest.java
[MODORDERS-1098](https://folio-org.atlassian.net/browse/MODORDERS-1098) - Rewrite PurchaseOrdersApiTest tests without using MockServer
- `testOrderWithPoLinesWithoutSource()`
-> `PurchaseOrderHelperTest.testSourceValidationInLine()`
(relates to [MODORDERS-1119](https://folio-org.atlassian.net/browse/MODORDERS-1119))
- `testDateOrderedIsNotSetForPendingOrder()`  (currently disabled)
-> removed, this is equivalent to checking that `OpenCompositeOrderManager` is not used for pending orders
- `testPostOpenOrderInventoryUpdateWithOrderFormatOther()` (currently disabled)
-> `PoLineCommonUtilTest.testIsInventoryUpdateNotRequired()`
(See also integration tests `open-order-without-holdings.feature` and `piece-operations-for-order-flows-mixed-order-line.feature` and …
> [MODORDERS-1098] Converting API unit tests - part 3

- src/main/java/org/folio/config/ApplicationConfig.java
- src/main/java/org/folio/helper/BindHelper.java
- src/main/java/org/folio/orders/utils/RequestContextUtil.java
- src/main/java/org/folio/service/orders/flows/update/open/OpenCompositeOrderPieceService.java
- src/main/java/org/folio/service/pieces/PieceDeleteInventoryService.java
- src/main/java/org/folio/service/pieces/PieceUpdateInventoryService.java
- src/main/java/org/folio/service/pieces/flows/create/PieceCreateFlowInventoryManager.java
- src/main/java/org/folio/service/pieces/flows/delete/PieceDeleteFlowInventoryManager.java
- src/main/java/org/folio/service/pieces/flows/delete/PieceDeleteFlowManager.java
- src/main/java/org/folio/service/pieces/flows/update/PieceUpdateFlowInventoryManager.java
- src/main/java/org/folio/service/titles/TitleInstanceService.java
- src/main/java/org/folio/service/titles/TitlesService.java
- src/test/java/org/folio/service/orders/flows/update/open/OpenCompositeOrderPieceServiceTest.java
- src/test/java/org/folio/service/pieces/flows/create/PieceCreateFlowInventoryManagerTest.java
- src/test/java/org/folio/service/pieces/flows/delete/PieceDeleteFlowManagerTest.java
- src/test/java/org/folio/service/pieces/flows/update/PieceUpdateFlowInventoryManagerTest.java
[[MODORDERS-1108] Update PiecesAPI CRUD methods  to process inventory in desired tenant](https://folio-org.atlassian.net/browse/MODORDERS-1108)
* Refactor existing classes
* Check for piece receivingTenantId, wherever present, use it to work on inventory items located in a different tenant.
* Keep both tenant contexts in order to be able to work for titles, pieces in the original tenant and also inventory objects in a different one
> [MODORDERS-1108] Update PiecesAPI CRUD methods  to process inventory in desired tenant

- src/main/java/org/folio/rest/core/exceptions/ErrorCodes.java
- src/main/java/org/folio/service/finance/FinanceHoldersBuilder.java
- src/main/java/org/folio/service/finance/FiscalYearService.java
- src/main/java/org/folio/service/finance/budget/BudgetService.java
- src/main/java/org/folio/service/finance/transaction/ClosedToOpenEncumbranceStrategy.java
- src/main/java/org/folio/service/finance/transaction/EncumbranceRelationsHoldersBuilder.java
- src/main/java/org/folio/service/finance/transaction/PendingToOpenEncumbranceStrategy.java
- src/main/java/org/folio/service/finance/transaction/ReceivingEncumbranceStrategy.java
- src/main/java/org/folio/service/orders/OrderReEncumberService.java
- src/main/java/org/folio/service/orders/ReEncumbranceHoldersBuilder.java
- src/test/java/org/folio/ApiTestSuite.java
- src/test/java/org/folio/service/finance/FinanceHoldersBuilderTest.java
- src/test/java/org/folio/service/finance/FundServiceTest.java
- src/test/java/org/folio/service/finance/budget/BudgetServiceTest.java
- src/test/java/org/folio/service/finance/transaction/ClosedToOpenEncumbranceStrategyTest.java
- src/test/java/org/folio/service/finance/transaction/EncumbranceRelationsHoldersBuilderTest.java
- src/test/java/org/folio/service/finance/transaction/OpenToPendingEncumbranceStrategyTest.java
- src/test/java/org/folio/service/finance/transaction/PendingToOpenEncumbranceStrategyTest.java
- src/test/java/org/folio/service/orders/OrderReEncumberServiceTest.java
- src/test/java/org/folio/service/orders/ReEncumbranceHoldersBuilderTest.java
- src/test/resources/mockdata/funds/funds.json
[MODORDERS-1118](https://folio-org.atlassian.net/browse/MODORDERS-1118) - Fix and optimize getting finance data to process encumbrances
- Optimized getting the finance data structures. Getting the current budget for all funds was generating a lot of calls that were not necessary for orders with many lines, this is now only done for a single fund.
- Refactored `ReEncumbranceHoldersBuilder` and `EncumbranceRelationsHoldersBuilder` to reduce code redundancy and make the process of getting finance data more consistent. Common code is now in `FinanceHoldersBuilder`.
- Updated unit tests. Redundant unit tests for `ReEncumbranceHoldersBuilder` and `EncumbranceRelationsHoldersBuilder` are moved to a new test: `FinanceHoldersBuilderTest`.
A side effect of the new implementation is that error …
> [MODORDERS-1118] Optimize and refactor getting finance data structures

- src/main/java/org/folio/helper/BindHelper.java
- src/main/java/org/folio/rest/core/exceptions/ErrorCodes.java
- src/main/java/org/folio/rest/impl/ReceivingAPI.java
- src/test/java/org/folio/TestUtils.java
- src/test/java/org/folio/rest/impl/CheckinReceivingApiTest.java
Modify bind pieces endpoint to accept holdingId and locationId
* Add holdingId and locationId to bindPiecesCollection.json
* Remove existing holdings validation
* Add validation to include only one field in bindItem: holdingId or locationId
* Create holding if holdingId is not present
> Modify bind pieces endpoint to accept holdingId and locationId

- src/main/java/org/folio/helper/BindHelper.java
- src/main/java/org/folio/orders/utils/CommonFields.java
- src/main/java/org/folio/orders/utils/HelperUtils.java
- src/main/java/org/folio/rest/core/exceptions/ErrorCodes.java
- src/main/java/org/folio/service/CirculationRequestsRetriever.java
- src/main/java/org/folio/service/inventory/InventoryItemManager.java
- src/main/java/org/folio/service/inventory/InventoryItemRequestService.java
- src/main/java/org/folio/service/inventory/util/RequestFields.java
- src/main/java/org/folio/service/pieces/flows/update/PieceUpdateFlowInventoryManager.java
- src/test/java/org/folio/rest/impl/CheckinReceivingApiTest.java
- src/test/java/org/folio/service/CirculationRequestsRetrieverTest.java
- src/test/java/org/folio/service/inventory/InventoryItemRequestServiceTest.java
- src/test/resources/mockdata/requests/requests.json
[[MODORDERS-1131] Fix piece, item, title relationship in bind piece features](https://folio-org.atlassian.net/browse/MODORDERS-1131)
> [MODORDERS-1131] Fix piece, item, title relationship in bind piece features

- descriptors/ModuleDescriptor-template.json
https://folio-org.atlassian.net/browse/MODORDERS-1124
PR with breaking change: https://github.com/folio-org/mod-inventory-storage/pull/1024/files
So field sourceId become required field.
No any modification in mod-orders is needed because we already populate sourceId when creating holding:
https://github.com/folio-org/mod-orders/blob/master/src/main/java/org/folio/service/inventory/InventoryHoldingManager.java#L215
> [MODORDERS-1124] API upgrade to new holdings storage version

- src/main/java/org/folio/service/inventory/util/RequestFields.java
- src/test/java/org/folio/service/CirculationRequestsRetrieverTest.java
[[MODORDERS-1131] Fix piece, item, title relationship in bind piece features](https://folio-org.atlassian.net/browse/MODORDERS-1131)
- Rename REQUESTER_ID field from itemId to requesterId
- Update corresponding unit test
> [MODORDERS-1131] Fix misspelled field name

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/helper/BindHelper.java
- src/main/java/org/folio/service/inventory/InventoryItemRequestService.java
- src/test/java/org/folio/service/inventory/InventoryItemRequestServiceTest.java
https://folio-org.atlassian.net/browse/FAT-14355
there is issue with permission and exception handling
```
ERROR FutureImpl$2         org.folio.rest.core.exceptions.HttpException: Access for user 'test-user' (00000000-1111-5555-9999-999999999992) requires permission: circulation.requests.item.put
```
adding permission to change circulation request status for transfer action and adding exception handling to notify user about error. 
Removing unsed method. This will be stored in version control system, if it need in the future
> added missing permission for changing status of circulation request and making improvements

- descriptors/ModuleDescriptor-template.json
Missing permission for bind endpoint when changing item status
> Add required permission to binding endpoint for item status

- descriptors/ModuleDescriptor-template.json
- ramls/pieces-requests.raml
- ramls/pieces.raml
- src/main/java/org/folio/config/ApplicationConfig.java
- src/main/java/org/folio/orders/utils/CommonFields.java
- src/main/java/org/folio/rest/impl/PiecesAPI.java
- src/main/java/org/folio/service/CirculationRequestsRetriever.java
- src/main/java/org/folio/service/consortium/SharingInstanceService.java
- src/main/java/org/folio/service/pieces/flows/delete/PieceDeleteFlowManager.java
- src/test/java/org/folio/service/CirculationRequestsRetrieverTest.java
- src/test/resources/mockdata/pieces/pieces-for-requests.json
[[MODORDERS-1138] Implement endpoint to fetch Circulation requests for pieces](https://folio-org.atlassian.net/browse/MODORDERS-1138)
- Add new schema for response
- Add new endpoint to fetch requests by piece ids
- Add logic to fetch requests from other tenants based on receivingTenantId of pieces
- Add unit tests
> [MODORDERS-1138] Implement endpoint to fetch Circulation requests for pieces

- src/main/java/org/folio/service/orders/lines/update/instance/WithHoldingOrderLineUpdateInstanceStrategy.java
Add tenantId param to show in UI in error message, that can help to understand in which tenant error is occured.
Related ticket - https://folio-org.atlassian.net/browse/UIOR-1290
> UIOR-1290. Add tenantId param to show in error message in UI

- src/main/java/org/folio/orders/utils/HelperUtils.java
- src/main/java/org/folio/service/inventory/InventoryItemRequestService.java
- src/main/java/org/folio/service/orders/lines/update/instance/WithHoldingOrderLineUpdateInstanceStrategy.java
https://folio-org.atlassian.net/browse/MODORDERS-1149
Without prcessing futures in chaing we had the following exception:
`org.folio.rest.core.exceptions.ConsortiumException: Error during sharing Instance for sourceTenantId: consortium, targetTenantId: college, instanceIdentifier: f14b2828-28ee-4169-9fa0-ee5c38db7e66, error: Failed to post inventory instance with reason: id value already exists in table instance: f14b2828-28ee-4169-9fa0-ee5c38db7e66`
It is because code tried to share instance from 2 locations to the same instanceId simultaneously.
> [MODORDERS-1149] Async fix

- src/main/java/org/folio/helper/CheckinReceivePiecesHelper.java
- src/main/java/org/folio/orders/utils/RequestContextUtil.java
- src/main/java/org/folio/service/inventory/InventoryHoldingManager.java
- src/main/java/org/folio/service/pieces/ItemRecreateInventoryService.java
- src/test/java/org/folio/rest/impl/CheckinReceivingApiTest.java
- src/test/resources/mockdata/lines/po_line_collection.json
- src/test/resources/mockdata/receiving/receive-physical-resources-6-of-10-with-errors.json
- <https://folio-org.atlassian.net/browse/MODORDERS-1169>
- Add a condition to prevent setting a null `holdingId` in the map, which is used to update the processed pieces
- Remove item status validation during item recreation on receive with an affiliation change
- Make holding creation apply for every piece that has an incoming `locationId`, which requires a new holding to be made
- Simplify item recreation method to fetch an item from the source tenant before other operations
- Tested with mod-orders and cross-module Karate tests:
- ![image](https://github.com/user-attachments/assets/398d935f-7a4c-43df-82b3-307fb2769d8e)
- ![image](https://github.com/user-attachments/assets/17dfd950-9836-4f6e-9698-e0c7a9a4d10c)
> [MODORDERS-1169]. Fix piece update on null processedHoldings.get(holdingKey)

- src/main/java/org/folio/config/ApplicationConfig.java
- src/main/java/org/folio/rest/impl/OrderTemplatesAPI.java
- src/main/java/org/folio/rest/impl/OrdersApi.java
- src/main/java/org/folio/service/finance/transaction/ReceivingEncumbranceStrategy.java
- src/main/java/org/folio/service/inventory/InventoryItemManager.java
- src/main/java/org/folio/service/orders/PurchaseOrderLineService.java
- src/main/java/org/folio/service/pieces/PieceUpdateInventoryService.java
- src/main/java/org/folio/service/pieces/PieceUtil.java
- src/main/java/org/folio/service/pieces/flows/BasePieceFlowUpdatePoLineService.java
- src/main/java/org/folio/service/pieces/flows/create/PieceCreateFlowInventoryManager.java
- src/main/java/org/folio/service/pieces/flows/create/PieceCreateFlowManager.java
- src/main/java/org/folio/service/pieces/flows/create/PieceCreateFlowPoLineService.java
- src/main/java/org/folio/service/pieces/flows/delete/PieceDeleteFlowPoLineService.java
- src/main/java/org/folio/service/pieces/flows/update/PieceUpdateFlowInventoryManager.java
- src/main/java/org/folio/service/pieces/flows/update/PieceUpdateFlowManager.java
- src/main/java/org/folio/service/pieces/flows/update/PieceUpdateFlowPoLineService.java
- src/test/java/org/folio/service/inventory/InventoryManagerTest.java
- src/test/java/org/folio/service/orders/lines/update/OrderLineUpdateInstanceHandlerTest.java
- src/test/java/org/folio/service/pieces/flows/create/PieceCreateFlowPoLineServiceTest.java
- src/test/java/org/folio/service/pieces/flows/delete/PieceDeleteFlowPoLineServiceTest.java
- src/test/java/org/folio/service/pieces/flows/update/PieceUpdateFlowManagerTest.java
- src/test/java/org/folio/service/pieces/flows/update/PieceUpdateFlowPoLineServiceTest.java
https://folio-org.atlassian.net/browse/MODORDERS-1177
Update only those locations that is related to the piece, but not all locations. It allows to reduce lot of http calls to fetch holdings for other not modified locations. Also it allowed to fix root cause of the issue because call to tenant where user does not have an affiliation is not made
> [MODORDERS-1177] A user cannot add/edit piece when related order has another pieces with affiliations in tenants user does not belong to

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/config/ApplicationConfig.java
- src/main/java/org/folio/helper/BindHelper.java
- src/main/java/org/folio/helper/CheckinReceivePiecesHelper.java
- src/main/java/org/folio/orders/utils/RequestContextUtil.java
- src/main/java/org/folio/orders/utils/ResourcePathResolver.java
- src/main/java/org/folio/service/consortium/ConsortiumUserTenantsRetriever.java
- src/main/java/org/folio/service/orders/HoldingsSummaryService.java
- src/main/java/org/folio/service/pieces/PieceStorageService.java
- src/main/java/org/folio/service/pieces/util/UserTenantFields.java
- src/test/java/org/folio/service/CirculationRequestsRetrieverTest.java
- src/test/java/org/folio/service/inventory/HoldingsSummaryServiceTest.java
- src/test/java/org/folio/service/orders/lines/update/OrderLineUpdateInstanceHandlerTest.java
- src/test/java/org/folio/service/pieces/PieceStorageServiceTest.java
- src/test/resources/mockdata/pieces/pieces-for-user-tenants.json
- src/test/resources/mockdata/userTenants/userTenants.json
[[MODORDERS-1174] Filter pieces based on user affiliations](https://folio-org.atlassian.net/browse/MODORDERS-1174)
- Fetch user tenants in case of ECS mode
- Filter pieces with user tenants if needed
- Update tests
> [MODORDERS-1174] Filter pieces based on user affiliations

- src/main/java/org/folio/helper/PurchaseOrderLineHelper.java
- src/test/java/org/folio/helper/PurchaseOrderLineHelperTest.java
- <https://folio-org.atlassian.net/browse/MODORDERS-1185>
- Add exchange value validation on POL exchange rate update
- Tested by unit tests, current mod-orders & cross module tests, and additional cross-module tests
> [MODORDERS-1185]. Encumbrance amount does not update when exchange rate is edited on open order

- src/main/java/org/folio/orders/utils/PoLineCommonUtil.java
- src/main/java/org/folio/rest/core/exceptions/ErrorCodes.java
- src/main/java/org/folio/service/pieces/flows/delete/PieceDeleteFlowManager.java
- src/test/java/org/folio/TestUtils.java
- src/test/java/org/folio/rest/impl/PieceApiTest.java
- src/test/java/org/folio/service/pieces/flows/delete/PieceDeleteFlowManagerTest.java
https://folio-org.atlassian.net/browse/MODORDERS-1195
- added validation to avoid order status closed and poLine quantity = 1 and Synchronized Receiving Workflow
It will throw error if it try to delete piece based on conditions
> [MODORDERS-1195] - Closed purchase order line associated with a deleted piece record cannot be saved

- pom.xml
[[MODORDERS-1194] Update libraries of dependant acq modules to the latest versions
](https://folio-org.atlassian.net/browse/MODORDERS-1194)
- Update versions
- Add module descriptor validator
> [MODORDERS-1194] Update libraries of dependant acq modules to the latest versions

- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/java/org/folio/config/ApplicationConfig.java
- src/main/java/org/folio/orders/utils/CacheUtils.java
- src/main/java/org/folio/orders/utils/HelperUtils.java
- src/main/java/org/folio/orders/utils/ResourcePathResolver.java
- src/main/java/org/folio/service/caches/ConfigurationEntriesCache.java
- src/main/java/org/folio/service/caches/InventoryCache.java
- src/main/java/org/folio/service/caches/JobExecutionTotalRecordsCache.java
- src/main/java/org/folio/service/caches/JobProfileSnapshotCache.java
- src/main/java/org/folio/service/caches/MappingParametersCache.java
- src/main/java/org/folio/service/configuration/ConfigurationEntriesService.java
- src/main/java/org/folio/service/consortium/ConsortiumConfigurationService.java
- src/main/java/org/folio/service/consortium/ConsortiumUserTenantsRetriever.java
- src/main/java/org/folio/service/finance/FiscalYearService.java
- src/main/java/org/folio/service/orders/CompositeOrderTotalFieldsPopulateService.java
- src/main/java/org/folio/service/organization/OrganizationService.java
- src/main/java/org/folio/service/settings/SettingsRetriever.java
- src/test/java/org/folio/service/caches/ConfigurationEntriesCacheTest.java
- src/test/java/org/folio/service/configuration/ConfigurationEntriesServiceTest.java
- src/test/java/org/folio/service/finance/FiscalYearServiceTest.java
- src/test/java/org/folio/service/orders/CompositeOrderTotalFieldsPopulateServiceTest.java
[[MODORDERS-1203] Total expended amount is not displayed when order has no fund distributions](https://folio-org.atlassian.net/browse/MODORDERS-1203)
- Refactor configuration entries service and cache
- Fetch and cache system time zone
- Extend fiscal year service to fetch current fiscal year for series
- Update and add new generated tests
https://github.com/folio-org/folio-integration-tests/pull/1592
> [MODORDERS-1203] Total expended amount is not displayed when order has no fund distributions

- NEWS.md
- pom.xml
https://folio-org.atlassian.net/browse/FOLIO-4102 …
> Release v12.9.0

- src/main/java/org/folio/helper/PurchaseOrderLineHelper.java
- src/main/java/org/folio/service/consortium/ConsortiumUserTenantsRetriever.java
- src/main/java/org/folio/service/pieces/PieceStorageService.java
- src/test/java/org/folio/helper/PurchaseOrderLineHelperTest.java
- <https://folio-org.atlassian.net/browse/MODORDERS-1208>
- Make `ConsortiumUserTenantsRetriever.getUserTenants()`  method use central tenant id
- Manually tested on TJ ECS Rancher
> [MODORDERS-1208]. ECS | Invoice linked with POL can not be paid in Member tenant

- descriptors/ModuleDescriptor-template.json
- ramls/pieces-batch.raml
- ramls/pieces.raml
- src/main/java/org/folio/config/ApplicationConfig.java
- src/main/java/org/folio/models/pieces/PieceBatchStatusUpdateHolder.java
- src/main/java/org/folio/orders/events/handlers/ReceiptStatusConsistency.java
- src/main/java/org/folio/orders/events/utils/EventUtils.java
- src/main/java/org/folio/orders/utils/FutureUtils.java
- src/main/java/org/folio/rest/impl/PiecesAPI.java
- src/main/java/org/folio/service/orders/flows/update/open/OpenCompositeOrderPieceService.java
- src/main/java/org/folio/service/orders/utils/StatusUtils.java
- src/main/java/org/folio/service/pieces/PieceService.java
- src/main/java/org/folio/service/pieces/PieceUtil.java
- src/main/java/org/folio/service/pieces/flows/update/PieceUpdateFlowManager.java
- src/test/java/org/folio/orders/events/handlers/HandlersTestHelper.java
- src/test/java/org/folio/orders/events/handlers/ReceiptStatusConsistencyTest.java
- src/test/java/org/folio/orders/utils/StatusUtilsTest.java
- src/test/java/org/folio/service/pieces/flows/update/PieceUpdateFlowManagerTest.java
[[MODORDERS-1210] Implement API to change piece statuses in batch](https://folio-org.atlassian.net/browse/MODORDERS-1210)]
- Minor refactoring of existing classes
- Add new endpoint
- Add status update method to PieceUpdateFlowManager
- Updated unit tests
- Added new unit tests
- Updated module descriptor
> [MODORDERS-1210] Implement API to change piece statuses in batch

- src/main/java/org/folio/service/pieces/flows/update/PieceUpdateFlowManager.java
[[MODORDERS-1210] Implement API to change piece statuses in batch](https://folio-org.atlassian.net/browse/MODORDERS-1210)
- First validate operation restriction to avoid unnecessary API call
- Add fetched piece quantity validation
- Changed error response in case piece is not found
```
{
"errors": [
{
"message": "The piece record is not found",
"code": "pieceNotFound",
"parameters": [
{
"key": "pieceIds",
"value": "[479b2177-3dc8-46aa-8cbc-81d0a1456242]"
}
]
}
],
"total_records": 1
}
```
> [MODORDERS-1210] Improve validation for piece batch status update

- src/main/java/org/folio/config/ApplicationConfig.java
- src/main/java/org/folio/helper/PurchaseOrderHelper.java
- src/main/java/org/folio/helper/PurchaseOrderLineHelper.java
- src/main/java/org/folio/service/orders/CompositePoLineValidationService.java
- src/test/java/org/folio/helper/PurchaseOrderHelperTest.java
- src/test/java/org/folio/helper/PurchaseOrderLineHelperTest.java
- src/test/java/org/folio/service/orders/CompositePoLineValidationServiceTest.java
- <https://folio-org.atlassian.net/browse/EUREKA-561>
- Add `validateUserUnaffiliatedLocationUpdates` to `updateOrder` method to guard against unaffiliated order opening/unopening
- Tested with Karate tests against a mod-orders modules:
> [EUREKA-561-4]. Add validateUserUnaffiliatedLocationUpdates method to Order Open/unopen

- src/main/java/org/folio/helper/PurchaseOrderHelper.java
- src/main/java/org/folio/service/finance/transaction/EncumbranceRelationsHoldersBuilder.java
- src/test/java/org/folio/service/finance/transaction/EncumbranceRelationsHoldersBuilderTest.java
https://folio-org.atlassian.net/browse/MODORDERS-1222
- Filtered duplicate poLines in side of retrieveMapFiscalYearsWithCompPOLines method
> [MODORDERS-1222] - Error when trying to Unopen an ongoing order to add a purchase order line with multiple funds

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/java/org/folio/service/consortium/ConsortiumConfigurationService.java
- src/main/java/org/folio/service/orders/CompositePoLineValidationService.java
- src/test/java/org/folio/service/orders/CompositePoLineValidationServiceTest.java
Release v12.9.5 to to add missed module permission and do some queries optimization for fetching user-tenants for validation
only when the Central Ordering feature is enabled.
> Release mod-orders v12.9.5

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/helper/BindHelper.java
Revert previous logic to ovveride to central tenant context, because it is not fix issue when we make binding from member tenant and member segment is selected.
Instead UI will provide correct tenantId header in scope of this ticket: 
https://folio-org.atlassian.net/browse/UIREC-422
> UIREC-422. Revert logic to override to centralTenantContext

- src/main/java/org/folio/service/CirculationRequestsRetriever.java
- src/main/java/org/folio/service/inventory/InventoryItemRequestService.java
- src/main/java/org/folio/service/inventory/util/RequestFields.java
[[MODORDERS-1231] ECS | List of requests previously related to bound pieces is displayed in wrong order](https://folio-org.atlassian.net/browse/MODORDERS-1231)
- Improve logging
- Add sorting for request transfer
> [MODORDERS-1231] ECS | List of requests previously related to bound pieces is displayed in wrong order

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/helper/BindHelper.java
- src/main/java/org/folio/service/consortium/ConsortiumConfigurationService.java
[[MODORDERS-1211] ECS | User in member tenant cannot bind pieces related to order from Central tenant](https://folio-org.atlassian.net/browse/MODORDERS-1211)
- Switch context to central tenant if needed before binding
- Use correct context to fetch settings
> [MODORDERS-1211] ECS | User in member tenant cannot bind pieces related to order from Central tenant

- src/main/java/org/folio/helper/PurchaseOrderHelper.java
- src/main/java/org/folio/helper/PurchaseOrderLineHelper.java
- src/main/java/org/folio/orders/events/handlers/AbstractOrderStatusHandler.java
- src/main/java/org/folio/orders/events/handlers/ReceiptStatusConsistency.java
- src/main/java/org/folio/rest/core/RestClient.java
- src/main/java/org/folio/rest/impl/AcquisitionsUnitsApi.java
- src/main/java/org/folio/rest/impl/CompositePoLineAPI.java
- src/main/java/org/folio/rest/impl/HoldingsSummaryAPI.java
- src/main/java/org/folio/rest/impl/OrderTemplatesAPI.java
- src/main/java/org/folio/rest/impl/PiecesAPI.java
- src/main/java/org/folio/rest/impl/ReceivingAPI.java
- src/main/java/org/folio/service/CirculationRequestsRetriever.java
- src/main/java/org/folio/service/configuration/ConfigurationEntriesService.java
- src/main/java/org/folio/service/dataimport/handlers/OrderPostProcessingEventHandler.java
- src/main/java/org/folio/service/finance/transaction/EncumbranceService.java
- src/main/java/org/folio/service/finance/transaction/TransactionService.java
- src/main/java/org/folio/service/inventory/InventoryHoldingManager.java
- src/main/java/org/folio/service/inventory/InventoryInstanceManager.java
- src/main/java/org/folio/service/inventory/InventoryItemManager.java
- src/main/java/org/folio/service/orders/PurchaseOrderLineService.java
- src/main/java/org/folio/service/orders/flows/update/unopen/UnOpenCompositeOrderManager.java
- src/main/java/org/folio/service/pieces/PiecesClaimingService.java
- src/main/java/org/folio/service/pieces/flows/DefaultPieceFlowsValidator.java
- <https://folio-org.atlassian.net/browse/MODORDERS-1227>
- Remove sensitive logs that can potentially leak PIIs
- Search parameters:
- `src/main/java` path
- `log.info`, `log.debug`, `log.warn`, `log.error`, `log.trace` markers
- `logger.info`, `logger.debug`, `logger.warn`, `logger.error`, `logger.trace`  markers
- `JsonObject.mapFrom`, `JsonArray.of()` markers
> [MODORDERS-1227]. Perform a new round of deletion of sensitive information from logs in acq modules

- src/main/java/org/folio/service/orders/CompositeOrderTotalFieldsPopulateService.java
- src/test/java/org/folio/service/orders/CompositeOrderTotalFieldsPopulateServiceTest.java
[MODORDERS-1248](https://folio-org.atlassian.net/browse/MODORDERS-1248) - Total expended value on order details pane contains invoice total value instead of invoice line total
- Added a filter using invoice lines' poLineId to filter invoice lines used to calculate total expended amount.
- Fixed unit tests and added a new one.
[Integration test PR](https://github.com/folio-org/folio-integration-tests/pull/1680)
> [MODORDERS-1248] Use only invoice lines related to the order to calculate total expended

- src/main/java/org/folio/service/finance/transaction/PendingToPendingEncumbranceStrategy.java
- src/main/java/org/folio/service/finance/transaction/TransactionService.java
- src/test/java/org/folio/service/finance/transaction/PendingToPendingEncumbranceStrategyTest.java
[MODORDERS-1253](https://folio-org.atlassian.net/browse/MODORDERS-1253) - User can edit fund distribution for unopened order with inactive budget in POL
Do not release 0 amount encumbrances before deleting them. The potential invoice connection will still be checked, but the budget activity will not be checked anymore.
This makes sense because deleting a 0 amount encumbrance would not change the budget anyway. Being able to delete them even when they use an inactive budget can be useful for pending orders.
[integration test PR](https://github.com/folio-org/folio-integration-tests/pull/1715)
If there …
> [MODORDERS-1253] Do not release 0 amount encumbrance before deleting

- src/main/java/org/folio/models/claiming/IntegrationDetailField.java
- src/main/java/org/folio/service/pieces/PiecesClaimingService.java
- src/test/java/org/folio/rest/impl/PiecesClaimingApiTest.java
- <https://folio-org.atlassian.net/browse/MODEXPW-578>
- Add a missing Job id into the Claiming integration detail to prevent the newly created job from overwriting the existing one
- Some proof of change from Thunderjet edev running Telepresense:
> 4 Claiming jobs (3 Successful & 1 Scheduled/debug terminated) 
> 4 Claiming jobs with their individual Job ids correctly populated, and resembling the jobs of Ordering type
> [MODEXPW-578]. New claiming job erases the old ones in "Export manager"

- src/main/java/org/folio/helper/PurchaseOrderHelper.java
- src/main/java/org/folio/helper/PurchaseOrderLineHelper.java
[MODORDERS-1283](https://folio-org.atlassian.net/browse/MODORDERS-1283) - Reopen an order creates an additional encumbrance
- Fixed the bug. See comment in ticket.
The new implementation reflects the way it was working before [MODORDERS-1269](https://folio-org.atlassian.net/browse/MODORDERS-1269), preserving the lines of `poFromStorage` in `PurchaseOrderHelper.updateOrder()`, but with a clearer implementation. It still might not work well if someone opened an order at the same time as removing a line from the composite order, but thankfully this is not likely to happen.
- Renamed a poorly named variable in `PurchaseOrderHelper` (unrelated).
- Does this PR meet or exceed the expected quality …
> [MODORDERS-1283] Fixed bug with encumbrances when unopening/reopening an order

- src/main/java/org/folio/config/ApplicationConfig.java
- src/main/java/org/folio/helper/PurchaseOrderLineHelper.java
- src/main/java/org/folio/rest/core/exceptions/ErrorCodes.java
- src/test/java/org/folio/rest/impl/PurchaseOrderLinesApiTest.java
Make the same validation as UI supposed to do in order to protect API users.
Related Jira ticket: https://folio-org.atlassian.net/browse/MODORDERS-1287
> MODORDERS-1287. Unopen order with synchronized workflow and received item cannot be opened

- src/main/java/org/folio/service/orders/flows/update/unopen/UnOpenCompositeOrderManager.java
- src/main/java/org/folio/service/pieces/PieceStorageService.java
- src/test/java/org/folio/rest/impl/MockServer.java
- src/test/java/org/folio/rest/impl/PurchaseOrdersApiTest.java
- src/test/resources/minimal_order.json
[[MODORDERS-1295] Not received pieces in statuses different from "Expected" are not deleted after related order was unopened](https://folio-org.atlassian.net/browse/MODORDERS-1295)
Delete pieces with status other than 'Received' after unopening the order
> [MODORDERS-1295] Not received pieces in statuses different from "Expected" are not deleted after related order was unopened

- src/main/java/org/folio/service/finance/transaction/EncumbranceWorkflowStrategy.java
- src/main/java/org/folio/service/finance/transaction/OpenToPendingEncumbranceStrategy.java
- src/main/java/org/folio/service/finance/transaction/PendingToOpenEncumbranceStrategy.java
- src/main/java/org/folio/service/orders/flows/update/open/OpenCompositeOrderManager.java
- src/test/java/org/folio/service/finance/transaction/PendingToOpenEncumbranceStrategyTest.java
- src/test/java/org/folio/service/orders/flows/update/open/OpenCompositeOrderManagerTest.java
- <https://folio-org.atlassian.net/browse/MODORDERS-1278>
- Add mapping of `fiscalYearId` on Purchase Order Open/Unopen operation
- Add mapping of `openedById` on Purchase Order Open operation
- Cover new fields with unit tests
> [MODORDERS-1278]. Display the fiscal year in which the Order was opened based on "Date opened"

- src/main/java/org/folio/service/inventory/InventoryInstanceManager.java
- src/test/java/org/folio/service/inventory/InventoryInstanceManagerTest.java
[MODORDERS-1310](https://folio-org.atlassian.net/browse/MODORDERS-1310) - Make Local order matching ECS aware such that shadows will be created for shared instances before local instances will be created.
- Changed the logic when an order is opened, to get an instance record and possibly create one and shadow instances.
- Only create shadow instances when the po line does not already have an instance id, the product ids are present, there is no matching instance in the member tenant, but there is a matching instance in the central tenant.
- Moved public methods to the top
- Updated tests
Integration tests
[integration test PR](https://github.com/folio-org/folio-integration-tests/pull/1911)
- Does …
> [MODORDERS-1310] Avoid creating unnecessary shadow instances

- src/main/java/org/folio/helper/CheckinReceivePiecesHelper.java
- <https://folio-org.atlassian.net/browse/MODORDERS-1296>
- Fixed an NPE by returning and empty Future
- Tested with 2 users where diku_admin was Creating a PO+POL and Opening an Order, while diku_user was Quick Receiving the Piece, and in all cases I didn't see an incorrect user being set in the metadata
- Below is the attached audit logs joining with a POL and User, we expect the 3 last records for each POL to be of diku_user, because diku_user was Quick Receiving the Piece:
(ignoreTest3 POL title, I forgot to re-login)
> intermittent order receiving issue - wrong name recorded in audit record, nullPointer logged

- src/main/java/org/folio/rest/core/exceptions/ErrorCodes.java
- src/main/java/org/folio/service/orders/PoLineValidationService.java
- src/test/java/org/folio/rest/impl/PurchaseOrdersApiTest.java
- src/test/java/org/folio/service/dataimport/handlers/CreateOrderEventHandlerTest.java
- src/test/java/org/folio/service/orders/PoLineValidationServiceTest.java
- src/test/resources/po_listed_print_serial_with_receipt_payment_not_required.json
[[MODORDERS-1065] Validate checkinItems based on receiptStatus](https://folio-org.atlassian.net/browse/MODORDERS-1065)
Add validation on POL receiptStatus for creation and update
> [MODORDERS-1065] Validate checkinItems based on receiptStatus

- descriptors/ModuleDescriptor-template.json
- ramls/configuration.raml
There are flags needed for the order settings to be able to deprecate suffixes and prefixes. Thus we will be able to hide deprecated suffixes and prefixes in the order creation and also search by deprecated or not deprecated values.
Updating the schemas is required work for the above adjustments in mod-orders and mod-orders-storage.
https://folio-org.atlassian.net/browse/MODORDERS-1320
By updateing acq-models and rebuilding, we can now work with the deprecated property of suffixes and prefixes. …
> MODORDERS-1320 Backend for Enabling the deactivation of obsolete Order Suffix/Prefix values

- src/main/java/org/folio/service/exchange/CacheableExchangeRateService.java
- src/main/java/org/folio/service/exchange/CustomExchangeRateProvider.java
- src/main/java/org/folio/service/exchange/ManualCurrencyConversion.java
- src/main/java/org/folio/service/finance/FinanceHoldersBuilder.java
- src/main/java/org/folio/service/inventory/InventoryItemManager.java
- src/main/java/org/folio/service/orders/CompositeOrderTotalFieldsPopulateService.java
- src/main/java/org/folio/service/orders/OrderLinesSummaryPopulateService.java
- src/main/java/org/folio/service/orders/OrderRolloverService.java
- src/main/java/org/folio/service/orders/ReEncumbranceHoldersBuilder.java
- src/test/java/org/folio/TestConfig.java
- src/test/java/org/folio/service/exchange/ManualCurrencyConversionTest.java
- src/test/java/org/folio/service/orders/OrderRolloverServiceTest.java
- <https://folio-org.atlassian.net/browse/MODFIN-434>
- Update CacheableExchangeRateService to support a new operationMode field
- Update Order Totals, Order Opening, Rollover and Re-encumber Encumbrances by setting the new operationMode field
> [MODFIN-434]. Update Treasury exchange rate provider handler to allow using the same exchange rate in both directions

- src/main/java/org/folio/service/pieces/PieceStorageService.java
- src/test/java/org/folio/service/pieces/PieceStorageServiceTest.java
https://folio-org.atlassian.net/browse/MODORDERS-1328
_Provide a brief technical summary of the changes._
---
> MODORDERS-1328. /mod-orders/orders/pieces?query=holdingId - Can return http 414

- src/main/java/org/folio/config/ApplicationConfig.java
- src/main/java/org/folio/service/orders/PurchaseOrderLineService.java
- src/main/java/org/folio/service/orders/lines/update/instance/BaseOrderLineUpdateInstanceStrategy.java
- src/main/java/org/folio/service/orders/lines/update/instance/WithHoldingOrderLineUpdateInstanceStrategy.java
- src/main/java/org/folio/service/orders/lines/update/instance/WithoutHoldingOrderLineUpdateInstanceStrategy.java
- src/main/java/org/folio/service/orders/utils/PoLineFields.java
- src/main/java/org/folio/service/pieces/PieceStorageService.java
- src/main/java/org/folio/service/pieces/util/PieceFields.java
- src/test/java/org/folio/service/orders/lines/update/OrderLineUpdateInstanceHandlerTest.java
- src/test/java/org/folio/service/orders/lines/update/instance/WithHoldingOrderLineUpdateInstanceStrategyTest.java
[[MODORDERS-1333] Do not delete used holdings during instance connection change](https://folio-org.atlassian.net/browse/MODORDERS-1333) 
- Add methods to fetch Pieces and POLs by holding IDs
- Filter out used holdings when deleting abandoned ones
- Update existing tests to cover new cases
---
> [MODORDERS-1333] Do not delete used holdings during instance connection change

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/helper/BaseHelper.java
- src/main/java/org/folio/helper/BindHelper.java
- src/test/java/org/folio/rest/impl/CheckinReceivingApiTest.java
- src/test/java/org/folio/rest/impl/MockServer.java
https://folio-org.atlassian.net/browse/MODORDERS-1289
Delete holding(if it was created previously) due to errors connected with item creation
---
> MODORDERS-1289. Holding is created despite an error about non-unique barcode during binding process

- src/main/java/org/folio/service/finance/transaction/EncumbrancesProcessingHolderBuilder.java
[[MODORDERS-1359] Encumbrance is pending after unopen-open](https://folio-org.atlassian.net/browse/MODORDERS-1359)
- Add encumbrance status check when filtering updatable transactions
- Verified with a new karate test scenario: https://github.com/folio-org/folio-integration-tests/pull/2014
---
---
> [MODORDERS-1359] Encumbrance is pending after unopen-open

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/config/ApplicationConfig.java
- src/main/java/org/folio/models/pieces/OpenOrderPieceHolder.java
- src/main/java/org/folio/rest/core/exceptions/ErrorCodes.java
- src/main/java/org/folio/service/orders/flows/update/open/OpenCompositeOrderHolderBuilder.java
- src/main/java/org/folio/service/orders/flows/update/open/OpenCompositeOrderPieceService.java
- src/main/java/org/folio/service/pieces/flows/DefaultPieceFlowsValidator.java
- src/main/java/org/folio/service/pieces/flows/create/PieceCreateFlowManager.java
- src/main/java/org/folio/service/pieces/flows/update/PieceUpdateFlowManager.java
- src/main/java/org/folio/service/titles/TitlesService.java
- src/test/java/org/folio/rest/impl/MockServer.java
- src/test/java/org/folio/service/orders/flows/update/open/OpenCompositeOrderPieceServiceTest.java
- src/test/java/org/folio/service/pieces/flows/DefaultPieceFlowsValidatorTest.java
- src/test/java/org/folio/service/titles/TitlesServiceTest.java
[[MODORDERS-1356] BE - Create Sequence field in receiving](https://folio-org.atlassian.net/browse/MODORDERS-1356)
- Add method for populating sequence number for pieces
- Add validation for piece sequence numbers
- Integrate sequence number population in all places where pieces are created
- Update tests
---
> [MODORDERS-1356] BE - Create Sequence field in receiving
